### PR TITLE
Low-order refined interpolation [lor-interp-dev]

### PR DESCRIPTION
**Pull request by v-dobrev**
Implementation of LOR interpolation in a new method `FiniteElementSpace::GetTransferOperator`, based on a new virtual method, `FiniteElement::GetLocalInterpolation`.

This is similar to PR #286, however, the mapping of points to physical space and back is avoided, and existing code is reused to simplify the implementation.

TODO:
- [x] Decide between this and #286 
- [x] Demonstrate non-identity HO->LOR "interpolation" in HPC Example 1? --> another PR
- [x] Add a parallel version

### CODE REVIEW

**Comment by tzanio** [comment]
Do we want to update the HPC Example 1 to support e.g. `ClosedUniform` LOR basis for dofs in `GaussLobatto`?

**Comment by barker29** [comment]
I think a better example than `ClosedUniform` might be to precondition an eg. 3rd order problem with a 2nd order problem on the same mesh - this feels (to me) less contrived than using a uniform basis.

**Comment by v-dobrev** [comment]
The right way to transfer true-dof data in parallel is to consecutively apply: first apply the HO prolongation operator,`P_ho` (on the coarse mesh), then apply locally the transfer operator `T` returned by `GetTransferOperator` and finally apply the low-order restriction operator `R_lo` (on the refined mesh). In other words, you simply do `vt_lo = R_lo T P_ho vt_ho`, where `vt_*` are true-dof vectors. For use as a prolongation and restriction operator in MG, we can form the operator using the "matrix-free" `TripleProductOperator` class, or we can assemble it as a `HypreParMatrix` without communication (since only `P_ho` has off-diagonal).

If you have a `ParGridFunction`-size vector, generally you have to do `v_lo = P_lo R_lo T P_ho R_ho v_ho`, where `v_*` are `ParGridFunction`-size vectors. In some cases, you may already know that `P_ho R_ho v_ho = v_ho` (i.e. `v_ho` is "synchronized"), so the formula will simplify to `v_lo = P_lo R_lo T v_ho`. I think that for the type of meshes we currently support we always have `P_lo R_lo T P_ho = T P_ho` - generally this will not be true in the case of non-conforming meshes (if/when we support that in the future). So currently, if `v_ho` is "synchronized" then we have `v_lo = T v_ho`.

**Comment by v-dobrev** [comment]
Regarding the demo of this in the HPC examples: I think it can be done in a separate branch + PR but I'll be OK if you want to do it now.

**Comment by tzanio** [comment]
> Regarding the demo of this in the HPC examples: I think it can be done in a separate branch + PR but I'll be OK if you want to do it now.

Separate PR is fine with me, lets just not forget about it :)

**Comment by tzanio** [comment]
To peraphrase https://github.com/mfem/mfem/pull/437#issuecomment-369079645: `GetTransferOperator` is basically defining a `DiscreteLinearOperator` and its parallel version should be assembled with `P_ho` and `R_lor` as in 

https://github.com/mfem/mfem/blob/master/fem/pbilinearform.cpp#L468-L477

This will probably be useful to have for LOR preconditioning. I also wonder if there is any benefit to formally construct a `DiscreteLinearOperator` object.

**Comment by barker29** [comment]
I pushed a parallel version in `ParFiniteElementSpace::ParallelAssembleTransferOperator`. I won't tick the TODO box until somebody else has looked at it.

**Comment by tzanio** [comment]
I changed the name to `GetTransferMatrix`. Otherwise looks good to me, thanks @barker29!

@v-dobrev can you take a look and merge in `next` if you are OK with it?

**Comment by v-dobrev** [comment]
@tzanio, @barker29,

I made the method virtual, changed its name to: `GetTrueTransferOperator` and implemented it in serial and in parallel. It can return both assembled transfer matrices (`SparseMatrix` in serial, `HypreParMatrix` in parallel) and "matrix-free" transfer operators. The implementation required some extensions in other places.

Take a look and let me know if are OK with these changes.

**Comment by tzanio** [comment]
Looks great, thank you @v-dobrev!

**Pull request merged**
