### PR TITLE
This is a hotfix for codecov

### PR DESCRIPTION
**Pull request by adrienbernede**
Makes patch coverage "informational".

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2212](https://github.com/mfem/mfem/pull/2212) | @adrienbernede | @tzanio | @tzanio + @pazner | 04/30/21 | 04/30/21 | 04/30/21 | |

### CODE REVIEW

**Comment by adrienbernede** [comment]
@tzanio, spotted by @pazner. Tested in https://github.com/mfem/mfem/pull/2211.

**Review by pazner — APPROVED** [review]

**Comment by tzanio** [comment]
what does this mean?

**Comment by pazner** [comment]
It will prevent the CI from failing because of the codecov/patch test (see for example #2197)

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
