### PR TITLE
Fixed support for HIP managed memory allocation/deallocation in the memory manager

### PR DESCRIPTION
**Pull request by helloworld922**
The managed memory code previously tried to call Cuda related functions. This fix forwards to the correct HIP functions.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4523](https://github.com/mfem/mfem/pull/4523) | @helloworld922 | @tzanio | @tzanio + @v-dobrev | 10/1/24 | 10/27/24 | 11/3/24 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
ping: @v-dobrev

**Comment by v-dobrev** [comment]
To test this PR, I built HYPRE with uvm memory (config option `--enable-unified-memory`) and then MFEM with MPI and HIP. In this setting, there are some failures when running the MFEM tests with `make test`.

@helloworld922, what tests did you run with this PR?

**Comment by v-dobrev** [comment]
As I suspected the above failures are not specific to HIP builds -- the same issues can be seen with CUDA (HYPRE + CUDA + UVM and MFEM + MPI + CUDA).

**Comment by v-dobrev** [comment]
I just pushed a fix for one of the issues -- this came up recently in another context too, so thought it's good to address it.

**Comment by helloworld922** [comment]
I only ran a few examples for testing on lassen and tioga, as well as relied on the auto test.

I just did a `make test` with CUDA+HYPRE and CUDA+METIS+MPI+MFEM with a debug and release build (there doesn't appear to be an `MFEM_DEBUG` option for CMake?), and in this branch there are a lot of test failures/tests not run.

> The following tests FAILED:
          1 - unit_tests (Not Run)
          2 - cunit_tests (Not Run)
          3 - sedov_tests_cpu (Not Run)
          4 - sedov_tests_debug (Not Run)
          5 - sedov_tests_cuda (Not Run)
          6 - sedov_tests_cuda_uvm (Not Run)
          7 - tmop_pa_tests_cpu (Not Run)
          8 - tmop_pa_tests_debug (Not Run)
          9 - tmop_pa_tests_cuda (Not Run)
         10 - punit_tests_np=1 (Failed)
         11 - punit_tests_np=4 (Failed)
         12 - pcunit_tests_np=1 (Failed)
         13 - pcunit_tests_np=4 (Failed)
         14 - psedov_tests_cpu_np=1 (Failed)
         15 - psedov_tests_cpu_np=4 (Failed)
         16 - psedov_tests_debug_np=1 (Failed)
         17 - psedov_tests_debug_np=4 (Failed)
         18 - psedov_tests_cuda_np=1 (Failed)
         19 - psedov_tests_cuda_np=4 (Failed)
         20 - psedov_tests_cuda_uvm_np=1 (Failed)
         21 - psedov_tests_cuda_uvm_np=4 (Failed)
         22 - ptmop_pa_tests_cpu_np=1 (Failed)
         23 - ptmop_pa_tests_cpu_np=4 (Failed)
         24 - ptmop_pa_tests_cuda_np=1 (Failed)
         25 - ptmop_pa_tests_cuda_np=4 (Failed)
         26 - debug_device_tests (Not Run)
        146 - pmesh-fitting_np=4 (Failed)
        
I haven't looked into what the failures are yet, but the same tests are failing in debug or release mode and without UVM.

**Comment by v-dobrev** [comment]
The way to enable debug mode in the CMake build system is to set the build type to `Debug` instead of the default `Resease`, e.g. by adding the flag `-DCMAKE_BUILD_TYPE=Debug` to your `cmake` config command.

I suspect that most of the failures you saw are because you did not build the examples, miniapps, and tests -- note that with the CMake build system, `make all` will NOT build all examples, miniapps, and tests -- to do that you can use `make exec -j 16`, see here: https://github.com/mfem/mfem/blob/540c21c9e5674d6e50f743a614efcbe4b6ff66e1/INSTALL#L955-L967

**Comment by v-dobrev** [comment]
Another potential issue on Lassen could be that you need to tell CMake how to properly run parallel jobs, e.g. using `-DMFEM_MPIEXEC="lrun" -DMFEM_MPIEXEC_NP="-n"`.

**Comment by helloworld922** [comment]
I figured out why I was getting test failures. It's because CMake doesn't build the actual test executables unless you run `make tests`.

After building the tests, the only failure I get is
>         146 - pmesh-fitting_np=4 (Failed)

This fails because `miniapps/meshing/pmesh-fitting.cpp` explicitly terminates if `HYPRE_USING_GPU` is defined.

**Comment by helloworld922** [comment]
I commented out these lines and the test passes, so it might be ok to remove this now?

**Comment by v-dobrev** [comment]
> This fails because `miniapps/meshing/pmesh-fitting.cpp` terminates if `HYPRE_USING_GPU` is defined.

This is an oversight -- examples that return `MFEM_SKIP_RETURN_VALUE` (i.e. `242`) have to manually be skipped in the CMake build system. For example, here's how this is done for some examples under various conditions: https://github.com/mfem/mfem/blob/540c21c9e5674d6e50f743a614efcbe4b6ff66e1/examples/CMakeLists.txt#L95-L105

In the GNU make build system this is automatic: examples that return `MFEM_SKIP_RETURN_VALUE` are shown as `[ SKIP ]`.

**Comment by v-dobrev** [comment]
> I commented out these lines and the test passes, so it might be ok to remove this now?

I'm not sure `pmesh-fitting.cpp` actually works correctly with `HYPRE_USING_GPU`, even if it does not crash. @kmittal2 or @vladotomov will know better.

**Comment by helloworld922** [comment]
I tried HYPRE+UVM+CUDA and now I'm getting many test failures. It looks like they're failing with segfaults. I tried `mpirun -np 1 ./ex1p -pa -d cuda`, and it segfaults at `linalg/hypre_parcsr.cpp:1303`.

**Comment by helloworld922** [comment]
I tried with your latest commit, and I still get the same segfault when I try running `mpirun -np 1 ./ex1p -pa -d cuda` with HYPRE+UVM+CUDA

**Comment by helloworld922** [comment]
I figured out what was causing my segfaults, it was how I was building HYPRE. I managed to configure HYPRE with `HYPRE_USING_UNIFIED_MEMORY` and `HYPRE_USING_DEVICE_MEMORY` at the same time. I can submit patches to HYPRE which make doing this impossible.

After fixing this, with debug builds I still get a failure in `pcunit_tests`, specifically the `BatchedLOR_AMS` test. It looks like `HypreRead` and `HypreWrite` in `lor_ams.cpp:242-252` are checking that reads/writes are checking for the `MemoryClass` `GetHypreMemoryClass()` returns, however I think it's copying data from/to MFEM which uses `MemoryType::HOST`/`MemoryType::DEVICE` to something requiring `MemoryClass::MANAGED`, and failing (assert in `mem_manager.cpp:1059`).

I'm not entirely sure how to fix this. Why don't these checks for `MemoryClass::MANAGED` not allow any valid `h_mt` and `d_mt`?

**Comment by v-dobrev** [comment]
@helloworld922, the issue you see is related to this issue: #4351. I'm testing a fix for that and I'll push it when ready.

**Comment by helloworld922** [comment]
That fixes the issue, and now with HYPRE+UVM+CUDA all the tests pass in debug and release mode.

I tried on Tioga with the MI300 and HYPRE+HIP+UVM, and I ran into a few test failures.

On ex8p I get this error in both release and debug mode:
> Memory access fault by GPU node-4 (Agent handle: 0x5c31ba0) on address 0x1553340bb000. Reason: Unknown.
Core limit file reached. GPU core dump created: gpucore.262276
Aborted (core dumped)

This happens on calling `pcg.Mult` at `ex8p.cpp:279`. if I initialize a `Device` object with type `cpu` this problem goes away.

There is also an intermittent failure in `ex10p_np=4` which I don't understand. When I try to use the srun wrapper, it fails, but calling `flux run` directly succeeds.

Again, adding `Device device("cpu");` fixes this problem.

**Comment by v-dobrev** [comment]
@helloworld922, I was not able to reproduce the issues you mentioned with HYPRE+HIP+UVM builds.

**Review by v-dobrev — APPROVED** [review]

**Comment by helloworld922** [comment]
I suspect the problem might be something related to the Tioga system (or at least my setup) rather than mfem. I rebuilt everything and I can get tests to pass now, with occasional hiccups with flux refusing to run a test. @v-dobrev

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
