### PR TITLE
Replace the terminology between shared non-conforming slave and master

### PR DESCRIPTION
**Pull request by YohannDudouit**
This PR improves further the new `Mesh::FaceInformation` by associating `location` and `conformity` to both `elem1` and `elem2` for a given face, this should make the `Mesh::FaceInformation` even easier to process by a human.

This PR also proposes to replace the concepts of `slave` and `master` faces for two main reasons:
- These terms are politically loaded, especially in the US due to its history,
- This terminology is hard to grasp, indeed `slave` and `master` refer to **how** the faces are created in the code, therefore understanding **how** the code works is a prerequisite to understand the documentation (?!). Whereas replacing these concepts by `fine` and `coarse` describes **what** the faces are from a mathematical/geometrical perspective. Furthermore, `slave` and `master` are not sufficient to describe all the possible face configurations, and thus a third concept of `ghost` faces (also not trivial to grasp) is needed to resolve the ambiguity. However, when describing faces in term of `coarse` and `fine`, all the possible face configurations can be described (non-ambiguously) without requiring a third concept.

### CODE REVIEW

**Comment by YohannDudouit** [comment]
This PR should be reviewed after #2195 , or #2769 should be merged in #2195 .

**Comment by tzanio** [comment]
I'd like to edit this PR and start its review, and I generally agree that renaming `slave/master` to `fine/coarse` may be a good idea, but I am confused -- there are way to many changes here which look much more significant than renaming.

What am I missing?

Was this PR intended to be towards a different branch than `master` (maybe `yohann/pa-dg-ncmesh`)?

**Comment by tzanio** [comment]
I'd like to edit this PR and start its review, and I generally agree that renaming `slave/master` to `fine/coarse` may be a good idea, but I am confused -- there are way to many changes here which look much more significant than renaming.

What am I missing?

Was this PR intended to be towards a different branch than `master` (maybe `yohann/pa-dg-ncmesh`)?

**Comment by v-dobrev** [comment]
@tzanio, see the comment here: https://github.com/mfem/mfem/pull/2767#issuecomment-1013558033

Basically this PR is the same as #2769, however, its target is the `master` branch.

I prefer to merge #2769 into #2195 (after resolving the discussions there) and then that into `master`. So this PR can be closed.

**Comment by YohannDudouit** [comment]
> This PR should be reviewed after #2195 , or #2769 should be merged in #2195 .

@tzanio Yes, this was the reason for that comment.

**Comment by pazner** [comment]
Can this PR be closed in favor of #2769?

**Pull request closed without merging**
