### PR TITLE
Consistent c'tors for [Par][Mixed]BilinearForm/[Par]LinearForm [shared-integ-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
Adding constructors which copy integrators from existing objects of the same type.

Also, adding code to properly handle the copying of marker arrays for restricted integrators.

### CODE REVIEW

**Comment by tzanio** [comment]
I'm not clear on the use case for this. Wouldn't #564 be addressed better by a shallow copy of the coefficient?

**Comment by mlstowell** [comment]
I suppose which would be a better solution is debatable.  My understanding was that Kirill's goal was to provide a higher level of abstraction to define a weak formulation involving BilinearForms, LinearForms, boundary conditions, etc.. It would therefore be easier to copy a BilinearForm rather than copy each coefficient that BilinearForm might depend upon.

That being said, I chose to address the issue in this way because there was an inconsistency in MFEM's constructors for these weak form classes.  The BilinearForm class offered a constructor that would copy integrators from another BilinearForm object without taking ownership of them (I have no idea how long this has been around nor what use case it was intended for).  The MixedBilinearForm and LinearForm objects had no similar constructors.  This pull request was mainly intended to resolve this inconsistency.  This PR was prompted by issue #564 but I felt this inconsistency should be addressed regardless of how well it suits Kirill's particular use case.

**Comment by tzanio** [comment]
Thanks for the explanation @mlstowell.

**Comment by v-dobrev** [comment]
@mlstowell, @tzanio,

I merged this branch in `next` for testing, however before we merge the PR, it may be a good idea for you to take a look at the last commit I made.

**Comment by mlstowell** [comment]
Hi, @v-dobrev ,
I think these are all good changes, thank you!  I particularly like all of the new and improved comments.
Mark

**Pull request merged**
