### PR TITLE
Update SuperLU_DIST solver interface

### PR DESCRIPTION
**Pull request by sebastiangrimberg**
Updates and upgrades for SuperLU_DIST sparse direct solver interface:

- HYPRE_BIGINT and HYPRE_MIXEDINT support.
- `Operator::ArrayMult(const Array<const Vector *> &X, Array<Vector *> &Y)` overrides for MUMPS solver classes (depends on https://github.com/mfem/mfem/pull/3075).
- Enable 3D processor grid option for SuperLU_Dist >= 7.2.0.
- Reuse symbolic factorization/row permutation for repeated `SetOperator` calls.
- Fix `gridexit` call.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3083](https://github.com/mfem/mfem/pull/3083) | @sebastiangrimberg | @pazner | @jandrej + @pghysels + @acfisher + @psocratis | 2/6/23 | 6/19/23 | 6/21/23 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by pazner** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by sebastiangrimberg** [comment]
This should resolve https://github.com/mfem/mfem/issues/3463 also.

**Comment by v-dobrev** [comment]
@sebastiangrimberg, I see that you force-pushed this branch. Once review has started we ask people to NOT force-push to make it simpler for reviewers to follow changes in the PR -- see https://github.com/mfem/mfem/pull/3083#issuecomment-1419617056. Please try to follow this rule in the future.

**Comment by pazner** [comment]
It would be great to get some reviews on this. Does anyone have time to take a quick look (@pghysels, @acfisher, @jandrej, @psocratis)? Thanks

**Comment by acfisher** [comment]
I took a quick look and these changes look good.  Can we bring it up to date with master and have a look at the testing?  Are we testing with SuperLU these days?

**Comment by sebastiangrimberg** [comment]
Thanks @acfisher, I've merged `master`. In addition to the example `ex1p`, there are unit tests for direct solvers in `tests/unit/linalg/test_direct_solvers.cpp` which I've updated and used to test locally, though I'm not sure if any part of the CI runs these tests. It looks like the checks by GitHub actions does not but I'm not sure about the more extensive internal testing.

**Comment by pazner** [comment]
> I took a quick look and these changes look good. Can we bring it up to date with master and have a look at the testing? Are we testing with SuperLU these days?

Thanks for looking into this @acfisher. Does the testing described in https://github.com/mfem/mfem/pull/3083#issuecomment-1497624227 sound sufficient to you?

**Review by acfisher — APPROVED** [review]
Testing looks good.  I think this one is ready.  Sorry for the delays in reviewing this, proposal season has taken all of our time and we are finally on the other side of it.

**Comment by pazner** [comment]
@sebastiangrimberg, could you try this out with MFEM, hypre, and SuperLU_DIST all configured to use CUDA? We are seeing failures on our side. Thanks

**Comment by pazner** [comment]
@v-dobrev used the following Spack configuration (on [Lassen](https://hpc.llnl.gov/hardware/compute-platforms/lassen), so also V100):
```
$SPACK_ROOT/bin/spack dev-build -u build -j 128 --fresh --test=root mfem@develop+cuda+superlu-dist cuda_arch=70 ^hypre+cuda ^superlu-dist+cuda cuda_arch=70
```

and obtained unit test failures:

```
-------------------------------------------------------------------------------
Parallel Direct Solvers
-------------------------------------------------------------------------------
mfem/tests/unit/linalg/test_direct_solvers.cpp:162
...............................................................................

mfem/tests/unit/linalg/test_direct_solvers.cpp:258: FAILED:
  REQUIRE( Y.Norml2() < 1.e-12 )
with expansion:
  1104.30452877997 < 1e-12

===============================================================================
test cases:   7 |   6 passed | 1 failed
assertions: 258 | 257 passed | 1 failed
```

**Comment by sebastiangrimberg** [comment]
Hm, OK interesting. I'm building using CMake (all packages), using the automatically detected `sm_70` arch from `CMAKE_CUDA_ARCHITECTURES`. SuperLU_DIST uses its own internal BLAS (`-DTPL_ENABLE_INTERNAL_BLASLIB=ON`), so my MFEM CMake configure line looks like:

``` 
-DSuperLUDist_DIR=$SUPERLU_DIR \
-DSuperLUDist_REQUIRED_PACKAGES="ParMETIS;METIS;MPI;CUDAToolkit" \
-DSuperLUDist_REQUIRED_LIBRARIES="$SUPERLU_DIR/lib64/libblas.a" \
```

I realized I had built debug versions of all packages so let me try with optimization flags.

**Comment by sebastiangrimberg** [comment]
OK, I'm able to reproduce the failure in `"Parallel Direct Solvers"` when building with CUDA support using Spack. I'm not sure what is going on and why the CMake build works but Spack does not, and I'm also not sure why it would be tied to the changes in this PR.

One difference I noticed is the Spack build for Hypre has a dependency on CUDA < 12, while my CMake build was using CUDA 12. I'll keep digging on this...

**Comment by sebastiangrimberg** [comment]
Sorry, I'm an idiot and was running `punit_tests` and not `pcunit_tests` in my CMake build hence the confusion...first time debugging MFEM + CUDA, sorry for the mistakes and thanks for bearing with me @pazner.

Anyway, I think I fixed the issue. I had missed two spots where device/host memory were getting out of sync. All tests are passing on my end now. See [32f9c06](https://github.com/mfem/mfem/pull/3083/commits/32f9c069f7117821e0010e4f920202d052f5bccc).

**Comment by pazner** [comment]
Re-merged in `next` for testing...

**Comment by v-dobrev** [comment]
There's another issue we ran into in our nightly testing: when building with the Intel compiler (our tests use version 2021.6.0 but other version probably have the same problem), SuperLU_DIST does not use `malloc`/`calloc` and `free`, see https://github.com/xiaoyeli/superlu_dist/blob/v8.1.2/SRC/memory.c#L151-L159. This is a problem when constructing `SuperMatrix` using arrays allocated with `malloc`/`calloc` e.g. by hypre, see here https://github.com/mfem/mfem/blob/cad9a4126270d6058ce8cb25e0d202cd6b8852ba/linalg/superlu.cpp#L236-L239

In this case (SuperLU_DIST built with the Intel compiler), it seems best to allocate the arrays through SuperLU_DIST and copy the data. Unfortunately, I don't see a simple way to check what compiler was used to build SuperLU_DIST: one option is to assume that the same compiler is used to build MFEM, another is to always perform the array copies.

Another approach could be to somehow prevent `SuperLU_DIST` from deleting arrays it did not allocate and then we can handle the deletion in `SuperLURowLocMatrix`.

**Comment by sebastiangrimberg** [comment]
I wonder if the simplest approach, at the expense of an extra memory copy, is to just copy the Hypre allocated data into new arrays which are SuperLU_DIST allocated, as in the first `SuperLURowLocMatrix` constructor? This is what, for example, the STRUMPACK and MUMPS solvers do rather than taking ownership of the input pointers. This way we can always guarantee that the malloc/free done are done in a compatible way by SuperLU_DIST.

**Comment by v-dobrev** [comment]
> I would think the simplest approach you suggest is to just copy the Hypre allocated data into new arrays which are SuperLU_DIST allocated at the expense of an extra copy, as in the first `SuperLURowLocMatrix` constructor. This is what, for example, the STRUMPACK and MUMPS solvers do rather than taking ownership of the input pointers. This way we can always guarantee that the malloc/free done are done in a compatible way by SuperLU_DIST.
> 
> If you agree that this is acceptable I’ll go ahead and make that change.

Sounds reasonable to me. In terms of time overhead, I don't think this will be noticeable. In terms of memory overhead, it should be noticeable only in an extreme case where having the two copies in memory pushes the memory need beyond the available RAM -- I'm not sure this case of big practical concern.

**Comment by sebastiangrimberg** [comment]
Great, thanks @v-dobrev. Should be fixed in edcf6b4.

**Comment by pazner** [comment]
Re-merged in `next` for testing...

**Comment by v-dobrev** [comment]
Re-running failed jobs.

**Comment by v-dobrev** [comment]
Restarting again after fix in the gh-action.

**Pull request merged**
