### PR TITLE
CMake updates for XSDK support [xsdk-cmake-dev]

### PR DESCRIPTION
**Pull request by acfisher**

### CODE REVIEW

**Comment by acfisher** [comment]
https://figshare.com/articles/xSDK_Community_Installation_Policies_GNU_Autoconf_and_CMake_Options/4495133
### XSDK CMAKE options

- [ ] USE_XSDK_DEFAULTS=[YES,NO]
- [ ] CMAKE_INSTALL_PREFIX=directory
- [ ] CMAKE_BUILD_TYPE=[Debug,Release]
- [ ] BUILD_SHARED_LIBS=[YES,NO]
- [ ] XSDK_ENABLE_<language>=[YES,NO]
- [ ] XSDK_PRECISION=[SINGLE,DOUBLE,QUAD] (Can be ignored)
- [ ] XSDK_INDEX_SIZE=[32,64] (Can be ignored)
- [ ] TPL_BLAS_LIBRARIES=”linkable list of libraries”
- [ ] TPL_LAPACK_LIBRARIES=”linkable list of libraries”
- [ ] TPL_ENABLE_<package>=[YES,NO]
- [ ] TPL_<package>_INCLUDE_DIRS=”/path/to/includes1;/path/to/includes1;...”

**Comment by v-dobrev** [comment]
`CMAKE_BUILD_TYPE` is supported, as mentioned here:
https://github.com/mfem/mfem/blob/f85a06b157b1f1ff5c17d402e9a5c0052af62f2b/INSTALL#L503-L505

**Comment by v-dobrev** [comment]
`BUILD_SHARED_LIBS` is supported, as mentioned here:
https://github.com/mfem/mfem/blob/f85a06b157b1f1ff5c17d402e9a5c0052af62f2b/INSTALL#L513-L514

**Comment by v-dobrev** [comment]
`CMAKE_INSTALL_PREFIX` works too:
https://github.com/mfem/mfem/blob/f85a06b157b1f1ff5c17d402e9a5c0052af62f2b/INSTALL#L547-L548

**Comment by v-dobrev** [comment]
I think we handle `USE_XSDK_DEFAULTS` properly too - following the description in the file [XSDKDefaults.cmake](https://github.com/mfem/mfem/blob/master/config/XSDKDefaults.cmake) which is included from the main [CMakeLists.txt](https://github.com/mfem/mfem/blob/master/CMakeLists.txt) file.

**Comment by v-dobrev** [comment]
@acfisher , in the checkbox text `XSDK_ENABLE_=[YES,NO]`, do you mean `XSDK_ENABLE_<language>=[YES,NO]`? If that is the case, these options are also handled in [CMakeLists.txt](https://github.com/mfem/mfem/blob/master/CMakeLists.txt) as described in [XSDKDefaults.cmake](https://github.com/mfem/mfem/blob/master/config/XSDKDefaults.cmake), see here:

https://github.com/mfem/mfem/blob/f85a06b157b1f1ff5c17d402e9a5c0052af62f2b/CMakeLists.txt#L56-L89

**Comment by acfisher** [comment]
@v-dobrev   THanks for looking into where we are at here.  You are correct on the XSDK_ENABLE_<language> tag.  That is what I was referring to.

**Comment by v-dobrev** [comment]
OK, I checked the item on the list.

**Comment by tzanio** [comment]
@acfisher can we revive this branch? May be good to complete before ATPESC?

**Comment by tzanio** [comment]
If I understand correctly, we are compatible with everything except potentially the `TPL_` variables.

As @v-dobrev pointed out in https://github.com/xsdk-project/xsdk-issues/issues/15#issuecomment-326473169, MFEM has equivalent variables but with slightly different names.

@acfisher -- can you check if we need to support these exact variables (`TPL_BLAS_LIBRARIES`, etc.) or just the functionality?

**Comment by tzanio** [comment]
If we _have to_ support the exact names, we can either support both options, or maybe consider renaming the current MFEM variables (though I would prefer to avoid that)

**Comment by acfisher** [comment]
I just took a look and we don't handle the TPL_*_LIBRARIES variables, the TPL_ENABLE_* variables, or the TPL_INCLUDE_DIRS.  We have internal MFEM variables that correspond, so perhaps we can ALIAS them?

**Comment by acfisher** [comment]
It looks like #445 just had the list of stuff we were working on at the time and no actual changes.  We can delete it.

**Comment by acfisher** [comment]
Issue addressed in a newer pull request.

**Pull request closed without merging**
