### PR TITLE
Bug fix in FindPointsGSLIB::Interpolate when using L2_FECollection in parallel

### PR DESCRIPTION
**Pull request by trevilo**
This is intended to fix a problem observed when using the gslib-based interpolator (`FindPointsGSLIB::Interpolate`) with `L2_FECollection` in parallel.

Specifically, with the existing code, it is possible for a call to `FindPointsGSLIB::Interpolate` to hang indefinitely.  This happens when using `L2_FECollection` and some MPI tasks find border points while others do not.  In this case, the tasks that do not find border points exit `FindPointsGSLIB::Interpolate` "early"---i.e., before the subsequent call to either `InterpolateH1` or `InterpolateGeneral`.  These calls though have communication calls, which leads to the hang.

The changes in 7859c93 are intended to expose this behavior using the `pfindpts` miniapp, by allowing the user to force different MPI tasks to search for different points.  In particular, it is sufficient to have only task 0 own any points to search for, while the other tasks have none.  This is implemented with the option `--search-on-r0`, which defaults to false such that the default behavior reproduces the current behavior where all MPI tasks have the same points.  If this option is used with `L2_FECollection`, i.e., `-ft 1`, in parallel, the miniapp will hang without the modification in 9148a1d.

The changes in 9148a1d are intended to fix this problem, simply by checking that no process found border points before the return in `FindPointsGSLIB::Interpolate`.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2422](https://github.com/mfem/mfem/pull/2422) | @trevilo | @tzanio | @kmittal2 + @vladotomov | 07/22/21 | 08/03/21 | 08/05/21 | |

### CODE REVIEW

**Comment by vladotomov** [comment]
@trevilo is this ready to review and merge or are you planning more changes?

**Comment by trevilo** [comment]
> @trevilo is this ready to review and merge or are you planning more changes?

Yes, it is ready to review as far as I'm concerned.  Thanks.

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by vladotomov — APPROVED** [review]
Looks good, thanks for the fix @trevilo!

@tzanio this branch is in a fork, maybe this is why some of the checks are not executing?

**Comment by tzanio** [comment]
@kmittal2, the review for this PR is dues soon -- can you take a look?

**Review by kmittal2 — APPROVED** [review]
Glad you caught this error @trevilo.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
