### PR TITLE
Bug-fix: Adding appropriate doftransformations for high-order ND tet elements in RefineOperator/PRefineOperator Mult and MultTranspose

### PR DESCRIPTION
**Pull request by psocratis**
Small bug-fix to the `RefineOperator::MultTranspose()`. Vector size was not set for the case where `doftrans != NULL`

Update: In the process of testing this some additional bugs were discovered related to the use dof transformations of the high-order tet ND elements in the Mult/MultTranspose methods of `RefineOperator` and `PRefineOperator`.

I believe this should fix the issues. I added a small test file in the examples directory for the reviewers which I intend to remove after the review. @sshiraiwa, Please let me know if this works for you. @mlstowell thanks for your help. 

Note: There is still an unrelated issue in the PRefinementOperator for TensorProductElements which I am investigating but I will try to address that in another PR.  

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2668](https://github.com/mfem/mfem/pull/2668) | @psocratis | @tzanio | @tzanio + @mlstowell | 11/23/21 | 11/30/21 | 12/05/21 | |

### CODE REVIEW

**Review by mlstowell — APPROVED** [review]
Thanks for tracking this down, @psocratis.

**Comment by sshiraiwa** [comment]
Thank you.

Yes, with this PR,
```
  TransferOperator *P2 = new TransferOperator(*fes1, fes2);
  P2 -> Mult(x1, x2);
  P2 -> MultTranspose(x2, x1);
```
where fes1 and fes2 are ND and x1 x2  are GridFunction on fes1 and fes2 goes through w/o crash.
Here is the comparison of forward and backward transfer for order=1 and order=3.

image

**Comment by psocratis** [comment]
@sshiraiwa, when you transfer back from fine grid to coarse grid it makes more sense to transfer dual vectors (loads). 
See `./examples/testNDtet_trasfer.cpp` in this PR that uses the mass matrix to map between primal and dual space. This is how it looks like

image
image

**Comment by sshiraiwa** [comment]
Yes, that was what I was missing. Thank you!

**Review by sshiraiwa — APPROVED** [review]

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
