### PR TITLE
Boundary attribute transfer to ParSubMesh

### PR DESCRIPTION
**Pull request by mlstowell**
Interior boundary elements of ParMesh objects which happen to align with processor boundaries only exist on one of the two processes which share the corresponding edge/face. This helps to avoid processing these boundary elements twice in various scenarios.

This leads to a problem when using such a mesh to create a ParSubMesh object based on a sub-domain. Boundary attributes are transferred to sub-mesh objects to facilitate problem setup on sub-domains. However, if the boundary of a sub-domain is defined as an interior boundary of the full domain and this boundary happens to align with a processor boundary, the interior boundary elements may not exist on the local processor so the sub-mesh object will not recognize these elements as members of a labeled boundary. This leads to a situation where the boundary of a sub-domain will contain some boundary attributes from the interior boundary of the original mesh and some new attribute numbers for the unrecognized members of this boundary.

To resolve this we need some mechanism for communicating boundary attribute numbers from the original mesh to all portions of the partitioned sub-mesh which touch those boundaries. The approach used in this PR is not the most efficient in terms of memory usage or CPU time but it was efficient in terms of developer time. The idea was to create a lowest order Raviart-Thomas field (which has 1 DoF per face) on the full mesh and copy the boundary attribute numbers into these face DoFs. Then use a transfer map to transfer these field values a.k.a. boundary attribute numbers to the newly created ParSubMesh object.

This PR also adds a unit test designed to confirm the successful marking of the boundaries of a ParSubMesh object. Also added are two new variants of the multidomain miniapp based on Nedelec and Raviart-Thomas basis functions which helped to identify the root cause of some unexpected behavior observed in a similar application.

This PR is related to issues #4011 and #4145 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4113](https://github.com/mfem/mfem/pull/4113) | @mlstowell | @tzanio | @jandrej + @psocratis | 3/14/24 | 4/3/24 | 4/5/24 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by mlstowell** [comment]
I believe I have tracked the problem to how we generate interior boundary elements when partitioning a mesh. It seems that interior boundary elements which happen to lie on a processor interface are only generated on one of the two processors touching that face. See
https://github.com/mfem/mfem/blob/970833e98ccaf71d3f86522bcdd826d911e33156/mesh/pmesh.cpp#L427-#L437

We could simply create boundary elements on both processors but this may have other side effects. I'd be very interested to hear from @v-dobrev, @tzanio, and others. Do people foresee problems with this simple approach?

**Comment by mlstowell** [comment]
The reason this came up in the `ParSubMesh` context is that when an interior boundary is also a boundary of a `ParSubMesh` the boundary elements along processor boundaries will sometimes not appear in the `ParSubMesh` with the same boundary attribute that they had in the parent mesh. Any interior boundary elements that get dropped will appear in the `ParSubMesh` as newly identified boundary elements with no association to the original interior boundary and therefore they are given a new attribute number.

**Comment by jandrej** [comment]
> I believe I have tracked the problem to how we generate interior boundary elements when partitioning a mesh. It seems that interior boundary elements which happen to lie on a processor interface are only generated on one of the two processors touching that face. See https://github.com/mfem/mfem/blob/970833e98ccaf71d3f86522bcdd826d911e33156/mesh/pmesh.cpp#L427-#L437
> 
> We could simply create boundary elements on both processors but this may have other side effects. I'd be very interested to hear from @v-dobrev, @tzanio, and others. Do people foresee problems with this simple approach?

I think in certain routines this would double the contribution of boundary elements (e.g. when we use averaging). So this will be a very complicated endeavor. I haven't tested that though.

**Comment by hughcars** [comment]
When you say "boundary elements along processor boundaries will sometimes not appear in the `ParSubMesh`" are these coincident to processor boundaries? The duplication would also double any linear functionals calculated on the interfaces, without some mechanism for skipping a face based on ownership.

This gets pretty close to the issue I was encountering with interior boundaries for NCMesh when all child elements on a face were owned by the opposing rank. The rough solution I went with was to allow accessing parents via children for accessing information see https://github.com/mfem/mfem/blob/master/mesh/ncmesh.cpp#L2493, https://github.com/mfem/mfem/blob/master/fem/fespace.cpp#L544 and https://github.com/mfem/mfem/blob/master/mesh/ncmesh.cpp#L5294. I wonder if a similar approach can be taken in reverse, where a "parent" face in the ParMesh is given means of pushing attributes directly to any child "ghosts". The children would be responsible for interrogating parents for attributes at that stage.  The interior boundary element coincident to a process boundary would need a mechanism to inform in either direction I suspect.

**Comment by sebastiangrimberg** [comment]
> I think in certain routines this would double the contribution of boundary elements (e.g. when we use averaging). So this will be a very complicated endeavor. I haven't tested that though.

Second this. This is an assumption made throughout the code (and by application codes). Any integration, integral BCs, etc. on interior boundaries would need to be revisited in parallel.

**Comment by mlstowell** [comment]
> When you say "boundary elements along processor boundaries will sometimes not appear in the `ParSubMesh`" are these coincident to processor boundaries? 
> 
Yes, the dropped interior boundary elements will always be coincident with processor boundaries.

**Comment by mlstowell** [comment]
I agree with everyone that duplication of integrals on interior boundaries is likely.

Perhaps the simplest solution is to create an array of "ghost" boundary elements probably similar to what @hughcars was suggesting. These could be processed in the same manner as standard boundary elements for mesh related functions such as refinement but skipped during integration loops and such.

The only alternative that I see would be to add the "ghost" boundary elements to the same data structures that currently hold other boundary elements but somehow mark them as "ghost" so that we can skip them in certain contexts. Of course this would probably require many existing codes to be modified to check for this "ghost" characteristic.

The primary (and perhaps only) purpose of these ghost boundary elements would be to store an attribute number. I don't believe any parallel communication would be required to keep these ghost boundary elements up to date with changes to the mesh because each ghost boundary element would necessarily correspond to exactly one local face and it should be sufficient to remain consistent with that local face.

I propose adding data structures and related accessor methods to maintain a list of ghost boundary elements in the `Mesh` object. The `Mesh` object can then maintain these data structures in precisely the same manner as the existing boundary elements. Applications can then add code to loop over these ghost boundary elements when necessary but ignore them otherwise. 

@hughcars, @sebastiangrimberg, @jandrej, @v-dobrev: Does this sound like a reasonable solution?

**Comment by sebastiangrimberg** [comment]
If I understand correctly, I agree with this proposal. I suggest:
2. That there should be no duplication introduced in the `Mesh::boundary` array so fundamentally no behavior downstream changes.
2. (Related to 1) The list of ghost boundary elements be added to `ParMesh`, not `Mesh`, as they are not needed in the serial case. Then the `ParSubMesh` constructor can pull from those ghost elements as needed.

**Comment by jandrej** [comment]
> If I understand correctly, I agree with this proposal. I suggest: 2. That there should be no duplication introduced in the `Mesh::boundary` array so fundamentally no behavior downstream changes. 2. (Related to 1) The list of ghost boundary elements be added to `ParMesh`, not `Mesh`, as they are not needed in the serial case. Then the `ParSubMesh` constructor can pull from those ghost elements as needed.

This would probably remove the communication necessity and averaging from `CommunicateSharedVdofs` in `ParSubMesh` as well right?

**Comment by jandrej** [comment]
Resolves https://github.com/mfem/mfem/issues/4145

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by psocratis — APPROVED** [review]
Looks very good! Just a couple of small things @mlstowell . One is to add the new miniapps to the makefile and their outputs to the `make clean` command. The second is a small suggestion to fix the data range of the colormap for both the submeshes to be the same, something like `<< "autoscale off\n" << "valuerange 0 1\n"`. This way you can check visually that the functions match on the common interface.

**Comment by tzanio** [comment]
Now that PR https://github.com/mfem/mfem/pull/3922 has been merged in `master`, please update this PR by:

1. merging `master` in here and resolving conflicts
2. replacing use of `double` with `real_t`
3. guarding double/single-only sections with `MFEM_USE_DOUBLE` and `MFEM_USE_SINGLE`
4. making sure tests run cleanly with default and `MFEM_PRECISION=single` configurations

See https://github.com/orgs/mfem/discussions/4207 for more details and/or ask @dylan-copeland for help.

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by mlstowell** [comment]
Just conformed that all tests pass when running `make test` with `MFEM_USE_SINGLE`.

**Comment by tzanio** [comment]
Re-merged in `next` for testing...

**Comment by tzanio** [comment]
The latest commit [breaks the code](https://github.com/mfem/mfem/actions/runs/8473876501/job/23219131254?pr=4113#step:18:818) (`visualization` has to be passed to `ComputeCurrentDensityOnSubMesh`)

@mlstowell -- can you take a look and fix it?

**Comment by tzanio** [comment]
Re-merged in `next` for testing...

**Comment by tzanio** [comment]
Re-merged in `next` for testing...

**Pull request merged**
