### PR TITLE
Fixed GeometryRefiner::RefineInterior() to not cause invalid deallocations

### PR DESCRIPTION
**Pull request by najlkin**
Method `GeometryRefiner::RefineInterior()` was appending integration rules to its internal array even when the rule was existing. This caused consequent invalid deallocations in the destructor and unclean exits / crashes. For example GLVis was affected, when the element refinement was increased and arrows for a vector field were visualized (that is how I noticed that, where instead of normal exit it just threw nice "free(): invalid pointer Aborted (core dumped)" :smile: )

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1503](https://github.com/mfem/mfem/pull/1503) | @najlkin | @v-dobrev | @kmittal2 + @rw-anderson | 06/19/20 | 07/07/20 | 07/15/20 | |

### CODE REVIEW

**Comment by najlkin** [comment]
Could someone rerun that Travis CI, it just failed to download hypre.

**Comment by v-dobrev** [comment]
@najlkin, thanks for tracking down and fixing the bug. Is this ready for review? If so, please add the label `ready-for-review`.

**Comment by najlkin** [comment]
@v-dobrev it is ready for review (the changes are minimal), but I do not have permissions to add labels as a mere member of mfem/users. That is also the reason why I am making the pull request from my fork again.

**Comment by tzanio** [comment]
@najlkin you are a member of mfem/collaborators now :)

**Comment by najlkin** [comment]
Thanks @tzanio ! :sparkles:

**Comment by rw-anderson** [comment]
Is the conditional check on the Append() still necessary after the other modifications?  Seems like all cases in the switch either return ir immediately (if non-null) or allocates one.  If the switch reaches the default case, it is an error.

It does not do harm, but seems to imply a null state is an expected condition there, and implies that returning null is an expected return value.

if (ir) { IntPts[Geom].Append(ir); }

**Comment by najlkin** [comment]
Yes, I agree. It is rather internal double check, so an assert suits better.

**Comment by v-dobrev** [comment]
Merged in `next` for testing...

**Pull request merged**
