### PR TITLE
Adding more sample runs to ex20 and ex20p [ex20-sample-runs-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
These new sample runs were chosen to demonstrate the drop in energy fluctuations when higher order symplectic methods are used.

Interestingly the 4th order method does not perform better than the 3rd order method for most of the sample Hamiltonians in the range of time steps that I tested. It does show good convergence on its own so choosing a smaller time step may produce better results but I didn't want the sample runs to take too long.

This PR depends on PR #2288 which should be merged first

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2293](https://github.com/mfem/mfem/pull/2293) | @mlstowell | @tzanio | @tzanio + @cjvogl | 06/07/21 | 06/08/21 | 06/09/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
LGTM

**Review by HennesHajduk — APPROVED** [review]

**Review by tzanio — APPROVED** [review]
Thanks @mlstowell !

**Review by cjvogl — APPROVED** [review]

**Comment by tzanio** [comment]
Can you check if the new Example 20/20p results in [tonight's test on tux426](https://mybitbucket.llnl.gov/projects/MFEM/repos/autotest/browse/tux426/2021-06-09-llnl-gh-next/sample-runs-baseline-tux426.diff) look OK?

**Comment by mlstowell** [comment]
> Can you check if the new Example 20/20p results in [tonight's test on tux426](https://mybitbucket.llnl.gov/projects/MFEM/repos/autotest/browse/tux426/2021-06-09-llnl-gh-next/sample-runs-baseline-tux426.diff) look OK?

The results match those from my machine and I think they look reasonable.

**Pull request merged**
