### PR TITLE
Potential bug in DG Element assembly? 

### PR DESCRIPTION
**Pull request by artv3**
Hi all, 

I believe I may have run into a bug with the element assembly option in MFEM. 
I made a small reproducer with ex9p. 

Running 
`./ex9p -m ../data/periodic-square.mesh -pa`
vs 
`./ex9p -m ../data/periodic-square.mesh -ea`

leads to different answers, with element assembly I get NaNs.

### CODE REVIEW

**Comment by YohannDudouit** [comment]
I think this indeed is a bug, but maybe not what you think, EA assumes that there is at least one `Integrator`, in your code there is none, resulting in the element matrices being uninitialized, to which are added the face integrator values... I can change the behavior of the code when EA is called without any integrators and only face integrators.

**Comment by YohannDudouit** [comment]
A temporary fix in `fem/bilinearform_ext.cpp:517` can be:
```c++
   if ( integratorCount == 0 )
   {
      ea_data = 0.0;
   }
```

The output:
``` ~/Projects/mfem/examples/> ./ex9p -m ../data/periodic-square.mesh -pa
Options used:
   --mesh ../data/periodic-square.mesh
   --problem 0
   --refine-serial 0
   --refine-parallel 0
   --order 3
   --partial-assembly
   --no-element-assembly
   --no-full-assembly
   --device cpu
   --ode-solver 4
   --t-final 10
   --time-step 0.01
   --prec-type 0
   --visualization
   --no-visit-datafiles
   --no-paraview-datafiles
   --no-adios2-streams
   --ascii-datafiles
   --visualization-steps 5
Device configuration: cpu
Memory configuration: host-std
Number of unknowns: 144
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
Solution vector norm 0
 ~/Projects/mfem/examples/> ./ex9p -m ../data/periodic-square.mesh -ea
Options used:
   --mesh ../data/periodic-square.mesh
   --problem 0
   --refine-serial 0
   --refine-parallel 0
   --order 3
   --no-partial-assembly
   --element-assembly
   --no-full-assembly
   --device cpu
   --ode-solver 4
   --t-final 10
   --time-step 0.01
   --prec-type 0
   --visualization
   --no-visit-datafiles
   --no-paraview-datafiles
   --no-adios2-streams
   --ascii-datafiles
   --visualization-steps 5
Device configuration: cpu
Memory configuration: host-std
Number of unknowns: 144
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
Solution vector norm 0
```

**Comment by artv3** [comment]
Thanks for looking into this @YohannDudouit . Yes, if we could get the consistent behavior that would be great.

**Comment by pazner** [comment]
I believe this is fixed by #2803. @artv3, please re-open if I'm mistaken.

**Pull request closed without merging**
