### PR TITLE
 Application fixes [gpu/appfixes]

### PR DESCRIPTION
**Pull request by artv3**
In exercising MFEM 4.0 we found that we needed to add a couple of lines of code to start getting our application to work. 

| PR | Author | Editor | Reviewers  | Assignment | Approval | Merge |
| --- | --- | --- | ---  | --- | --- | --- |
| https://github.com/mfem/mfem/pull/937 | @artv3 | @tzanio | @v-dobrev + @camierjs | 11/23/19 | 12/09/19 | ⌛due 12/16/19 |

### CODE REVIEW

**Comment by artv3** [comment]
Folks, we have a conflict here, should I just take what is in master?

``` 
<<<<<<< gpu/appfixes
         // 'Transformation' is not used
         nodes.GetVectorValues(Transformation, eir, pm);
=======
         Nodes->GetVectorValues(FaceElemTr.Loc1.Transf, eir, pm);
>>>>>>> master
```

**Comment by mlstowell** [comment]
If this conflict is in `mesh.cpp` then you should use what's in master.  If this is the line I think it is, it is a bugfix from  PR #1003.

**Comment by artv3** [comment]
Thanks @mlstowell!

**Comment by artv3** [comment]
How are we looking team?

**Comment by v-dobrev** [comment]
Note: the branch https://github.com/mfem/mfem/tree/axom-dev is merged here, so it should be safe to delete it.

**Comment by tzanio** [comment]
Reminder: the reviews for this PR are due this week

cc: @v-dobrev, @camierjs

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
