### PR TITLE
Fix a bug in Diffusion Element Assembly in 3D.

### PR DESCRIPTION
**Pull request by YohannDudouit**
Thanks to @nbeams for finding a bug in the `DiffusionIntegrator` Element Assembly in 3D, it also impacts Full Assembly. This PR fixes the bug.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1660](https://github.com/mfem/mfem/pull/1660) | @YohannDudouit | @tzanio | @camierjs + @artv3 + @barker29 | 08/01/20 | 08/04/20 | 08/13/20 | |

### CODE REVIEW

**Comment by YohannDudouit** [comment]
@artv3 @camierjs This is tested in `test_assembly_levels.cpp`, I'm investigating why the unit tests passed when there was a bug.

**Comment by YohannDudouit** [comment]
@artv3 This technique of testing only work without boundary conditions.

**Comment by YohannDudouit** [comment]
@camierjs @artv3 I fixed `test_assembly_levels.cpp`, I was using nested `SECTION` in `for` loops which resulted in only the first test of the `for` loop to be ran.

**Comment by tzanio** [comment]
> @camierjs @artv3 I fixed test_assembly_levels.cpp, I was using nested SECTION in for loops which resulted in only the first test of the for loop to be ran.

Good detective work, @YohannDudouit. Can you please check also that this is not a problem in other unit tests?

**Comment by YohannDudouit** [comment]
@tzanio Most tests are okay, `test_pakernels.cpp` has the same issue, I'll modify it in this PR.

I should mention it can be okay to use `SECTION` inside `for` loops, if the `SECTION` names are unique:
```c++
   for (int i; ...)
   {
      SECTION("mySection" + std::to_string(i))
      {
         ...
      }
   }
```
more details here: https://github.com/catchorg/Catch2/issues/993

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
