### PR TITLE
[DISCUSS] Space-time mesh generator in 3D/4D. [mfem_4d_meshgen]

### PR DESCRIPTION
**Pull request by kvoronin**
Added to 4d_dev:
1) parallel mesh generator which extends a 2D/3D (triangular/tetrahedral) mesh into a space-time 3D/4D mesh for given time step and number of time slabs;
2) visualization through mesh slices: 3D or 4D mesh is sliced by hyperplanes t=const and the output slice mesh (or grid function) is printed in VTK format (can be directly used by ParaView);
3) several 2D/3D meshes (square for 2D, cube and sphere ~ ball in 3D - for testing mesh generator).
Qhull software is an option which can be used or not used for mesh generator, so slight modifications to makefile and defaults.mk were made (a configuration flag MFEM_WITH_QHULL and variables QHULL_DIR, QHULL_OPT, QHULL_LIB);
4) a new example ParMeshGenViz4D.cpp.

### CODE REVIEW

**Comment by tzanio** [comment]
Travis regression testing above is failing, see https://travis-ci.org/mfem/mfem/builds/225415199

**Comment by kvoronin** [comment]
1) Sorry, I forgot to "git add" the latest defaults.mk (as well as example and mesh files). What is the right way to add them and carry out the testing again? I just commited the cnages and pushed them to the branch. Is the pull request still active?
2) Is the testing environment always taking hypre and metis from default mfem paths aka @MFEM_DIR@/../ ? So should I have these paths in  defaults.mk or can I set them externally for tests (like an argument for make)?

**Comment by tzanio** [comment]
Pull request is still active. Testing runs automatically on push.

**Comment by tzanio** [comment]
Hi Kirill,

This is PR is at 50K additions now which is too much to be put in the library :)

Do you mind removing the meshes and the `github_mfem_4d.*` files from it?

Also, it goes without saying that we should consider and merge the 4d_dev branch first, for which currently there is no pull request.

Cheers,
Tzanio

**Comment by v-dobrev** [comment]
@tzanio, note that this is a PR into `4d_dev`.

**Comment by kvoronin** [comment]
@tzanio, I don't mind about removing anything (github_mfem_4d.* are actually trash files from qt creator project, I apologize for that), and since it is about 4d stuff, I think it only makes sense as a PR for 4d_dev.

**Comment by tzanio** [comment]
Something got messed up, I'll close this PR.

@kvoronin, I feel that this still needs more work to be really friendly to new users.

**Pull request closed without merging**
