### PR TITLE
Fix a few issues with the shared entity communicators in ParMesh

### PR DESCRIPTION
**Pull request by v-dobrev**
I think these sneaked in via the Submesh PR #2920.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3642](https://github.com/mfem/mfem/pull/3642) | @v-dobrev | @mlstowell | @jandrej + @mlstowell | 5/9/23 | 9/25/23 | ⌛due 5/30/23 | |

### CODE REVIEW

**Comment by mlstowell** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by sebastiangrimberg** [comment]
I can confirm that this is definitely a bug and #2920 introduced these regressions on previous behavior. In an effort to get a fix into `master`, see #3843  for an alternative implementation which is a bit lighter (fewer changes) and thus hopefully leads to faster review. I'm fine if you prefer this PR, but either way I'd love for one of these fixes to get merged ASAP!

**Comment by mlstowell** [comment]
@v-dobrev, there is an alternate PR #3843 which may include some of the changes in this PR. Could you please take a look at that one and let us know your thoughts?

**Comment by v-dobrev** [comment]
> @v-dobrev, there is an alternate PR #3843 which may include some of the changes in this PR. Could you please take a look at that one and let us know your thoughts?

See https://github.com/mfem/mfem/pull/3843#issuecomment-1698551485.

**Review by mlstowell — APPROVED** [review]

**Review by tzanio — APPROVED** [review]

**Comment by sebastiangrimberg** [comment]
I'm still not 100% sure, but believe the concern in the comment in this alternate PR still stands: https://github.com/mfem/mfem/pull/3843#issuecomment-1699346267. Either way right or wrong I'm curious just to know what the correct interpretation is for better understanding of the code.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by v-dobrev** [comment]
I finally had some time to look carefully at this PR and the alternative, #3843 suggested by @sebastiangrimberg, and I think we want to go with the latter, see https://github.com/mfem/mfem/pull/3843#issuecomment-1734825231.

@tzanio, @mlstowell, if you agree, we can revert the merge in `next` of this and merge the other in `next` for testing.

**Comment by jandrej** [comment]
> I finally had some time to look carefully at this PR and the alternative, #3843 suggested by @sebastiangrimberg, and I think we want to go with the latter, see [#3843 (comment)](https://github.com/mfem/mfem/pull/3843#issuecomment-1734825231).
> 
> @tzanio, @mlstowell, if you agree, we can revert the merge in `next` of this and merge the other in `next` for testing.

Agree. Not approving in favor of #3843

**Comment by tzanio** [comment]
> if you agree, we can revert the merge in next of this and merge the other in next for testing.

OK, lets do that.

@sebastiangrimberg, sorry for the confusion

**Comment by sebastiangrimberg** [comment]
> @sebastiangrimberg, sorry for the confusion

No problem!! Happy this will soon be resolved in `master`.

**Pull request closed without merging**
