### PR TITLE
DiffusionIntegrator using MatrixCoefficient on 2D surface in 3D mesh 

### PR DESCRIPTION
**Pull request by sshiraiwa**
This is to address an issue reported in https://github.com/mfem/mfem/issues/2111.
When a mesh is 2D defined in 3D space, diffusion coefficient in matrix form is supposed to be spaceDim x spaceDim.
However, dshape, to which grad v * c is stored, has a shape of nd x dim (not nd x spaceDim).  With MFEM_DEBUG flag, the size
mismatch is captured. Without the flag, the data is partially lost and it produces a strange result. Figure below compares  the result of solving div-grad-phi = 1 with essential BCs when an identity matrix is used for coefficient (left: before fix and right: after fix). If the coefficient is scalar one, the result is the same as the right one, as it is expected.

image

### CODE REVIEW

**Comment by v-dobrev** [comment]
Hi @sshiraiwa, sorry about this problem and thank you for the fix.

We never updated `DiffusionIntegrator` properly for matrix coefficients on surfaces -- we added support for scalar coefficients and ignored the other cases.

It looks like other methods in `DiffusionIntegrator` need to be fixed too, e.g. `AssembleElementVector`, `ComputeElementFlux`. Also, it looks like some of the methods do not support diagonal coefficients properly.

**Comment by tzanio** [comment]
Thank you @sshiraiwa. When this is ready, can you please label it `ready-for-review`?

**Comment by mlstowell** [comment]
I added a simple unit test based on example 1 but with a matrix coefficient and a fixed mesh. If anyone wants to see what the unit test is computing you can compile and run `examples/test_surf_diff.cpp` which is the same thing except that it has command line options. We can turn this into a proper example if that would be useful or we can just remove this file from the examples directory before merging this PR.

**Comment by sshiraiwa** [comment]
My fault...I added bunch of wrong files which are not supposed to be added here.
Trying to fix them....

**Comment by tzanio** [comment]
Superseded by https://github.com/mfem/mfem/pull/2137

**Pull request closed without merging**
