### PR TITLE
Extended copyright to 2022

### PR DESCRIPTION
**Pull request by tzanio**
Copyright (c) 2010-2021 -> Copyright (c) 2010-2022

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2855](https://github.com/mfem/mfem/pull/2855) | @tzanio | @tzanio | @camierjs + @acfisher | 2/25/22 | 2/28/22 | 3/1/22 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
The `branch-history` can be ignored for this PR.

**Comment by adrienbernede** [comment]
@tzanio I think you’ll need to update the copyright check in config/githooks/pre-push.

**Comment by tzanio** [comment]
It is updated :)

**Comment by adrienbernede** [comment]
lol, it is indeed... my bad 😅

**Review by adrienbernede — APPROVED** [review]
All good!

**Review by camierjs — APPROVED** [review]

**Review by acfisher — APPROVED** [review]
I grepped around for 2021 just to be sure and it looks like you go them all.

**Comment by tzanio** [comment]
thanks @acfisher

**Pull request merged**
