### PR TITLE
Fix MinGW compilation errors

### LINKED ISSUE #2494: Compiling with MINGW (Windows)
I tested building MFEM with MINGW (msys2 on Windows 10)
```
Christian@CHRISTIAN-PC MINGW64 ~/mfem/build
$ cmake -G "MinGW Makefiles" ../
$ cmake --build .
```
There are two errors:
```
isockstream.cpp:26:13: error: conflicting declaration 'typedef int ssize_t'
socketstream.cpp:31:13: error: conflicting declaration 'typedef int ssize_t'
```
I think the `typedef` should be enabled only for VC compiler, so a possible fix could be to use
```c
#ifdef _MSC_VER
typedef int ssize_t;
#endif
```
in both files. That fixes the error for me and compiling with Visual Studio 2019 still works fine.

### PR DESCRIPTION
**Pull request by wo80**
This PR fixes some issues with MinGW compilation. Tested with Visual Studio 2019 and GCC 10.3 on Windows 10 x64.

Closes #2494

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2497](https://github.com/mfem/mfem/pull/2497) | @wo80 | @tzanio | @pazner + @acfisher | 08/30/21 | 09/02/21 | 09/05/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by pazner** [comment]
@wo80, can you see if the changes on [this branch](https://github.com/mfem/mfem/tree/paraview-restart-fix) fix the ParaView unit tests?

**Comment by wo80** [comment]
@pazner MinGW still fails the test, but with a different error message:
```
-------------------------------------------------------------------------------
ParaView restart mode
-------------------------------------------------------------------------------
E:\data\Projekte\mfem\mfem\tests\unit\fem\test_datacollection.cpp:247
...............................................................................

E:\data\Projekte\mfem\mfem\tests\unit\fem\test_datacollection.cpp:289: FAILED:
  REQUIRE( t == MFEM_Approx(t_ref) )
with expansion:
  2 == Approx( 1.5 )
```
The line endings in `ParaView.pvd` are now mixed `CR+LF` (7 lines) and `CR` (3 times), which is an improvement, since the XML formatting issue is fixed. So now the content gets read successfully, but the content is wrong (should be 3 datasets only):
```xml
<?xml version="1.0"?>
<VTKFile type="Collection" version="0.1" byte_order="LittleEndian">
<Collection>
<DataSet timestep="0" group="" part="0" file="Cycle000000/data.pvtu"/>
<DataSet timestep="1" group="" part="0" file="Cycle000001/data.pvtu"/>
<DataSet timestep="2" group="" part="0" file="Cycle000002/data.pvtu"/>
<DataSet timestep="1" group="" part="0" file="Cycle000001/data.pvtu"/>
<DataSet timestep="1.5" group="" part="0" file="Cycle000002/data.pvtu"/>
</Collection>
</VTKFile>
```
Visual Studio still passes all tests and `ParaView.pvd` has correct line endings `CR+LF`.

**Comment by pazner** [comment]
> **EDIT**: the first three `DataSet` xml elements have the single `CR` line ending, so when entering restart mode, this gets read by `getline` as ONE line (pos_begin = 0, pos_end = 320). Using `std::endl` on line 990 fixes it for me, flushing the stream as mentioned in [#2494 (comment)](https://github.com/mfem/mfem/issues/2494#issuecomment-908638070) also works.

Thanks for checking. I just pushed the fix you suggested (calling `flush` before `tellp`) to the `paraview-restart-fix` branch.

Could you confirm that that fixes the issue for you? And if so, maybe it would make sense to merge that branch into this PR.

**Comment by wo80** [comment]
@pazner Megred `paraview-restart-fix` into my local repo, all tests pass.
@tzanio Should I merge into this PR?

**Comment by tzanio** [comment]
> @tzanio Should I merge into this PR?

yes

**Review by pazner — APPROVED** [review]
Thanks for the fix @wo80.

I was able to build using MinGW using AppVeyor and run the unit tests — everything looked good to me.

It would be good to also run the full test suite (or at least `make test`), but I don't have access to a Windows machine to do it.

**Comment by v-dobrev** [comment]
I tested the PR with MinGW from https://www.mingw-w64.org/downloads/#mingw-builds (the latest pre-built version of GCC they have is GCC 8.1.0) and I had an issue with Example 25 and the functions `jn/_jn`, `yn,_yn` that it uses. It turned out using `-std=gnu++11` instead of `-std=c++11` fixes the issue, so I pushed an update to set `CMAKE_CXX_EXTENSIONS=ON` when building with MinGW.

I tested the serial build with:
```console
cd mfem/build
cmake .. -G "MinGW Makefiles"
cmake --build . -- -j 8
cmake --build . --target exec -- -j 8
ctest
```
The build of MinGW that I used does not have an MPI compiler, so I could not test the parallel/MPI build.

**Comment by wo80** [comment]
@v-dobrev With msys2 one can use `mingw-w64-x86_64-msmpi` package, which usually works well. For example, I can build HYPRE with MPI enabled and all examples compile and run fine. Unfortunately, I haven't been able to build MFEM ex1p:
```
Christian@CHRISTIAN-PC MINGW64 /e/data/projekte/mfem/mpi
$ cmake -G "MinGW Makefiles" -DMFEM_USE_MPI=YES ../mfem/
$ cmake --build . --target ex1p
[  3%] Built target copy_data
[  3%] Built target exec_prerequisites
...
[ 93%] Linking CXX static library libmfem.a
[100%] Built target mfem
[100%] Linking CXX executable ex1p.exe
```
Linking fails with a couple of _undefined reference_ errors related to MPI, like
```
C:/shared/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe: C:/shared/msys64/mingw64/lib/libHYPRE.a(mpistubs.c.obj):mpistubs.c:(.text+0x1b8): undefined reference to `MPI_Group_incl'
```
The file `/e/data/projekte/mfem/mpi/examples/CMakeFiles/ex1p.dir/linklibs.rsp` does specify `-lmsmpi`, so I don't know what's the problem here.

**Comment by wo80** [comment]
CMake lately started to complain (it didn't do so before) about:
```
CMake Error at CMakeLists.txt:505 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "mfem".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * CMakeLists.txt:500 (target_link_libraries)
```
So, on line 505, `target_link_libraries(mfem ws2_32)` should be made `PRIVATE`.

**Comment by v-dobrev** [comment]
Regarding the linking order: we should probably move `MPI_CXX` toward the end of the list here (in particular, after `HYPRE`): https://github.com/mfem/mfem/blob/12c7976b2ef7ee800efa81370aa3b7f47d32eeda/CMakeLists.txt#L426-L434

Regarding the other CMake changes you suggest -- feel free to add them to the PR.

Thanks!

**Comment by wo80** [comment]
I tested build targets `examples`, `tests` and `miniapps` - all build fine (serial and MPI).

Running `unit_tests` and `punit_tests`, all tests pass.

**Comment by tzanio** [comment]
Thanks for your help @wo80 !

**Comment by pazner** [comment]
> I tested build targets `examples`, `tests` and `miniapps` - all build fine (serial and MPI).
> 
> Running `unit_tests` and `punit_tests`, all tests pass.

Great! Do you think you could run `make test`, which runs a somewhat more comprehensive test suite (it will run example and miniapp sample runs in addition to the unit tests)?

**Comment by wo80** [comment]
@pazner For the serial build `make test` reports 100% tests passed.

I cannot run Microsofts MPI executable `mpiexec.exe` from inside the msys2 environment, so the parallel tests are not executed. I manually checked `punit_tests`, `psedov_tests_cpu`, `psedov_tests_debug` and `tmop_pa_tests_cpu`. They all pass.

**Comment by wo80** [comment]
@pazner MPI inside msys2 actually works, just had to tell CMake the right path to `mpiexec.exe`:
```
Christian@CHRISTIAN-PC MINGW64 /e/data/projekte/mfem/mpi
$ export PATH=/c/"Program Files"/"Microsoft MPI"/Bin:$PATH
$ cmake ../mfem -G "MinGW Makefiles" -DMFEM_USE_MPI=YES -DMFEM_MPIEXEC=/c/"Program Files"/"Microsoft MPI"/Bin/mpiexec.exe
$ cmake --build . --target examples -- -j 4
$ cmake --build . --target miniapps -- -j 4
$ cmake --build . --target tests -- -j 4
$ mingw32-make test
```
100% tests passed.

**Comment by tzanio** [comment]
Is this worth mentioning briefly in `CHANGELOG`?

**Comment by pazner** [comment]
Great, thanks for checking!

**Review by v-dobrev — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Review by tzanio — APPROVED** [review]
Thank you very much for this contribution @wo80 !

**Pull request merged**
