### PR TITLE
Optional flag to copy row starts/col starts when using ParMult() [parmult_pr]

### PR DESCRIPTION
**Pull request by ben-s-southworth**
| PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1297](https://github.com/mfem/mfem/pull/1297) | @ben-s-southworth | @tzanio | @psocratis + @kmittal2 | 02/22/20 | 02/25/20 | 02/27/20 | |

### CODE REVIEW

**Comment by ben-s-southworth** [comment]
@tzanio @v-dobrev where is the documentation: https://mfem.github.io/doxygen/html/namespacemfem.html#a8ae7a4e2b11398ce395166a723f129c1 updated? Should add this flag there.

**Comment by tzanio** [comment]
> @tzanio @v-dobrev where is the documentation: https://mfem.github.io/doxygen/html/namespacemfem.html#a8ae7a4e2b11398ce395166a723f129c1 updated? Should add this flag there.

It is automatically generated from the source comment with Doxygen. 

You can document the specific arguments by prefixing them with `@a`, see e.g. https://github.com/mfem/mfem/blob/7d75b885f88a585b9a7bd5975cef2c7105f8f077/linalg/hypre.hpp#L494-L503

**Comment by tzanio** [comment]
Please add the `ready-for-review` label when this is ready...

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
