### PR TITLE
Final changes for mfem-4.6

### PR DESCRIPTION
**Pull request by v-dobrev**
**Target release date:** September 27, 2023

**Done:**
- [x] #3614
- [x] #3461
- [x] #3859
- [x] #3803
- [x] #3827
- [x] #3857 
- [x] #3871 
- [x] #3768
- [x] #3821
- [x] #3792
- [x] #3600
- [x] #3570
- [x] #3880
- [x] #3400
- [x] #3722
- [x] #3797
- [x] #3896 
- [x] #3662
- [x] #3667
- [x] #3894 
- [x] #3325
- [x] #3843

**Postponed:**
- [x] Merge #2669
- [x] Merge #2610
- [x] Merge #3693
- [x] Merge #719
- [x] Merge SYCL support (https://github.com/mfem/mfem/tree/sycl❓)
- [x] Merge #3559
- [x] Merge #3657
- [x] Merge #3388❓

### CODE REVIEW

**Comment by termi-official** [comment]
Depending on the planned release date I can prioritize https://github.com/mfem/mfem/pull/3693 to make sure Kelly works correctly at least in the next release.

**Comment by v-dobrev** [comment]
> Depending on the planned release date I can prioritize #3693 to make sure Kelly works correctly at least in the next release.

Thanks, @termi-official. I'll add approximate release target (mid-September) to the top post and add add #3693 to the list there. Not everything on the list is absolutely necessary for the release -- we can postpone things if we decide.

**Comment by v-dobrev** [comment]
I see these warnings from `nvcc`:
```console
fem/tmop_amr.cpp(585): warning: variable "myid" was set but never used
...
ex37.hpp(167): warning: overloaded virtual function "mfem::VectorCoefficient::Eval" is only partially overridden in class "mfem::VolumeForceCoefficient"
```

**Comment by v-dobrev** [comment]
There are also Ginkgo related warnings -- probably best to fix them in a separate PR in the future.

**Review by tzanio — APPROVED** [review]

**Review by tzanio — APPROVED** [review]
Thanks!

**Pull request merged**
