### PR TITLE
Implement `MultTranspose` for `ConstrainedOperator`.

### PR DESCRIPTION
**Pull request by victor-decaria-nnl**
This implements the transpose of constrained operator. My understanding is that the constrained operator zeros out certain rows and columns of the matrix, then does something to the corresponding diagonal entry depending on the policy. So we just needed some logic to call transpose of the underlying operator when calling `ConstrainedOperator::MultTranspose`.

I added a unit test for `ConstrainedOperator::Mult` and `ConstrainedOperator::MultTranspose` for `DIAG_ONE` and `DIAG_ZERO` for a small matrix.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4040](https://github.com/mfem/mfem/pull/4040) | @victor-decaria-nnl | @tzanio | @jandrej + @sohailreddy | 12/27/23 | 2/7/24 | 2/10/24 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
ping: @sohailreddy, @jandrej

**Review by jandrej — APPROVED** [review]

**Review by sohailreddy — APPROVED** [review]
Looks good to me!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
We got an autotest failures last night which may be due to this PR. For example:

```
+mfem/tests/unit/linalg/test_operator.cpp: In function ‘void C_A_T_C_H_T_E_S_T_0()’:
+mfem/tests/unit/linalg/test_operator.cpp:101:98: error: no matching function for call to ‘mfem::Vector::Vector(<brace-enclosed initializer list>)’
+    Vector y_true_zero_transpose({0, 5723.696294059853, 7877.828900340113, 0., 2883.1173002839714});
+                                                                                                  ^
+In file included from ../../linalg/linalg.hpp:17,
+                 from ../../mfem.hpp:44,
+                 from /home/kolev1/autotest-mfem/tux426/mfem/tests/unit/linalg/test_operator.cpp:12:
+../../linalg/vector.hpp:103:13: note: candidate: ‘template<int N> mfem::Vector::Vector(const double (&)[N])’
+    explicit Vector(const double (&values)[N]) : Vector(N)
+             ^~~~~~
+../../linalg/vector.hpp:103:13: note:   template argument deduction/substitution failed:
+/home/kolev1/autotest-mfem/tux426/mfem/tests/unit/linalg/test_operator.cpp:101:98: note:   mismatched types ‘double’ and ‘int’
+    Vector y_true_zero_transpose({0, 5723.696294059853, 7877.828900340113, 0., 2883.1173002839714});
+                                      
```

I had to resolve conflicts when merging in [`next`](https://github.com/mfem/mfem/commits/next/) see https://github.com/mfem/mfem/commit/b64b695d752e72273db2ff07d03d78a98b08ec9c.

Can you take a look?

**Comment by victor-decaria-nnl** [comment]
@tzanio I resolved the conflicts with master here. I think I fixed the autotest, and am guessing it was due to having an `int` in an initializer list for `Vector`. I changed

`Vector y_true_zero_transpose({0, 5723.696294059853, 7877.828900340113, 0., 2883.1173002839714});`
to
`Vector y_true_zero_transpose({0.0, 5723.696294059853, 7877.828900340113, 0.0, 2883.1173002839714});`

**Comment by pazner** [comment]
Re-merged in `next` for testing...

**Comment by tzanio** [comment]
Thanks @victor-decaria-nnl and @pazner

**Pull request merged**
