### PR TITLE
Write time and cycle to conduit data collection root file [conduitdc-time-cycle-fix]

### PR DESCRIPTION
**Pull request by greene30**
This pull request writes the time, time step, and cycle to the conduit data collection root file. 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1864](https://github.com/mfem/mfem/pull/1864) | @greene30 | @tzanio | @tzanio + @v-dobrev | 11/03/20 | 11/04/20 | 11/08/20 | |

### CODE REVIEW

**Review by tzanio — APPROVED** [review]
Thanks @greene30 !

**Review by cyrush — APPROVED** [review]

**Review by v-dobrev — APPROVED** [review]

**Comment by greene30** [comment]
I'm looking over the CONTRIBUTING.md file and it looks like the next step is for me to merge this branch into the next branch. Can I do that now?

**Comment by tzanio** [comment]
No (you don't have permissions). I'll do it

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
