### PR TITLE
Grouping Copyrights, License and Release checks in 1 job

### PR DESCRIPTION
**Pull request by adrienbernede**
Suggested change to merge 3 repo check jobs in one.

### CODE REVIEW

**Comment by tzanio** [comment]
Is this ready for review @adrienbernede?

**Comment by adrienbernede** [comment]
@tzanio Not yet, I am testing it, and improving a bit.

**Review by tzanio — APPROVED** [review]
Looks good to me, thanks @adrienbernede !

**Review by mlstowell — APPROVED** [review]
That looks perfect! Thanks, @adrienbernede.

**Comment by adrienbernede** [comment]
Thank you @mlstowell for getting involved in the testing!

**Comment by mlstowell** [comment]
> Thank you @mlstowell for getting involved in the testing!

I am a strong advocate for testing. I tend to focus more on unit tests partly because I haven't yet learned much about GitHub workflows and the like. I, for one, am very glad we have you on the team to help us with such things, @adrienbernede!

**Pull request merged**
