### PR TITLE
Fix the shared installation with CUDA and TPL link flags with CUDA

### LINKED ISSUE #1625: Compiling examples & miniapps broken with CUDA+PETSc
When building the MFEM library with CUDA+PETSc, the miniapps cannot be compiled.
(Note this also affects SLEPc as it depends on PETSc.)
If MFEM is configured without CUDA or without PETSc, the compilation is fine.
It seems the problem is the parsing of Xlinker flags (`-Wl`) by `nvcc`.
This is with CUDA version 10.2.89.

The command used to configure MFEM is:
```
make config MFEM_USE_MPI=YES MFEM_USE_METIS_5=yes MPICXX=/opt/mpich/bin/mpicxx METIS_DIR=@MFEM_DIR@/../metis MFEM_USE_CUDA=YES MFEM_USE_PETSC=YES PETSC_DIR=PETSC_DIR=/home/wcdawn/projects/petsc/arch-linux-c-debug/
```

Then, in the examples directory, executing `make ex1p` generates the command
```
nvcc  -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_60 -ccbin /opt/mpich/bin/mpicxx -I.. -I../../hypre/src/hypre/include -I../../metis/include -I/home/wcdawn/projects/petsc/include -I/home/wcdawn/projects/petsc/arch-linux-c-debug/include -I/opt/cuda/include -I/opt/mpich/include ex1p.cpp -o ex1p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis/lib -lmetis -Wl,-rpath,/home/wcdawn/projects/petsc/arch-linux-c-debug/lib -L/home/wcdawn/projects/petsc/arch-linux-c-debug/lib -lpetsc -Wl,-rpath,/opt/cuda/lib -L/opt/cuda/lib -llapack -lblas -lpthread -lX11 -lm -lcufft -lcublas -lcudart -lcusparse -lcusolver -lcuda -lquadmath -lstdc++ -ldl -lrt
```
Which fails with error
```
nvcc fatal   : Unknown option '-Wl,-rpath,/home/wcdawn/projects/petsc/arch-linux-c-debug/lib'
```

`ex1p` can be successfully compiled using `--compiler-options` and `-Xlinker` options as
```
nvcc  -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_60 -ccbin /opt/mpich/bin/mpicxx -I.. -I../../hypre/src/hypre/include -I../../metis/include -I/home/wcdawn/projects/petsc/include -I/home/wcdawn/projects/petsc/arch-linux-c-debug/include -I/opt/cuda/include -I/opt/mpich/include ex1p.cpp -o ex1p -L.. -lmfem -L../../hypre/src/hypre/lib -lHYPRE -L../../metis/lib -lmetis --compiler-options -Xlinker --compiler-options -rpath --compiler-options -Xlinker --compiler-options /home/wcdawn/projects/petsc/arch-linux-c-debug/lib -L/home/wcdawn/projects/petsc/arch-linux-c-debug/lib -lpetsc --compiler-options -Xlinker --compiler-options -rpath --compiler-options -Xlinker --compiler-options /opt/cuda/lib -L/opt/cuda/lib -llapack -lblas -lpthread -lX11 -lm -lcufft -lcublas -lcudart -lcusparse -lcusolver -lcuda -lquadmath -lstdc++ -ldl -lrt
```

It's pretty terse but can be simplified in the Makefile similar to the solution [here](https://codereview.stackexchange.com/questions/161157/avoid-compiler-options-in-makefile-using-nvcc).

Editing the compiler command is simple for the examples but makes compiling the miniapps (e.g. navier) nearly impossible.

### LINKED ISSUE #1945: make install broken with CUDA
I was testing for the first time the CUDA build to add support from PETSc.
I noticed that make install is broken when using SHARED libraries. 

This looks wrong (usage of BUILD_FLAGS instead of LINK_FLAGS) to me https://github.com/mfem/mfem/blob/master/makefile#L539. And it is also kind of redundant, since we have this rule here https://github.com/mfem/mfem/blob/master/makefile#L458.

Why do we need a special command to be issued here https://github.com/mfem/mfem/blob/master/makefile#L547? Why using   `install` is not enough at this point in the makefile?

### PR DESCRIPTION
**Pull request by v-dobrev**
In `makefile`, fix the shared install with CUDA.

In `config/defaults.mk`, use `$(XLINKER)` instead of `-Wl,` in all library link options.

Resolves #1945, resolves #1625.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1950](https://github.com/mfem/mfem/pull/1950) | @v-dobrev | @tzanio | @tzanio + @stefanozampini + @camierjs | 12/15/20 | 01/05/21 | 01/07/21 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
@stefanozampini, can you try this branch to see if it resolves #1945 with your setup?

@adam-sim-dev, @wcdawn, can you try this branch to see if it resolves #1625 with your setup?

**Comment by adam-sim-dev** [comment]
Thanks for this fix. I could build ex3p and ex5p on my side.

OS: Ubuntu 18.04
CXX: icc version 19.1.3.304
MPI: Intel MPI 2019.9.304

I build mfem with CUDA, PETSc, Metis, Hypre, MUMPS enabled.

The following warnings are observed when building mfem:

`linalg/../fem/pgridfunc.hpp(32): warning: overloaded virtual function "mfem::GridFunction::ComputeDGFaceJumpError" is only partially overridden in class "mfem::ParGridFunction"`

```
fem/bilininteg_diffusion_pa.cpp(1554): warning #125: expected a "("
  #pragma unroll MQ1
                 ^
```

**Comment by wcdawn** [comment]
Yes! This fixes the problem I was having. I was able to successfully compile `mfem` and compile & run `ex11p` using CUDA, PETSC, and SLEPC (as well as HYPRE and METIS).

I do seem similar warnings as @adam-sim-dev but I think this is probably just a quirk of `nvcc`.

**Comment by v-dobrev** [comment]
@adam-sim-dev and @wcdawn, thanks for testing this!

> The following warnings are observed when building mfem:
> 
> `linalg/../fem/pgridfunc.hpp(32): warning: overloaded virtual function "mfem::GridFunction::ComputeDGFaceJumpError" is only partially overridden in class "mfem::ParGridFunction"`

We have a PR to fix this warning: #1920.

Regarding the warnings:

> ```
> fem/bilininteg_diffusion_pa.cpp(1554): warning #125: expected a "("
>   #pragma unroll MQ1
>                  ^
> ```
> 
> ```
> fem/bilininteg_mass_pa.cpp(942): warning #125: expected a "("
>   #pragma unroll MQ1
>                  ^
> ```

we probably need to fix the `MFEM_UNROLL` macro for the Intel compiler. cc: @camierjs.

**Comment by stefanozampini** [comment]
The building fix was the one I was proposing indeed. In addition to the other warnings, I get these too

```
/home/zampins/Devel/petsc/arch-gpu-h2opus/externalpackages/git.mfem/linalg/../general/forall.hpp(333): warning: statement is unreachable
          detected during instantiation of "void mfem::ForallWrap<DIM,DBODY,HBODY>(__nv_bool, int, DBODY &&, HBODY &&, int, int, int) [with DIM=1, DBODY=lambda [](int)->void, HBODY=lambda [](int)->void]" 
/home/zampins/Devel/petsc/arch-gpu-h2opus/externalpackages/git.mfem/linalg/densemat.cpp(3526): here

/home/zampins/Devel/petsc/arch-gpu-h2opus/externalpackages/git.mfem/linalg/../general/forall.hpp(333): warning: statement is unreachable
          detected during instantiation of "void mfem::ForallWrap<DIM,DBODY,HBODY>(__nv_bool, int, DBODY &&, HBODY &&, int, int, int) [with DIM=1, DBODY=lambda [](int)->void, HBODY=lambda [](int)->void]" 
/home/zampins/Devel/petsc/arch-gpu-h2opus/externalpackages/git.mfem/linalg/densemat.cpp(3591): here

```

I have opened a PR with some preliminary support for PETSc on GPUs https://github.com/mfem/mfem/pull/1963

**Comment by v-dobrev** [comment]
@stefanozampini, the warnings seem to come from here (line 333): https://github.com/mfem/mfem/blob/8f010f3c0cd808faf84e2ff3c7d6fc988f55dd72/general/forall.hpp#L332-L334

Is that correct?

Maybe if we add `else` in the beginning of the second and third lines, that will silence the warning?

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
@camierjs, are you OK with these changes?

**Review by camierjs — APPROVED** [review]

**Comment by tzanio** [comment]
@stefanozampini any objections to merge this and continue the discussion in #1963?

**Review by stefanozampini — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
