### PR TITLE
Mark mfem_error as [[noreturn]]

### PR DESCRIPTION
**Pull request by pazner**
If a function has a non-void return type, the compiler will complain if there is not a return value in all control paths. This can generate a warning if, for example, `MFEM_ABORT` is called in the `default` case of a switch statement, or in the else branch of an if-else statement.

Since C++11, functions can be marked as [`[[noreturn]]`](https://en.cppreference.com/w/cpp/language/attributes/noreturn), which tells the compiler they never return. `mfem_error` is one such function, since it calls `std::abort`. This PR marks `mfem_error` as `[[noreturn]]`, which should silence unnecessary compiler warnings.

For example:

```cpp
#include "mfem.hpp"
#include <iostream>

using namespace std;
using namespace mfem;

int f(int x)
{
   if (x == 1) { return 1; }
   else { MFEM_ABORT(""); }
}

int main(int argc, char *argv[])
{
   int x = 1;
   OptionsParser args(argc, argv);
   args.AddOption(&x, "-x", "--x", "x");
   args.ParseCheck();
   cout << f(x) << '\n';
   return 0;
}
```

On master, this code will generate the warning `non-void function does not return a value in all control paths [-Wreturn-type]` (clang version 15.0.0). On this branch, it compiles cleanly.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4021](https://github.com/mfem/mfem/pull/4021) | @pazner | @tzanio | @sebastiangrimberg + @aschaf | 12/7/23 | 12/11/23 | 12/12/23 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by sebastiangrimberg — APPROVED** [review]
Two comments:
1. Had to double check that `[[noreturn]]` is valid for functions which throw exceptions (when `MFEM_USE_EXCEPTIONS` is defined and `mfem_error_action == MFEM_ERROR_THROW`), and indeed this is valid.
2. Does the `[[noreturn]]` attribute need to be specified in the definition in the cpp file? I thought it was only needed at declaration in the header.

**Comment by pazner** [comment]
Thanks @sebastiangrimberg.
 
> 1. Had to double check that `[[noreturn]]` is valid for functions which throw exceptions (when `MFEM_USE_EXCEPTIONS` is defined and `mfem_error_action == MFEM_ERROR_THROW`), and indeed this is valid.

Yep, throwing an exception does not count as returning (it will break the normal control flow). That's illustrated in the [cppreference example](https://en.cppreference.com/w/cpp/language/attributes/noreturn#Example).

> 2. Does the `[[noreturn]]` attribute need to be specified in the definition in the cpp file? I thought it was only needed at declaration in the header.

To be honest, I'm not sure (but I don't think it hurts). I originally had it only in the header, but then I changed it [here](https://github.com/mfem/mfem/compare/3dfe52b4b1ef6092f13f8c74d4b2ff5fb4586e2a..b13d4d663166e95c47e023ad32311a2df97b9414) because of the following from cppreference:

> If a function is declared with [[noreturn]] in one translation unit, and the same function is declared without [[noreturn]] in another translation unit, the program is ill-formed; no diagnostic required.

I suppose on a closer reading, this does not apply, since the translation unit for error.cpp will always include the [[noreturn]] declaration in error.hpp.

**Comment by sebastiangrimberg** [comment]
> I suppose on a closer reading, this does not apply, since the translation unit for error.cpp will always include the [[noreturn]] declaration in error.hpp.

Yes, this is true. I think it's clearer to have it only at the declaration, consistent with keywords like `inline`, `static`, etc.

**Comment by pazner** [comment]
OK, changed in fa3b23fc9

**Review by sebastiangrimberg — APPROVED** [review]

**Comment by v-dobrev** [comment]
I think to silence such warnings, we've been using "never reachable" return statements after `MFEM_ABORT` or similar macros. Using `[[noreturn]]` solves the issue without needing the "unreachable" return statement. 🎉 

I didn't realize it is available in C++11 -- I thought it was in a newer C++ standard.

**Review by jandrej — APPROVED** [review]
I just ran into this behavior.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Review by aschaf — APPROVED** [review]

**Pull request merged**
