### PR TITLE
Add AMD HIP support to CMake build system

### LINKED ISSUE #1428: HIP support with CMake
We can probably "steal" the `FindHIP.cmake` from OCCA: https://github.com/libocca/occa/blob/master/cmake/FindHIP.cmake contributed by @noelchalmers.

### PR DESCRIPTION
**Pull request by joshessman-llnl**
This PR adds the HIP CMake scripts from https://github.com/ROCm-Developer-Tools/HIP and builds the library/miniapps/examples with `hipcc` when `MFEM_USE_HIP` is enabled.

This required that the `add_mfem_examples` and `add_mfem_miniapp` CMake functions be converted to macros - creating a new function scope "hides" some required HIP variables in the parent scope. 

I did not configure the unit tests to use HIP as the Makefile build system currently does not build HIP-specific tests (w.r.t. `mfem::Device` configuration) as it does for CUDA, though I can add those in if it would be helpful.  If the "regular" unit tests should be built with `hipcc` I can add that in as well.

Resolves #1428.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1906](https://github.com/mfem/mfem/pull/1906) | @joshessman-llnl | @tzanio | @camierjs + @YohannDudouit + @jandrej + @v-dobrev | 12/15/20 | 01/24/21 | 01/31/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
@camierjs, @YohannDudouit, @jandrej and @v-dobrev -- can you please review?

**Comment by camierjs** [comment]
How do you enable `MFEM_USE_HIP` ? `-DMFEM_USE_HIP=YES` does not seem to be used in the command line?

**Comment by jandrej** [comment]
> How do you enable `MFEM_USE_HIP` ? `-DMFEM_USE_HIP=YES` does not seem to be used in the command line?
> The compilation find `HIPCC`, but `mfem` needs this to be turned `on` to be able to use the `hip` device.

Can you elaborate? I used `cmake .. -DMFEM_USE_HIP=ON` and cmake builds the sources with `hipcc`. @joshessman-llnl explained that he is not running any tests with the Device configured, to stay consistent with the makefiles.

**Comment by camierjs** [comment]
Is there a way to specify the `HIP_ARCH` as the `CUDA_ARCH`?
That would be useful to have it also as an info message during the `cmake` configuration.

**Comment by joshessman-llnl** [comment]
> 
> 
> Is there a way to specify the `HIP_ARCH` as the `CUDA_ARCH`?
> That would be useful to have it also as an info message during the `cmake` configuration.

Yes - I've gone ahead and added a HIP_ARCH variable that is displayed during build configuration and is used to set a `hipcc` compiler flag.

**Comment by camierjs** [comment]
Trying with :
```
cmake .. -DMFEM_USE_HIP=YES -DHIP_ARCH=gfx906 \
               -DMFEM_ENABLE_TESTING=YES -DMFEM_ENABLE_EXAMPLES=YES -DMFEM_ENABLE_MINIAPPS=YES \
               -DMFEM_USE_MPI=NO -DMFEM_USE_METIS=NO
```
I think we need to add :
```
if (MFEM_USE_HIP)
  set_source_files_properties(${SRCS} PROPERTIES HIP_SOURCE_PROPERTY_FORMAT TRUE)
endif()
```
and:
```
if (MFEM_USE_HIP)
   hip_add_library(mfem-common ${SRCS} ${HDRS})
else()
   add_library(mfem-common ${SRCS} ${HDRS})
endif()
```
in the `miniapps/common/CMakeLists.txt`.

**Comment by camierjs** [comment]
As well as in the `tests/unit`.

**Comment by joshessman-llnl** [comment]
Ah, I was not aware that the `all` and default targets didn't include everything.  I've added a set of CMake macros for adding libraries/executables such that `make all tests examples miniapps` succeeds. as does the `ctest` command you posted.

**Comment by camierjs** [comment]
> Ah, I was not aware that the `all` and default targets didn't include everything. I've added a set of CMake macros for adding libraries/executables such that `make all tests examples miniapps` succeeds. as does the `ctest` command you posted.

Awesome! Thank you for adding it!

**Comment by camierjs** [comment]
LGTM

**Review by camierjs — APPROVED** [review]

**Comment by tzanio** [comment]
@YohannDudouit and @v-dobrev, can you please take a look?

**Comment by adrienbernede** [comment]
LGTM

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Can you please mention this in `CHANGELOG`?

**Review by tzanio — APPROVED** [review]
Thanks for this really useful contribution @joshessman-llnl 🎉 

@camierjs, @YohannDudouit and @jandrej -- thank you for reviewing!

**Pull request merged**
