### PR TITLE
Adjustments to the branch-history script [branch-history-dev]

### PR DESCRIPTION
**Pull request by tzanio**
The [branch-history script](https://github.com/mfem/mfem/blob/master/tests/scripts/branch-history) may be too conservative currently.

In this PR we want discuss adjustments suggested by the team as they use it.

These adjustments, include:
- Adding filtering 
- Changing the default ["acceptable" values](https://github.com/mfem/mfem/blob/master/tests/scripts/branch-history#L66-L77)

### CODE REVIEW

**Comment by tzanio** [comment]
@mfem/reviewers, please comment here what changes you'd like to see in the new `branch-history` script.

The initial commit in this PR will filter out changes in the existing source files.

**Comment by tzanio** [comment]
See also #1267 -- do we want to incorporate part of the scripts in makefile targets, or should we encourage folks to run the scripts themselves and document them better?

**Comment by IdoAkkerman** [comment]
The script checks all commits, not the final changes.
For instance  in #476 I changed fe.cpp somewhere and changed it back later (debug stuff I guess).
It now gets flagged as exceptionally large file.
Is it reasonable to check every commit? Instead of just the final changes?

File size check will flag changes to fe.cpp and mesh.cpp. Why would the file size be an issue?
Shouldn't that mean that these files need to be split in smaller ones?

**Comment by tzanio** [comment]
> The script checks all commits, not the final changes.
> For instance in #476 I changed fe.cpp somewhere and changed it back later (debug stuff I guess).
> It now gets flagged as exceptionally large file.
> Is it reasonable to check every commit? Instead of just the final changes?

It checks all commits that are not in master, which is very much intentional. In the settings of a GitHub PR if a large file has been added in one commit and deleted in another the reviewers will not see it (unless they review every single commit). 

> File size check will flag changes to fe.cpp and mesh.cpp. 

These two files will be addressed

**Comment by IdoAkkerman** [comment]
If not done already:
tests/scripts/*.err
tests/scripts/*.out
should be added to .gitignore

**Comment by IdoAkkerman** [comment]
Now realize, it was perhaps out of place to make this commit.
If I overstepped here please let me know!!

**Comment by tzanio** [comment]
> Now realize, it was perhaps out of place to make this commit.
> If I overstepped here please let me know!!

In general it is good to ask, but that particular commit is fine.

It should be `tests/scripts/*.err` and `tests/scripts/*.out` though...

**Comment by tzanio** [comment]
We should update the [Automated Testing]( https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#automated-testing) section of `CONTRIBUTING.md` with description of the travis checks which in particular explains that failures in `branch-history` are acceptable.

**Comment by pazner** [comment]
We can also think about incorporating something like this script: https://github.com/mfem/mfem/issues/1255#issuecomment-586528331

The goal would be to reduce the number of false positives resulting from small modifications to large files like `mesh.cpp`.

**Comment by tzanio** [comment]
Closed in favor of #1267

**Pull request closed without merging**
