### PR TITLE
Parallel Unstructured Mesh Infrastructure (PUMI): Attaching Gmsh Physical Entity Tags [cws/pumi-gmsh-phys-ents]

### PR DESCRIPTION
**Pull request by cwsmith**
This PR adds support for attaching Gmsh physical entity tags stored in PUMI meshes as an attribute on an MFEM mesh.  See issue #2726 for development and testing discussion.

This PR **is backward compatible** with PUMI meshes created with PUMI <= 2.2.6, but only PUMI meshes created with the upcoming [PUMI 2.2.7 release](https://github.com/SCOREC/core/issues/357) or the current [master@19185e9](https://github.com/SCOREC/core/tree/19185e9a8590176575721f7057764a4feafe3e4c) branch will contain the Gmsh physical entity tags.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2782](https://github.com/mfem/mfem/pull/2782) | @cwsmith | @tzanio | @tzanio + @mlstowell | 01/27/22 | 02/01/22 | 02/08/22 | |

### CODE REVIEW

**Comment by tzanio** [comment]
@cwsmith, please mark as `ready-for-review` when this is ready.

(see https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#quick-summary)

**Review by mlstowell — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Can you fix the style please: https://github.com/mfem/mfem/runs/5023713810?check_suite_focus=true#step:4

(the `code-style` CI check above didn't run because the PR is from a fork)

**Comment by tzanio** [comment]
Thanks @cwsmith !

**Comment by v-dobrev** [comment]
Hi @cwsmith, our nighly tests uncovered a build issue with PUMI v2.2.6:
```console
ex1p.cpp:152:29: error: invalid conversion from 'const ma::Input*' to 'ma::Input*' [-fpermissive]
          crv::adapt(uniInput);
                             ^
```
Is it possible to change the PR to keep it compatible with PUMI v2.2.6, or should we consider PUMI v2.2.7 to be the new minimum version requirement for PUMI? Maybe we can use `auto` when defining `uniInput`? I'm not sure about the other code changes.

**Comment by cwsmith** [comment]
@v-dobrev Commit https://github.com/mfem/mfem/pull/2782/commits/a88269f1f35abd31a45e26e16b728043df4caea7 using `auto` was just pushed.  Thanks for the suggestion.  This should restore compatibility with PUMI 2.2.6.  

I'm fine with supporting a small range of minor PUMI versions or increasing the minimum required version.  PUMI 2.2.7 should be released in late February (... after SIAM PP22).  Do you have a preference?

**Comment by v-dobrev** [comment]
Thanks, @cwsmith!

Let's keep the required PUMI version at 2.2.6 since 2.2.7 is not released yet.

Actually, right now the required version is listed as `PUMI == 2.2.3`: https://github.com/mfem/mfem/blob/a96065ed1802ee95e7a33ee749b2ae4a6e4a6de6/INSTALL#L707 We should update this accordingly: either `PUMI >= 2.2.3`, `PUMI >= 2.2.6`, or something like that.

**Comment by cwsmith** [comment]
@v-dobrev You're welcome.  The minimum pumi version listed in the `INSTALL` file was increased to 2.2.6 in https://github.com/mfem/mfem/pull/2782/commits/fb41c298e38d07a96c1d209a0f1ec8b5e3ef66ad and https://github.com/mfem/mfem/pull/2782/commits/606ba7c19024eeddfc1e2f2d464e0bec85ced9be increased the minimum version in `CMakeLists.txt`.  

I didn't see a version check mechanism in the makefile based build system.  Did I miss it (I didn't dig too deep)?

**Comment by v-dobrev** [comment]
> I didn't see a version check mechanism in the makefile based build system. Did I miss it (I didn't dig too deep)?

No, there is no version check in the GNU make build system.

Also, there were no issues in the nightly tests with the latest commit, so this should be ready to be merged.

**Pull request merged**
