### PR TITLE
CI: add pedantic flags

### LINKED ISSUE #1566: Force warnings to be errors in Travis CI
This came up in the following discussion: https://github.com/mfem/mfem/pull/1529#discussion_r440983510

I think we can add the following extra options to catch some common warnings: `-pedantic -Wall -Werror`. The simplest way to do this (independent of the debug option) is to set the makefile variable `CPPFLAGS`.

### PR DESCRIPTION
**Pull request by adrienbernede**
Fixes #1566

The goal is to build with stricter requirement to catch some warnings and alert.

Other Travis CI issues we can fix here:
- [x] Use caching in the "checks" phase (currently the "gitignore" step builds hypre all the time)
- [x] Skip the "branch-history" test for the `next` branch.
- [x] Try using `ccache` to speedup builds.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1600](https://github.com/mfem/mfem/pull/1600) | @adrienbernede | @tzanio | @v-dobrev + @tzanio + @jandrej | 07/25/20 | 07/28/20 | 08/04/20 | |

### CODE REVIEW

**Comment by adrienbernede** [comment]
@v-dobrev The test is failing because what seem to be a warning transformed into an error.
@pazner Would it make sense to you to initialize Cik? (It makes sense to me).

**Comment by adrienbernede** [comment]
Doing it instead of asking :)

**Comment by v-dobrev** [comment]
> @v-dobrev The test is failing because what seems to be a warning transformed into an error.
> @pazner Would it make sense to you to initialize Cik? (It makes sense to me).

I was just looking at that. :-)

The warning on travis may be bogus -- newer versions of gcc may not show it.

**Comment by v-dobrev** [comment]
I just tried it with gcc 9.2 on mac and I got the same warning-error. It should fine to just initialize it.

**Comment by v-dobrev** [comment]
With gcc 9.2 on mac I don't get these warnings-errors: https://travis-ci.com/github/mfem/mfem/jobs/357198256#L4230-L4236

However, I get a different error:
```console
In file included from fem/datacollection.cpp:16:
fem/picojson.h: In function 'bool picojson::_parse(Context&, picojson::input<Iter>&) [with Context = picojson::default_parse_context; Iter = __gnu_cxx::__normal_iterator<const char*, std::__cxx11::basic_string<char> >]':
fem/picojson.h:249:10: error: '<anonymous>.picojson::value::u_' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  249 |       u_ = x.u_;
      |       ~~~^~~~~~
```

**Comment by v-dobrev** [comment]
On the other hand, with `Apple clang version 11.0.0 (clang-1100.0.33.16)` I don't see any issues, even before the last fix.

**Comment by v-dobrev** [comment]
One option is to switch to a newer Ubuntu version with newer gcc in Travis.

**Comment by pazner** [comment]
> Would it make sense to you to initialize C_ik? (It makes sense to me).

Yes, definitely makes sense — thanks for fixing @adrienbernede!

**Comment by adrienbernede** [comment]
@v-dobrev @tzanio I need a clear guideline here.

By enabling warning as error here we have different behavior depending of the compiler type/version.

This is not necessarily an issue because it may actually spot potential "weaknesses"... except when there are false positives.

@v-dobrev is suggesting to switch to a newer ubuntu, but I get errors even with gcc 6.1 and gcc 8.1.0 on quartz.

I don’t plan on addressing all of these, but I had a look at several of them:

`mesh/nurbs.cpp:312:32: error: array subscript is above array bounds [-Werror=array-bounds]`
`        a[s2][j] = (a[s1][j] - a[s1][j-1])/ndu[pk+1][rk+j];`
`                       ~~~~~~~^`
This one is hard to assess, I gave up because I felt lazy dealing with indexes without being involved in the underlying algorithm. These lines were lastly modified by @IdoAkkerman who may be more efficient at spotting the origin of the problem?

`fem/restriction.cpp:820:69: error: 'orientation' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                                                orientation, dof1d, d);`
This one is, IMO, easy to address: initialization of `orientation` is conditional, but the conditional `if (dof_reorder)` leads to an abort if not verified, also it is already tested earlier in the constructor. I have a fix I can propose.

Then the real problem comes from tons and tons of these:
`fem/transfer.cpp:385:43: error: 'sol_x[13]' may be used uninitialized in this function [-Werror=maybe-uninitialized]`
Typically `sol_x` will be allocated to size "MAX_whatever" and then initialized up to "whatever".
Although we could totally initialize on the full size, the table is only used on the initialized subset. So I suspect the table is large for some padding/alignment optimization?

There may be other ones, but the latest one is flooding my terminal :).

**Comment by v-dobrev** [comment]
LGTM

**Comment by v-dobrev** [comment]
@adrienbernede, I started trying a few things here and ended up "hijacking" your branch -- sorry about that.

I think these are good additions and fixes and, in particular, speedup the travis builds noticeably (by using `ccache`).

The only outstanding issue is the added flags in the gitlab ci -- the optimized builds with gcc fail due to warnings (see https://lc.llnl.gov/gitlab/mfem/mfem/pipelines/13948). This was also happening in travis, so I disabled these new flags (`-pedantic -Wall -Werror`) for the optimized builds with gcc. We can do the same in the gitlab ci, or just not add these flags there.

I think this is very close to being ready for review. Take a look and let me know what you think.

**Comment by adrienbernede** [comment]
If you agree with me, I’ll remove those flags.

**Comment by v-dobrev** [comment]
> If you agree with me, I’ll remove those flags.

I agree with you.

**Comment by adrienbernede** [comment]
LGTM

**Comment by v-dobrev** [comment]
@adrienbernede, I think this is ready for review -- if you agree, add the "ready-for-review" label (and remove "WIP").

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
