### PR TITLE
fix build with petsc-3.15

### PR DESCRIPTION
**Pull request by balay**
This fix is needed for xsdk@develop

### CODE REVIEW

**Comment by balay** [comment]
@acfisher  The code checker is recommending the following change - which doesn't match the rest of the file - so will wait for a response

https://github.com/mfem/mfem/runs/2242767209?check_suite_focus=true

```
-               ierr = PetscSFBcastBegin(sf,MPIU_SCALAR,garray,larray,MPI_REPLACE); CCHKERRQ(comm,ierr);
-               ierr = PetscSFBcastEnd(sf,MPIU_SCALAR,garray,larray,MPI_REPLACE); CCHKERRQ(comm,ierr);
+               ierr = PetscSFBcastBegin(sf,MPIU_SCALAR,garray,larray,MPI_REPLACE);
+               CCHKERRQ(comm,ierr);
+               ierr = PetscSFBcastEnd(sf,MPIU_SCALAR,garray,larray,MPI_REPLACE);
+               CCHKERRQ(comm,ierr);
```

**Comment by balay** [comment]
@v-dobrev  My current xsdk build is mfem~cuda

**Comment by adam-sim-dev** [comment]
@v-dobrev , I think it should fix #2140

**Comment by stefanozampini** [comment]
https://github.com/mfem/mfem/pull/1963/commits/41a96be0e5ae57c54cb17c15b7cbff9710788302 also fixes a CUDA building issue with the latest release. @balay I'm closing this PR if you confirm it builds fine on your end with  https://github.com/mfem/mfem/pull/1963

**Comment by balay** [comment]
@stefanozampini from #2140 I see the same (improved) fix at https://github.com/mfem/mfem/commit/488e3f02a34e428ca6cbc4d20b128485341a80bd so can prefer that fix.

I can run a test with   #1963 - but currently my build is without cuda [so only the above is likely to get tested]

**Comment by stefanozampini** [comment]
@balay  thanks. Closing this PR

**Comment by balay** [comment]
To confirm - I ran a `xsdk@develop` build which builds `mfem@develop~cuda` using the following change - and that built fine.
```
-    version('develop', branch='master')
+    version('develop', branch='stefanozampini/add-petsc-cuda-support')
```

**Comment by v-dobrev** [comment]
Hi @balay, just FYI: I'm using this as a patch in MFEM's spack package to allow mfem v4.2 to work with petsc v3.15.0 -- this is added here https://github.com/spack/spack/pull/22735.

**Pull request closed without merging**
