### PR TITLE
Modified SLI solver to work w/ non-SPD operator and preconditioner

### PR DESCRIPTION
**Pull request by ben-s-southworth**
Stopping tolerance is based on the norm of residual or preconditioned residual, and no longer requires that the preconditioner induces a norm. 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1303](https://github.com/mfem/mfem/pull/1303) | @ben-s-southworth | @tzanio | @delyank + @barker29 | 02/22/20 | 03/10/20 | 03/17/20 | |

### CODE REVIEW

**Comment by delyank** [comment]
I don't know if there was a discussion on this issue. If there is one, please point me to it.

I understand the idea behind the PR, but here is my concern.

Consider the SPD case and say that A is the matrix and B is the preconditioner but the very special case when B = A^(-1) exactly. Also, e is the current error and r is the current residual. So Ae = r and Br = e.

Then, the measure (B r, r) = (e, A e). So it is the energy (squared) of the error and it usually is the most natural measure for a problem that aims at minimizing the energy from the get go. Conversely, || Br || = || e ||. That is, this the Euclidean norm of the error. I know this is more general. So the difference is in the norms and they are not precisely equivalent. The difference (when relative errors are considered) is like measuring the error in L2 vs H1 (excluding the sqrt part). For an elliptic problem H1 is the natural choice.

So it makes sense to have both somehow, I guess.

**Comment by ben-s-southworth** [comment]
@delyank There was a brief discussion here: https://github.com/mfem/mfem/issues/1052. I don't disagree that for an elliptic/H1 problem, the A-norm may be the correct norm to measure in. However, I don't think it makes sense for the *default* behavior of the most basic and general linear fixed-point iteration to be designed for/require H1/SPD problems. Having both options makes sense and would not b difficult with a flag or two separate classes, I guess the question is which to default? SPD default would not affect existing code, but still seems non-intuitive to me, and vice-versa for non-SPD default.

**Comment by tzanio** [comment]
Let's postpone this merge until the mfem-4.1 release is complete...

**Comment by delyank** [comment]
Ben, I agree that assuming SPD in the default is not the best. Adding the flag is not the main thing now and Andrew has a good point. Probably, it's very rare to use this class for SPD problems considering that CG is always an option. So let's leave it with your general modification without flags.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Can you please merge in master and document this in CHANGELOG?

**Pull request merged**
