### PR TITLE
[WIP] Tmopt Kernels + API 

### PR DESCRIPTION
**Pull request by camierjs**
Merging PR:
 - #1731 Extended interface for PANonlinearFormExtention and its gradient [tmopt-split-api]
 - #1484 [TMOP] @GPU [tmopt]

### CODE REVIEW

**Comment by camierjs** [comment]
LGTM

**Comment by camierjs** [comment]
LGTM

**Comment by camierjs** [comment]
LGTM

**Comment by adrienbernede** [comment]
The error in Gitlab CI looks like a time-out issue. There are new tests with this PR, so it may makes sense to check if some of those are unnecessarily long, or if we should increase the allocation time.

**Comment by v-dobrev** [comment]
> The error in Gitlab CI looks like a time-out issue. There are new tests with this PR, so it may makes sense to check if some of those are unnecessarily long, or if we should increase the allocation time.

Looking at the log of the failed job, I see that the `tmop*` tests passed. Some of the other tests did not finish but that's not so important in this testing branch/PR. Also, the failed job was the "debug" job (that's why it is slower) -- the optimized jobs ran through all the tests without issues.

**Pull request closed without merging**
