### PR TITLE
CMake creates config.mk and installs config.mk and test.mk [cwsmith/cmake_create_config.mk]

### LINKED ISSUE #312: Obtain config.mk in CMAKE builds
Would it be possible to install a config.mk file out of a CMAKE build?
The reason is that at present if you build MFEM with CMAKE, you are also forced to build other codes that depend on MFEM (in this case, a library) with CMAKE. I'm not aware of any tool that permits to include and use  XXX.cmake configuration files with a standard makefile.

### PR DESCRIPTION
**Pull request by cwsmith**
This was tested with a spack install of hypre, metis, zlib, and pumi.  

My mfem cmake script is below:
```
#!/bin/bash -ex
usage="Usage: $0 <path to mfem source> <enable pumi=0|1>"
[ $# -ne 2 ] && echo $usage && exit 1
src=$1
[ ! -e $src ] && echo "mfem source dir '$src' is not accessible" && exit 1
pumi=$2
[[ $pumi -ne 0 &&  $pumi -ne 1 ]] && echo $usage && exit 1
use_pumi=ON
[ $pumi == 0 ] && use_pumi=OFF

hypre=`spack location -i hypre`
metis=`spack location -i metis`
zlib=`spack location -i zlib`
pumi=`spack location -i pumi`

cmake $src \
-DCPPFLAGS="-DFOO=1" \
-DCMAKE_CXX_COMPILER=mpicxx \
-DCMAKE_CXX_FLAGS='-g -O2' \
-DMFEM_USE_MPI=ON \
-DHYPRE_DIR=$hypre \
-DMETIS_DIR=$metis \
-DZLIB_DIR=$zlib \
-DMFEM_USE_PUMI=$use_pumi \
-DPUMI_DIR=$pumi \
-DCMAKE_INSTALL_PREFIX=$PWD/install
```

So, assuming the above script is named `config-mfem.sh` the mfem install sequence is:

```
git clone git@github.com:cwsmith/mfem
git checkout cwsmith/cmake_create_config.mk
mkdir build-mfem 
cd build-mfem
/path/to/config-mfem.sh ../mfem 1 # build with pumi enabled
make install -j
```

Laghos can then be built with:

```
git clone git@github.com:CEED/Laghos.git
d=/path/to/mfem/install/dir
make MFEM_DIR=$d CONFIG_MK=$d/share/mfem/config.mk TEST_MK=$d/share/mfem/test.mk
```

Resolves #312

### CODE REVIEW

**Comment by cwsmith** [comment]
I'm fixing the build without pumi now that appveyor found.

**Comment by tzanio** [comment]
Thanks for doing this @cwsmith!

Added a note that it resolves #312.

**Comment by v-dobrev** [comment]
@cwsmith, can you give me permission to push to your branch - I have some small additions and changes I want to push.

**Comment by cwsmith** [comment]
@v-dobrev I sent you an invite.

**Comment by cwsmith** [comment]
Looks good to me.  Following the instructions from the [OP](https://github.com/mfem/mfem/pull/508#issue-192108792), I was able to successfully build and run Laghos.

CMake has `CMAKE_SHARED_LIBRARY_CXX_FLAGS`.  The policy here:
https://cmake.org/cmake/help/v3.12/policy/CMP0018.html?highlight=cmake_shared_library_%20lang%20_flags
indicates that the logic for creating PIC libs has changed, but, as I understand, this variable will remain in cmake and we can read from it to get the flag.  The part that leaves me in some doubt is the statement that there are 'new undocumented platform variables to select (PIC) flags'.  It seems like using one of those may be more future proof... if using undocumented variables can be considered safe at all.  

If there is a resident cmake expert we can consult with it may be a good idea to double check this.

**Comment by v-dobrev** [comment]
Thanks @cwsmith!

I tried your suggestion to use the variable `CMAKE_SHARED_LIBRARY_CXX_FLAGS` instead of the hard-coded `-fPIC` value and it worked for me, so I made the change.

**Pull request merged**
