### PR TITLE
Autotest improvements [testing/bernede1/autotest-improved]

### PR DESCRIPTION
**Pull request by adrienbernede**
- Fix the bug that allowed autotest results to show both as failing and success if they ran twice, first failing and then passing. The directory is now overridden by each run.
- In the output file, add a link to the pipeline that originated the present results.

Screen Shot 2021-07-26 at 8 49 01 AM

Screen Shot 2021-07-26 at 8 49 45 AM

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2344](https://github.com/mfem/mfem/pull/2344) | @adrienbernede | @tzanio | @tzanio + @jandrej | 07/26/21 | 07/26/21 | 07/26/21 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
Maybe we can avoid purging previous results and just create a new directory with a suffix like `_01`, `_02`, etc. This is what the internal tests do.

**Comment by adrienbernede** [comment]
> Maybe we can avoid purging previous results and just create a new directory with a suffix like `_01`, `_02`, etc. This is what the internal tests do.

Good point.

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
