### PR TITLE
View boundary attributes in `mesh-explorer` [view-bdr-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
This is a smallish change to the `mesh-explorer` miniapp which views boundary attributes by skinning a 3D mesh to produce a 2D mesh consisting of its boundary elements.

Currently this mesh skinning function does not support mesh nodes defined using a discontinuous grid function.  This limitation can be revisited after merging PR #716 or PR #1194.

| PR | Author | Editor | Reviewers  | Assignment | Approval | Merge |
| --- | --- | --- | ---  | --- | --- | --- |
| https://github.com/mfem/mfem/pull/1231 | @mlstowell   | @tzanio | @drzisga + @bslazarov | 01/13/20 | 02/03/20 | ⌛due 02/10/20 |

### CODE REVIEW

**Comment by tzanio** [comment]
@drzisga and @bslazarov, reminder that the reviews for this PR are due in less than a week

**Comment by bslazarov** [comment]
How should I test it? It compiles and runs without any problems. However, I am not sure how to test the new features.

**Comment by tzanio** [comment]
> However, I am not sure how to test the new features.

Build `mesh-explorer` (in `miniapps/meshing`) and open a mesh with boundary attributes, e.g. `../../data/beam-hex.mesh`)?

**Comment by bslazarov** [comment]
Compiles fine, valgrinded - everything is ok, works fine as well!

**Comment by tzanio** [comment]
Thanks @bslazarov! @drzisga, do you have time to take a look?

**Comment by tzanio** [comment]
Merged in `next` for testing ...

**Pull request merged**
