### PR TITLE
Change face neighbor numbering in `GetSharedFaceTransformations`

### LINKED ISSUE #1458: Face neighbor element number is ambiguous in interior face integrators in parallel
An interior face integrator has access to the element numbers of the two neighboring elements through `Trans.Elem1No` and `Trans.Elem2No`. Many DG integrators check e.g. `Trans.Elem1No >= 0` to verify that the face is interior rather than boundary.

An ambiguity is introduced in parallel, where the index `Trans.Elem2No` could refer to a local (on-processor) element, or to a "face neighbor" element, and so if the integrator needs information about the finite element, it does not appear possible to decide whether to call `ParFiniteElementSpace::GetFE` or `ParFiniteElementSpace::GetFaceNbrFE`.

As far as I can tell, there is currently no way to resolve this ambiguity.

One potential solution is to modify `ParBilinearForm::AssembleSharedFaces`, for example by passing an element index such that `Trans.Elem2No` is greater than or equal to the number of elements, indicating that the element is a face neighbor element (and then the face neighbor element index can be recovered by subtracting the number of on-processor elements in the mesh).

### PR DESCRIPTION
**Pull request by pazner**
This PR changes the value of `T->Elem2No` returned by `ParMesh::GetSharedFaceTransformations`.

The behavior in `master` is to return the "element neighbor index" (starting from 0). The issue with this is that there is no way for the caller to distinguish between a process-local mesh element and a face neighbor mesh element based on this index.

The behavior in this PR is to return the "shifted element index" (i.e. starting from `NumOfElements`), so that callers of method (e.g. integrators) can distinguish between local elements (`index < NumOfElements`) and face neighbor element (`index >= NumOfElements`). The element neighbor index can be recovered simply by subtracting `NumOfElements`.

Closes #1458.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1491](https://github.com/mfem/mfem/pull/1491) | @pazner | @tzanio | @v-dobrev + @tzanio | 05/20/20 | 06/23/20 | 06/27/20 | |

### CODE REVIEW

**Comment by pazner** [comment]
@v-dobrev, you might want to take a look at this. My preliminary tests suggest these changes are OK, but I haven't done comprehensive testing.

**Comment by tzanio** [comment]
@v-dobrev reminder that the review for this PR is due this week.

**Comment by tzanio** [comment]
@v-dobrev -- do you need more time?

**Comment by v-dobrev** [comment]
> @v-dobrev -- do you need more time?

Yes, I'll try to review it this week.

**Comment by v-dobrev** [comment]
LGTM

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
LGTM

**Comment by artv3** [comment]
Hi folks, although this PR introduced a low-level API change in how data is accessed in ``GetFaceNbrElementVDofs`` it might still effect users. It effected the application I work on, a heads up would be nice 👍

**Comment by pazner** [comment]
> Hi folks, although this PR introduced a low-level API change in how data is accessed in `GetFaceNbrElementVDofs` it might still effect users. It effected the application I work on, a heads up would be nice 👍

Legitimate point, and sorry for causing the trouble! We should indeed have a better process for handling "technically breaking" changes like this.

**Comment by v-dobrev** [comment]
I agree -- we should have at least mentioned this in the changelog, even though it is a low-level API change. We should still do that, at least.

If running in debug mode (`MFEM_DEBUG=YES`) the issues caused by this change should trigger an error (out-of-bounds access in the face-neighbor arrays), however, understanding the reason behind the error may not be that obvious. Maybe we can add special check(s) (e.g. using `MFEM_ASSERT`) to catch such out-of-bounds access at the level of `GetFaceNbrElementVDofs` and print a message that points out the API change.

**Comment by artv3** [comment]
Does this change effect the non-zero ordering of the resulting global matrix? We are noticing a slowdown in an application and are looking at recent mfem changes.

**Comment by tzanio** [comment]
My understanding is that it should not have had an effect on the ordering or application performance, but I may be wrong -- @pazner and @v-dobrev, can you confirm?

**Comment by pazner** [comment]
This PR should not have changed element/DOF/nonzero ordering.

**Pull request merged**
