### PR TITLE
Added the gzstream capability to the data collection classes [gzdata-collection-dev]

### PR DESCRIPTION
**Pull request by acfisher**

### CODE REVIEW

**Comment by tzanio** [comment]
@acfisher, is this ready for review?

**Comment by acfisher** [comment]
Yeah, it's a pretty simple one that should be ready to look at.

> @acfisher, is this ready for review?

**Comment by tzanio** [comment]
Thanks @aaroncblack, looks good to me. Should we add as a reviewer one of the users that can test this in their application?

**Comment by acfisher** [comment]
That might not be a bad idea.  I ran a quick test myself and put a unit test in for the capability as well.  We will also need the Visit folks to update their version of MFEM for it to be able to read the compressed files, but there is no change in the uncompressed versions so it's fully backward compatible.

**Comment by tzanio** [comment]
This is a small and self-contained change.

@v-dobrev -- any objections to merge it?

**Pull request merged**
