### PR TITLE
Clarify ODE ImplicitSolve documentation

### LINKED ISSUE #3395: Document and clarify TimeDependentOperator::ImplicitSolve notation
I keep on forgetting doing this.

* Write a clarification that one only needs to implement a backward euler step for `k = f(x + dt k, t)`

### PR DESCRIPTION
**Pull request by jandrej**
Closes #3395

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3443](https://github.com/mfem/mfem/pull/3443) | @jandrej | @pazner | @cjvogl + @bensworth + @v-dobrev | 2/8/23 | ⌛due 2/22/23 | ⌛due 3/1/23 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by v-dobrev** [comment]
Please add the `ready-for-review` label if/when this is ready.

**Comment by pazner** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by cjvogl** [comment]
@jandrej, can you elaborate on what the Newton mention is clarifying?

**Review by cjvogl — CHANGES_REQUESTED** [review]
@jandrej, can you elaborate on what the Newton mention is clarifying? Perhaps I am missing something, but the addition reads to me that `ImplicitSolve` will always implement a Newton approach... is that the clarification?

**Comment by jandrej** [comment]
> @jandrej, can you elaborate on what the Newton mention is clarifying? Perhaps I am missing something, but the addition reads to me that `ImplicitSolve` will always implement a Newton approach... is that the clarification?

The addition should give a hint to the person that implements this method that usually a nonlinear solve is required but it also gives the clarification what the residual and linearization look like (which was not immediately clear to me).

**Review by cjvogl — APPROVED** [review]
Thanks for the wording change!

**Comment by bensworth** [comment]
I think the extra documentation is a good idea, but you have to be careful with mass matrices - should k have a mass matrix and the identity inside be a mass matrix? I am not positive without writing it out more carefully because I usually write out RK methods in a stage value rather than stage derivative formulation, but please check.

Also minor, but I suggest bringing the minus sign inside of the Jacobian. As written, I think you are inverting a negative definite sort of operator (say your problem is linear, then df/du has negative eigenvalues/FOV for stability, and you then subtract I). Because solvers are typically formulated based on assumptions of positivity, swapping the sign to be I - df/du IMO is a more natural way to look at it, and then you also have the form of a standard fixed point iteration, `x_{i+1} = x_i + M^(-1)r_i`.

**Comment by bensworth** [comment]
Also relevant:
https://github.com/mfem/mfem/pull/1602

**Comment by cjvogl** [comment]
To @bensworth's point about the mass matrix, perhaps it is worth noting first that `ImplicitSolve` is for solving
$$\frac{dy}{dt} = g(y,t)$$
whether the $\vec{f}(\vec{z},t)$ in the comments represents $\vec{g}(\vec{z},t)$ in
$$M \frac{d\vec{y}}{dt} =\vec{g}(\vec{y},t)$$
or $M^{-1} \vec{g}(\vec{z},t)$ in
$$\frac{d\vec{y}}{dt} = M^{-1} \vec{g}(\vec{y},t)$$

**Comment by bensworth** [comment]
Good point @cjvogl. If the point of this PR is to make the implicit solve requirements more clear, I would personally vote to pose it in terms of mass matrices, or at least include that formulation as well, because virtually every implicit solve done through MFEM will take that form

**Comment by pazner** [comment]
I think these are good suggestions @bensworth. @jandrej, could you add a note explaining how the mass matrix is typically incorporated (either by including `M^{-1}` in the definition of the right-hand side `f`, or by a (confusingly named) "implicit part" `F(x,k,t) = M k` or similar).

**Comment by acfisher** [comment]
Have all of the concerns been addressed here?  @pazner @bensworth @jandrej @cjvogl

**Comment by pazner** [comment]
I believe this is waiting on https://github.com/mfem/mfem/pull/3443#issuecomment-1470808256

**Comment by acfisher** [comment]
@jandrej Can you address this https://github.com/mfem/mfem/pull/3443#issuecomment-1470808256

**Comment by jandrej** [comment]
As this is apparently more confusing than the previous docs, I'll close the PR.

**Comment by bensworth** [comment]
@jandrej the old documentation is not good in my opinion, addressing https://github.com/mfem/mfem/pull/3443#issuecomment-1470808256 should not be a big task and makes a lot more sense than just dropping the PR altogether

**Comment by cjvogl** [comment]
I agree that the current documentation should be improved.  For a tutorial that I am writing, it took a nontrivial amount of time to re-parse the current documentation and explain things.  This is what I came up with, in case it is useful:
image

**Comment by acfisher** [comment]
@bensworth I asked @cjvogl to use the material he put together for his tutorial to address this.  Stay tuned.

**Comment by cjvogl** [comment]
@jandrej, are you ok if I push changes to this branch/PR or would you prefer I start a new branch/PR?

**Comment by jandrej** [comment]
go ahead

**Comment by cjvogl** [comment]
@jandrej, sorry that I hadn't gotten around to updating my comment here.  I found it useful to expand the clarification to the documentation of `TimeDependentOperator` as a whole... so I started a new PR #4115

**Comment by acfisher** [comment]
@jandrej, I believe this is all being addressed in PR https://github.com/mfem/mfem/pull/4115
Do you want to close this one?

**Pull request closed without merging**
