### PR TITLE
Fix a bug with hybridization on 2D NC meshes

### LINKED ISSUE #1105: Hybridization does not work on NC processor boundaries.
It seems hybridization has never worked correctly on non-conforming interfaces that are at the same time processor interfaces. I tested this as far back as v3.2.

How to reproduce:

1. In `ex4p`, disable all serial and parallel refinement.

2. Run `mpirun -n 4 ex4p -m ../data/amr-quad.mesh -o 2 -hb`. This works because all inter-processor faces happen to be conforming:
ex4p-good

3. When run on a different number of CPUs, some master-slave faces are on processor boundary: `mpirun -n 3 ex4p -m ../data/amr-quad.mesh -o 2 -hb`
ex4p-bad

I could use some help fixing this because I don't know how hybridization actually works...

### PR DESCRIPTION
**Pull request by v-dobrev**
This bug affected 2D NC meshes that are partitioned so that NC faces lie between processors.

I also added a sample run in ex4p that tests such a case.

Resolves #1105.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1564](https://github.com/mfem/mfem/pull/1564) | @v-dobrev | @tzanio | @tzanio + @vladotomov | 06/19/20 | 06/20/20 | 06/22/20 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
LGTM

**Comment by tzanio** [comment]
Thanks for the quick review @vladotomov!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by v-dobrev** [comment]
LGTM

**Comment by tzanio** [comment]
I kept the branch for the additional changes mentioned above. Let me know if you prefer to make those in another branch.

**Pull request merged**
