### PR TITLE
Adding NURBSFECollection::FiniteElementForDim [bugfix/nurbs-fe-coll]

### PR DESCRIPTION
**Pull request by mlstowell**
This PR corrects a bug introduced in PR #3349 which introduced  `FiniteElementCollection::FiniteElementForDim`. This general implementation fails for the NURBS finite element collection because it assumes all finite element spaces will be defined on simplexes.

Rather than make the assumption that all finite element spaces will be defined on tensor product spaces this PR defines an override in the `NURBSFECollection` to handle it as a special case.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3447](https://github.com/mfem/mfem/pull/3447) | @mlstowell | @tzanio | @dylan-copeland + @v-dobrev | 2/6/23 | ⌛due 2/20/23 | ⌛due 2/27/23 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by v-dobrev** [comment]
This is a good catch. The assumption I made in https://github.com/mfem/mfem/pull/3349#discussion_r1039488255 was that all overrides of `FiniteElementCollection::FiniteElementForGeometry` will return `NULL` when there is no specific FE associated with the given `Geometry::Type`. However, this convention is not followed by all `FiniteElementCollection` sub-classes and, instead, some of them generate an error.

Maybe we should update all `FiniteElementCollection` sub-classes to follow the convention of returning `NULL`?
In GLVis, this issue may affect all such sub-classes due to the use of `FiniteElementCollection::GetMapType(int)` (added in https://github.com/GLVis/glvis/pull/249) which, in turn, calls `FiniteElementCollection::FiniteElementForDim`.

What do you think @mlstowell?

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by mlstowell** [comment]
I agree with @v-dobrev that returning NULL from `FiniteElementForGeometry` and `FiniteElementForDim` would be better than calling `mfem_error`. I'll look through the derived classes and see how common this is.

**Comment by mlstowell** [comment]
We seem to have over 20 classes which use the `mfem_error` solution found in the NURBS finite element collection. The H1, L2, RT, and ND collections call `MFEM_ABORT` then return NULL.

If we want to use the NULL value as an indicator that this combination is not supported then we should probably remove all of the calls to both `mfem_error` and `MFEM_ABORT`. If anyone feels the messages are important we could use `MFEM_WARNING` (or something similar) but I'm not sure that's a good idea.

**Comment by IdoAkkerman** [comment]
It is possible to make higher order H(div) and H(curl)  spaces with NURBS. This is actually I would like to work on.
Is RT and ND synonymous with H(div) and H(curl) ?

Perhaps still worth going for a "short" fix as suggested. Just wanted to mention it.
Any ideas on how to progress with  vector bases and NURBS?

**Comment by v-dobrev** [comment]
I proposed an alternative, more general solution in #3503.

**Comment by mlstowell** [comment]
The solution proposed by @v-dobrev in PR #3503 provides a more robust approach which remains backward compatible while resolving potential issues with other finite element spaces (not just the NURBS collection handled as a special case in this PR).

**Comment by tzanio** [comment]
@mlstowell, can we delete this branch?

**Pull request closed without merging**
