### PR TITLE
( Still under development. ) Fix test.mk to propogate error code [travis_retcode_testing]

### PR DESCRIPTION
**Pull request by aaroncblack**
Submitting PR to get Travis to run

### CODE REVIEW

**Comment by aaroncblack** [comment]
Updated test.mk to return error code for each test execution.  Update travis yaml file to run make, and make test/check in one line so that it catches the return code.  If these are on separate lines, it only checks the return of the last command executed.

**Comment by v-dobrev** [comment]
There is still an issue with travis not reporting failures, e.g. in the 257.6 job in [build 257](https://travis-ci.org/mfem/mfem/builds/215738125).

Also, the MPI builds on Mac are failing due to some long names - any ideas how to fix those?

**Comment by aaroncblack** [comment]
@v-dobrev - The long path issue appears to be a known issue on Macs.  Workaround on the OpenMPI webpage is to set the temp dir to a shorter path.

I'll add that in the env section for MPI builds, after I figure out how to get Travis to report those failures.

**https://www.open-mpi.org/faq/?category=osx#startup-errors-with-open-mpi-2.0.x**

> On some versions of Mac OS X / MacOS Sierra, the default temporary directory location is sufficiently long that it is easy for an application to create file names for temporary files which exceed the maximum allowed file name length. With Open MPI v2.0.x, this can lead to errors like the following at application startup:
> 
> shell$ mpirun ... my_mpi_app
> PMIx has detected a temporary directory name that results
> in a path that is too long for the Unix domain socket:
>  
>     Temp dir: /var/folders/mg/q0_5yv791yz65cdnbglcqjvc0000gp/T/openmpi-sessions-502@anlextwls026-173_0/53422
>  
> Try setting your TMPDIR environmental variable to point to
> something shorter in length.
> 
> The workaround for the Open MPI 2.0.x and v2.1.x release series is to set the TMPDIR environment variable to /tmp or other short directory name.

**Comment by aaroncblack** [comment]
This update causes testing to abort after the first test.  I pulled a fresh branch and this isn't the current behavior( as @tzanio mentioned to me today ).

I'll update the test.mk to solve this a different way.  One solution would be to set an environment variable TEST_FAILED=0 and if any tests failed, set it to 1.  Then call exit ($TEST_FAILED).

**Comment by aaroncblack** [comment]
Closing this PR.  It was based off the wrong branch.

**Pull request closed without merging**
