### PR TITLE
Switch from LGPL-2.1 to BSD-3 [bsd-relicense]

### PR DESCRIPTION
**Pull request by tzanio**
- Updated LICENSE, README, CHANGELOG and CONTRIBUTING.md
- Removed COPYRIGHT, added NOTICE
- Updated the headers in all source files, makefiles, etc.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1315](https://github.com/mfem/mfem/pull/1315) | @tzanio | @tzanio | @acfisher + @jandrej | 02/23/20 | 03/02/20 | 03/04/20 | |

### CODE REVIEW

**Comment by tzanio** [comment]
> Files still mentioning MFEM being licensed under LGPL
> 
> * `config/user.cmake`
> * `config/user.mk`
> * `build/config/_config.hpp` (the template for this and some other build system generated files probably)

I think these may be your local files, they are not part of the repo :)

> What happens to gzstream? It is licensed under LGPL. Are we allowed to distribute it in a BSD licensed repo?

This is a tricky one. @markcmiller86, is gzstream available under BSD-friendly licence by any chance? If not, is it available as an external library that we can link to?

> Catch is distributed under "Boost Software License 1.0". I don't know what it means, but we should make sure that we are allowed to include the catch header in this repo.

This is probably compatible with BSD-3. Can you check?

**Comment by jandrej** [comment]
> > Files still mentioning MFEM being licensed under LGPL
> > 
> > * `config/user.cmake`
> > * `config/user.mk`
> > * `build/config/_config.hpp` (the template for this and some other build system generated files probably)
> 
> I think these may be your local files, they are not part of the repo :)

Doh.gif 🤦‍♂

**Comment by markcmiller86** [comment]
> This is a tricky one. @markcmiller86, is gzstream available under BSD-friendly licence by any chance? If not, is it available as an external library that we can link to?

Hmmm....I looked and no, I didn't find any other licenses for it. It dates back to 2003 AFAIKT. I looked for some alternatives too. One option is potentially [Boost zip filters](https://www.boost.org/doc/libs/1_68_0/libs/iostreams/doc/classes/gzip.html). The penality is a potentially *large* dependency.

Another possible option...make gzstream optional (I think it already is) and if users enable it, require them to attest to acceptance (or not) of the LGPL license for it during the configuration step. Not sure how practical that is.

**Comment by tzanio** [comment]
> > > Catch is distributed under "Boost Software License 1.0". I don't know what it means, but we should make sure that we are allowed to include the catch header in this repo.
>>
> > This is probably compatible with BSD-3. Can you check?
>
> It seems it is, but I'm not sure.

Based on https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#General_comparison, https://en.wikipedia.org/wiki/Boost_(C%2B%2B_libraries)#License and my reading of https://github.com/catchorg/Catch2/blob/Catch1.x/LICENSE.txt I think we can include it in MFEM after the relicensing.

@Follett2 -- can you confirm that this is correct (including a header licensed under "Boost Software License 1.0" into a BSD-3 library)?

@acfisher -- why does the file `tests/unit/LICENSE_1_0.txt` look like HTML, shouldn't it be a copy of https://github.com/catchorg/Catch2/blob/Catch1.x/LICENSE.txt?

**Comment by acfisher** [comment]
@tzanio Yes it should be the text version.  I must have copy pasted it from a webpage and got all of the html formatting somehow.  I'll fix that.

**Comment by tzanio** [comment]
It looks like the `gzstream` is available in library form here: http://www.cs.unc.edu/Research/compgeom/gzstream.

Maybe the simplest solution will be to just remove the `general/gzstream.?pp` files and replace them with linking to this library?

**Comment by markcmiller86** [comment]
> Maybe the simplest solution will be to just remove the `general/gzstream.?pp` files and replace them with linking to this library?

Its slightly more complicated than that because I modified the gzstream classes a bit to
   * Integrate more naturally within MFEM namespace
   * Modified to use char *mode for constructors/open instead of int
   * Changed bufferSize from 47+256 to 8192 (8 kilobytes)
   * Added simple factories ifgzstream/ofgzstream to create either gz[o|i]stream or std::[o|i]fstream and, consequently, to build with or without zlib

So, you'd want to have a packaged version of the MFEM-friendly version of gzstream somewhere for user's to optionally download and easily install. Then, yes, you could just link to it.

**Comment by markcmiller86** [comment]
FYI...I've concluded I created a [similar problem in VisIt](https://github.com/visit-dav/visit/issues/4432)

**Comment by jandrej** [comment]
@markcmiller86 this sounds like a plan. Let me know If you need any assistance.

**Comment by tzanio** [comment]
@acfisher, @jandrej and @markcmiller86 -- can you work together to remove the `gzsteam.hpp` and `gzstream.cpp` files and replace them with linking to an external library?

Note that:

1) The current `MFEM_USE_GZSTREAM` variable should be renamed to `MFEM_USE_ZLIB`, so that could be used e.g. in https://github.com/mfem/mfem/blob/master/fem/datacollection.cpp#L912

2) This portion of the `CHANGELOG` needs to be updated: https://github.com/mfem/mfem/blob/master/CHANGELOG#L187-L191

3) The overall change to external gzstream needs to be mentioned in the `CHANGELOG`

4) If we can't use the official gzstream library, maybe Mark can have a LGPL version of it with his changes that we point to?

**Comment by jandrej** [comment]
@tzanio I'm currently integrating [zstr](https://github.com/mateidavid/zstr) as a replacement for gzstream.

**Comment by acfisher** [comment]
@tzanio We are on it.  We didn't want to wait until the external library was pulled out and set up so we found a a simple zlib header only wrapper that we are dropping in it's place that will work for all of our needs by linking directly to zlib.   I cleared this plan with Charity so no issues there.  Julian is almost done with the code transition and I'll make sure all the boxes get checked for the review.

**Comment by tzanio** [comment]
Thanks guys!

**Comment by jandrej** [comment]
The changes from gzstream to zstr included a rename from "named_ifgzstream" to "named_ifzstream". This needs a companion PR in glvis, since this function is used there.

**Comment by v-dobrev** [comment]
> The changes from gzstream to zstr included a rename from "named_ifgzstream" to "named_ifzstream". This needs a companion PR in glvis, since this function is used there.

Why not keep the old name? The change may have effect beyond GLVis.

**Comment by jandrej** [comment]
My intention was to distinguish from the previously used gzstream library. Maybe the comment about the interface not changing is wrong. `named_ifzstream` can be interfaced in the same way as `named_ifgzstream`. But for example
```c++
    const char *mode = (compression) ? "zwb6" : "w";
    ofgzstream mesh_file(mesh_name.c_str(), mode);
```
vs.
```c++
    mfem::ofzstream mesh_file(mesh_name, compression);
```
shows that ofzstream is different. The second argument now takes a bool instead of a string.

**Comment by markcmiller86** [comment]
> ```c++
>     const char *mode = (compression) ? "zwb6" : "w";
> ```

that mode string was something I added to `gzstream` when I integrated into MFEM. The `z` means to compress, the `6` is gzip `level`. The other chars are normal sec. 2 I/O `open()` mode chars.

**Comment by acfisher** [comment]
Hmm, I think it's a good idea to revert the name back to the original for now since that is part of our interface.  If we want to change the interface we can discuss that later..

**Comment by tzanio** [comment]
This is good to go in my opinion. Thank you @jandrej for jumping in and adding the gzstream replacement so quickly!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Re-merged in `next` for testing ...

**Comment by acfisher** [comment]
:tada::tada::tada:

Thanks @jandrej for the list minute zlib transition.

**Comment by tzanio** [comment]
You guys both were awesome... I'm really happy how smooth and quick the process was!

**Pull request merged**
