### PR TITLE
Guard add_test calls with MFEM_ENABLE_TESTING

### PR DESCRIPTION
**Pull request by white238**
This came up in Serac where we are optionally using MFEM as a submodule and our CMake build system uses `add_subdirectory` to speed up co-development builds.

During our default development workflow, we do not want to build MFEM's examples or tests directly. However,  without this change, MFEM's tests are added to Serac's tests but they are not being built, which causes our tests to fail.

This PR guards all `add_test` calls with your already existing option `MFEM_ENABLE_TESTING`.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2631](https://github.com/mfem/mfem/pull/2631) | @white238 | @v-dobrev | @jandrej + @jwang125 | 11/06/21 | 11/22/21 | 12/07/21 | |

### CODE REVIEW

**Comment by kennyweiss** [comment]
Thanks @white238 !  

We're seeing the same problem in a library that I work on (`tribol`), which also has a CMake-based build system and uses mfem as a submodule.

**Comment by tzanio** [comment]
@white238, when this is ready please mark with `ready-for-review`, see https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#quick-summary

**Comment by v-dobrev** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by kennyweiss — APPROVED** [review]
Thanks @white238!

**Review by jandrej — APPROVED** [review]

**Review by jwang125 — COMMENTED** [review]
Compiles successfully.

**Review by jwang125 — APPROVED** [review]

**Comment by v-dobrev** [comment]
Merged in `next` for testing...

**Pull request merged**
