### PR TITLE
More threads/block for SmemPADiffusionApply3D

### PR DESCRIPTION
**Pull request by tomstitt**
~~Flip the inner loops so we can thread in z without atomics.~~ see comment below

This change has been tested in our code and passes all our regression tests.

### CUDA Results

CEED ex1 results on 1 V100:
```
./go.sh -c lassen -m xlc -p 1 -n 1 -r ./tests/mfem_ex1/ex1.sh mfem_branch=<> mfem_devs=cuda problem=1
```
|master | this branch|
|---------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|
| cuda_master | cuda_branch |

### AMDGPU Results
CEED ex1 results on 1 MI100:
```
# modified the corona config a little
./go.sh -c corona -m hip -p 1 -n 1 -r ./tests/mfem_ex1/ex1.sh mfem_branch=<> mfem_devs=hip problem=1
```
|master | this branch|
|---------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------|
| hip_master | hip_branch |

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2638](https://github.com/mfem/mfem/pull/2638) | @tomstitt | @tzanio | @camierjs + @artv3 + @YohannDudouit | 11/06/21 | 11/10/21 | 11/11/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by YohannDudouit** [comment]
Hi @tomstitt , this looks really good, I see that you use a different threading strategy to improve the performance, I don't really understand your reference to "atomics", can you elaborate what you mean by  "Flip the inner loops so we can thread in z without atomics."

**Comment by tomstitt** [comment]
> Hi @tomstitt , this looks really good, I see that you use a different threading strategy to improve the performance, I don't really understand your reference to "atomics", can you elaborate what you mean by "Flip the inner loops so we can thread in z without atomics."

Hey @YohannDudouit , yes, sorry for the minimal notes, that was a comment to myself since I had tried another threading strategy that did involve atomics, I'm going to strike it since it isn't at all clear...

There are a few blocks that look like this next snippet and at first I thought we could add threads in z doing the following:

```
double u[D1D], v[D1D];
MFEM_UNROLL(MD1)
for (int dz = 0; dz < D1D; dz++) { u[dz] = v[dz] = 0.0; }  ////// thread in z
MFEM_UNROLL(MD1)
for (int dx = 0; dx < D1D; ++dx)    ////// thread in z
{
   const int i = qi(qx,dx,Q1D);
   const int j = dj(qx,dx,D1D);
   const int k = qk(qx,dx,Q1D);
   const int l = dl(qx,dx,D1D);
   const double s = sign(qx,dx);
   MFEM_UNROLL(MD1)
   for (int dz = 0; dz < D1D; ++dz)
   {
      const double coords = X[dz][dy][dx];
      u[dz] += coords * B[i][j];
      v[dz] += coords * G[k][l] * s;
   }
}
MFEM_UNROLL(MD1)
for (int dz = 0; dz < D1D; ++dz)  ////// thread in z
{
   DDQ0[dz][dy][qx] = u[dz];  ////// atomic add into DDQ0
   DDQ1[dz][dy][qx] = v[dz];  ////// atomic add into DDQ0
}
```
But instead we can just move the `for (dz = 0 to D1D)` loop to the outside (and by "Flip the inner loops" I meant that we flip the ordering of the middle loop in the snippet above so that `for (dz = 0 to D1D)` is outside of `for (dx = 0 to D1D)` instead of inside) and and get this PR:

```
MFEM_FOREACH_THREAD(dz,z,D1D)
{
   double u = 0.0, v = 0.0;
   MFEM_UNROLL(MD1)
   for (int dx = 0; dx < D1D; ++dx)
   {
      const int i = qi(qx,dx,Q1D);
      const int j = dj(qx,dx,D1D);
      const int k = qk(qx,dx,Q1D);
      const int l = dl(qx,dx,D1D);
      const double s = sign(qx,dx);
      const double coords = X[dz][dy][dx];
      u += coords * B[i][j];
      v += coords * G[k][l] * s;
   }

   DDQ0[dz][dy][qx] = u;
   DDQ1[dz][dy][qx] = v;
}

**Comment by camierjs** [comment]
It looks great -  good if all the regression tests are passing too: thank you @tomstitt !

**Review by camierjs — APPROVED** [review]

**Review by YohannDudouit — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
