### PR TITLE
[CEED] Fix the libCEED integration in MFEM due to the interface change.

### PR DESCRIPTION
**Pull request by YohannDudouit**
This PR fixes the integration of libCEED in MFEM due to recent interface change in libCEED.

| PR | Author | Editor | Reviewers  | Assignment | Approval | Merge |
| --- | --- | --- | ---  | --- | --- | --- |
| https://github.com/mfem/mfem/pull/1285 | @YohannDudouit  | @tzanio | @tzanio + @camierjs | 02/09/20 | 02/09/20 | ⌛due 02/16/20 |

### CODE REVIEW

**Comment by camierjs** [comment]
Seems to work fine for me! Thank you for proposing this PR so quickly!

**Comment by tzanio** [comment]
Merged in `next` for testing ...

**Comment by tzanio** [comment]
@camierjs + @YohannDudouit, please take a look at tonight's regression tests on [tux426](https://mybitbucket.llnl.gov/projects/MFEM/repos/autotest/commits/95c7cd06b13cba1e1f54ab3b011f6393c30402c9#tux426/2020-02-10-llnl-gh-next/autotest.log) and [tux429](https://mybitbucket.llnl.gov/projects/MFEM/repos/autotest/commits/d9a74232872dcfaa0a6ae6742d4f881d8d30dc0a#tux429/2020-02-10-github-next/sample-runs-devices-tux429.diff) for potential issues in this PR.

**Comment by v-dobrev** [comment]
@YohannDudouit, in the `INSTALL` file we mention the minimal git-hash of libCEED that is required by MFEM -- can you update that git-hash as well?

**Pull request merged**
