### PR TITLE
Euler & Compressible Navier-Stokes calculations. [cns-dev]

### PR DESCRIPTION
**Pull request by vikramsg**
Adding Euler and CNS calculations.

The example cns2d.cpp calculates the smooth density and Taylor Green Vortex problems for 2D calculations. This only does serial calculations. 

The change required for this implementation was to add interior face capabilities in the linear form since the face integrator is of non-linear form. A DGEulerIntegrator was added which allows this capability. At each time step b->Assemble needs to be called. 

EDIT: Sorry, I didn't understand how to put a pull request to a new branch.

### CODE REVIEW

**Comment by vikramsg** [comment]
Modified linearform to assemble for interior face, plinearform to assemble shared faces, pgridfunc to add GetVectorValue and added cns2dp.cpp to do CNS in 2D in parallel. Validated against serial version.

**Comment by vladotomov** [comment]
Hi Vikram, do you think this is ready for review or are you planning to do additional improvements?

**Comment by vikramsg** [comment]
Hi Vladimir, 

I think this is ready for review for now. I plan to add additional features, but I think this is the correct baseline to make sure that things work. 

My initial aim was to do 2D CNS in serial and parallel and that is now done. 

Right now it only does periodic problems and 2D. I want to eventually do 3D and other boundary conditions. But for now I want to see how variable order DG can be implemented.

**Comment by jdahm** [comment]
Hi Vikram, this is a great start! I'm going to work on this request in the hydro-dev branch of this repository. Over the weekend I started by adding support for face-based NonlinearFormIntegrators. Feel free to give me comments on it.

**Comment by vikramsg** [comment]
Actually I have a fully working 3D solver now with various boundary conditions. 

I can see the non-linear form you added. I had done something similar but I had kept it in the linear form just for convenience. You can have a look if you want. Boundary conditions etc were on similar lines.

**Comment by tzanio** [comment]
Hi @vikramsg,

Given that we added an Euler example in mfem-3.3.2 (example 18), I'm inclined to close this pull request.

Do you agree?

Are there parts of it that you'd like to preserve (maybe in a separate PR)?

Tzanio

**Comment by vikramsg** [comment]
Yes, you can close it.

**Pull request closed without merging**
