### PR TITLE
Adding a parallel inner product to ParLinearForm and ParGridFunction [lf-inner-product-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
These changes allow one to compute the integral of a parallel grid
function over the entire domain by computing its inner product with a
parallel linear form.

Without these additions such an inner product would compute different
values on each processor.

### CODE REVIEW

**Comment by tzanio** [comment]
Mark, what's the use case for this inner product?

Typically for grid functions one will use an integral inner product (i.e. with a mass matrix)...

**Comment by mlstowell** [comment]
I agree that taking such an inner product of two grid functions is typically meaningless without a mass matrix.  However, I'm mainly interested in products involving one grid function and one linear form.  This treats the linear form as a linear functional which maps grid functions to real numbers.

In the bloch-wave-dev branch this is used in two very closely related ways.  The easiest to explain is the process of computing the coefficients of a Fourier series.  Say you have a scalar valued grid function and you want to compute the first few terms of its Fourier expansion.  By building linear forms with appropriate sine or cosine coefficients you can compute the Fourier coefficients by taking the inner product of the grid function with these linear forms.  In my particular use case I have several grid functions whose Fourier coefficients I need to compute so it makes sense to build these linear forms and use them several times.

**Comment by mlstowell** [comment]
I think the way I implemented this might be the safer option.  Many of our codes use the mfem::Vector type when the contents could more accurately be considered a LinearForm, GridFunction, HypreParVector, etc.. and the Vector class already has this inner product which functions in serial.  If we override this with an inner product that takes a ParGridFunction argument but the developer writes "v1 * v2" where v1 is a ParLinearForm but v2 is an mfem::Vector then Vector::operator*(const Vector&) would be called rather than ParLinearForm:operator*(const ParGridFunction&).  This will compile and run without complaint but the results won't be what the developer hoped for.

It might be a good idea to also add a ParLinearForm::operator*(const ParGridFunction&) method to avoid the conversion you mention (and also ParGridFunction::operator*(const ParLinearForm&)) but I think we still need the methods with Vector arguments.

**Comment by mlstowell** [comment]
Upon further consideration I don't think any conversions are necessary when calling ParLinearForm::operator*(const Vector &) because ParGridFunction already is a Vector.  Or am I missing something...

**Comment by tzanio** [comment]
It is just a question of (semantic) clarity, i.e. inner product makes sense either as a linear algebra operation between two `Vector`s, or as a finite element operation between a `GridFunction` (primal dof vector) and a `LinearForm` (dual dof vector, i.e. primal dof vector times a mass matrix).

Other combinations, while possible, don't make "mathematical sense", but I don't see a good way to block them, so maybe the PR is OK as it is...

It is a minor point.

**Comment by mlstowell** [comment]
Part of me would like to discourage people from using operator* for local products because I worry that it can be misused more often than not.  However, there may be legitimate uses that I'm not thinking of so, if we do add some warnings (at least to the comments), we should leave them as they were.

The idea of creating new methods to perform these products is a good one.  It would let us explicitly state what the method should be used for.  Linear forms are linear functionals which map grid functions to real numbers so we could name the method Map or Apply, or (my favorite) we could define it as "double operator(const GridFunction &) const".  This last one really shows that this object is a linear functional.

**Comment by v-dobrev** [comment]
I agree that `double operator(const GridFunction &) const` will be a cool notation.

On the other hand, it may be confusing to people that are not that familiar with the math side of FEM, so something more explicit (like `InnerProduct` or `Dot` or `DotProduct`) will be more expressive to more people. That said, I'm not strongly opposed to other names.

**Comment by mlstowell** [comment]
The trouble with InnerProduct or Dot is that they are synonymous with *.  So people might expect them to perform the same operation as operator*.

**Comment by v-dobrev** [comment]
How about `ParInnerProduct`, `ParDot`, or `ParDotProduct` to explicitly suggest that this is the parallel version. We can even add this to class `Vector` (with an additional `MPI_Comm` parameter) without creating confusion.

**Comment by mlstowell** [comment]
OK, I'll do that.  Thanks!

**Comment by mlstowell** [comment]
I decided to do something a little different after noticing the solution used for HypreParVectors.  In this case the inner product is defined as a stand-alone function called "InnerProduct".  So I thought it would be more consistent to define two stand-alone InnerProduct functions for Vectors as well.  One of these takes an MPI_Comm argument and computes the global inner product the other computes separate local inner products.

I removed any new overloads of the operator\* methods but added operator()(const GridFunction&) methods to LinearForm and ParLinearForm instead.  This will provide the functionality that I need with a syntax that is more natural.

**Comment by v-dobrev** [comment]
@tzanio, @mlstowell,
I think this is ready. If you agree, add :+1:. When all agree, we can proceed.

**Pull request merged**
