### PR TITLE
Remove deprecated OpenMP support [noomp-dev]

### PR DESCRIPTION
**Pull request by jdahm**

### CODE REVIEW

**Comment by tzanio** [comment]
I am having second thoughts about this -- do we really want to remove this (maybe some users are using it) or do we just want to document better how limited it is and maybe keep the option to expand it in the future?

**Comment by camierjs** [comment]
I'd like to wait a little: I just used it while turning some code into kernels.
Having these pragma are helpful for that.

**Comment by jdahm** [comment]
This pull request to remove the existing pragmas and option was created so that new more specific OpenMP options could be added in the future. For instance, an option to add OpenMP to element block building such as this, or matrix-free execution on a device, etc. Maybe the existing option could be renamed to make its limited scope clear to the user?

**Comment by tzanio** [comment]
> Maybe the existing option could be renamed to make its limited scope clear to the user?

I'm OK with that. My concern was more about removing without have a clear/better alternative. If better OpenMP is available e.g. via the okina branch, then we can clean this and ask users to "upgrade".

**Comment by jdahm** [comment]
This was addressed in #780.

**Pull request closed without merging**
