### PR TITLE
Performance fix with essential dofs in BlockNonlinearForm

### PR DESCRIPTION
**Pull request by jandrej**
This PR changes the behavior of BlockNonlinearForm to finalize the sparsity patterns of the local sub-matrices before eliminating essential degrees of freedom.

Depending on the amount of essential dofs, this increases performance by about 10x for most of my use cases.

There is another performance "bug" hiding in the elimination loop, but I think the present change is more significant.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1550](https://github.com/mfem/mfem/pull/1550) | @jandrej | @v-dobrev | @jakubcerveny + @psocratis | 06/15/20 | 07/07/20 | 07/15/20 | |

### CODE REVIEW

**Comment by psocratis** [comment]
@jandrej Can you suggest a sample run for us to check?

**Comment by tzanio** [comment]
ping: @jakubcerveny

**Comment by jandrej** [comment]
LGTM

**Comment by v-dobrev** [comment]
LGTM

**Comment by v-dobrev** [comment]
This can be optimized more substantially by using a single call to `EliminateCols` instead of the multiple calls to `EliminateCol`. Since we are using row-wise storage in `SparseMatrix`, both of these methods have to go through all rows to find all places where a column is present. That's why the complexity of both methods is similar, however, `EliminateCol` has to be called multiple times (once for each column we want to eliminate).  Of course, this will be much more noticeable for larger problems.

Eventually, we should switch to `EliminateCols` but for now, the improvement from this branch may be sufficient.

**Comment by v-dobrev** [comment]
Merged in `next` for testing...

**Comment by v-dobrev** [comment]
Merged in `next`.

**Pull request merged**
