### PR TITLE
Add support for pyramid elements in Gmsh meshes

### PR DESCRIPTION
**Pull request by sebastiangrimberg**
This PR uncomments the blocks from #1571 to allow for reading of pyramid elements in Gmsh meshes, in light of upgrades introduced in #2400. It also adds a correction to `ParMesh` for parallel meshes with pyramid elements.

Pyramids are still limited to the lowest-order case, so this will fail if the user specifies a Gmsh mesh with pyramid elements with > 5 vertices. Additionally, it will fail if the user tried to construct a high-order FE space on the mesh. ~~For this reason, I've marked the PR as WIP as it may not be worth merging these changes until the arbitrary-order case is supported for pyramids.~~ Since arbitrary-order pyramid elements may take a while to be added to MFEM, this small PR is ready to be reviewed for merging.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2980](https://github.com/mfem/mfem/pull/2980) | @sebastiangrimberg | @tzanio | @bslazarov + @mlstowell | 1/21/23 | 1/27/23 | 2/3/23 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by mlstowell — APPROVED** [review]

**Comment by bslazarov** [comment]
How can I test the new capability?

**Comment by sebastiangrimberg** [comment]
> How can I test the new capability? Is there any gmsh mesh with pyramid elements available in the data directory?

Hi @bslazarov, here are two Gmsh v2 mesh versions of `ref-pyramid.mesh` and `octahedron.mesh` that you can use for testing. Thanks!

[mesh.zip](https://github.com/mfem/mfem/files/10501471/mesh.zip)

**Comment by bslazarov** [comment]
> > How can I test the new capability? Is there any gmsh mesh with pyramid elements available in the data directory?
> 
> Hi @bslazarov, here are two Gmsh v2 mesh versions of `ref-pyramid.mesh` and `octahedron.mesh` that you can use for testing. Thanks!
> 
> [mesh.zip](https://github.com/mfem/mfem/files/10501471/mesh.zip)

Thank you! The new additions seems to work fine. However, I discovered a memory leak in the mesh refinement with pyramid elements:

==1747452== 40 bytes in 1 blocks are definitely lost in loss record 4 of 4
==1747452==    at 0x483BE63: operator new(unsigned long) (vg_replace_malloc.c:344)
==1747452==    by 0x2D24EA: mfem::Mesh::UniformRefinement3D_base(mfem::Array<int>*, mfem::DSTable*, bool) (mesh.cpp:8625)
==1747452==    by 0x3BD2DA: mfem::ParMesh::UniformRefinement3D() (pmesh.cpp:4602)
==1747452==    by 0x2D74B6: mfem::Mesh::UniformRefinement(int) (mesh.cpp:9406)
==1747452==    by 0x172FC1: main (ex0p.cpp:44)

It seems to be unrelated to the current PR.

**Review by bslazarov — APPROVED** [review]
New issue is submitted for the memory leak in mesh refinement with pyramids

**Comment by tzanio** [comment]
Should we mention this in `CHANGELOG`?

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by sebastiangrimberg** [comment]
> Should we mention this in `CHANGELOG`?

[caa1e2c](https://github.com/mfem/mfem/pull/2980/commits/caa1e2c7ae280e3bbd3f0db267257e37f1646bff)

**Review by tzanio — APPROVED** [review]
Thanks for the contribution @sebastiangrimberg !

**Pull request merged**
