### PR TITLE
Added method to Mesh to prune extra specified vertices

### PR DESCRIPTION
**Pull request by stefanozampini**
PETSc currently sends data to glvis without taking care of the number of vertices specified in the mesh
This can generate some issues when reading H1 gridfunctions, since the number of vertex dofs is taken directly from Mesh::GetNV()

### CODE REVIEW

**Comment by v-dobrev** [comment]
Hi @stefanozampini,

There is already a method - `Mesh::RemoveUnusedVertices()` - that does the same thing as `Mesh::PruneExtraVertices()`. Or, is the new method different?

**Comment by stefanozampini** [comment]
Oh, I missed that method. I guess I can use that one. I would like to add that method to FinalizeTopology. Are you OK with that?

**Comment by v-dobrev** [comment]
`Mesh::FinalizeTopology()` may not be the right place to call `Mesh::RemoveUnusedVertices()` since the latter assumes the vertices or the nodes are defined. It may be better to call it at the end of `Mesh::Finalize()` or simply after the mesh is read or fully constructed.

**Comment by stefanozampini** [comment]
@v-dobrev , I've added a call to RemoveUnusedVertices at the end of ReadMFEMMesh(), just to fix the visualization issue I had with PETSc solutions and non-conforming grids

**Comment by v-dobrev** [comment]
I'm not sure I like this solution of your problem - if PETSc is writing the data wrong, why fix this in MFEM and not in PETSc?

Another reason I don't like this, is that now, if I save a mesh with an extra vertex from MFEM, then I cannot read it back correctly.

Is it hard to solve this issue in PETSc?

**Comment by stefanozampini** [comment]
No, it's not hard to fix it on the PETSc side. However, extra vertic

**Comment by stefanozampini** [comment]
Sorry, fat fingers and typing from my smartphone. Anyway, it's not hard to fix it from the PETSc side. However, if a mesh has extra vertices, the grid functions are not properly handled, as the number of H1 dofs (for example) depends on Mesh::numVertices.

**Comment by stefanozampini** [comment]
So? what do you want to do with this? You cannot represent GridFunctions properly when a mesh has extra vertices, so I believe this should go in. What do you think?

**Pull request merged**
