### PR TITLE
Copy Nodes GridFunction in trimmer mini app [trimmer-nodes-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
This PR addresses issue #2177 following suggestions from @kmittal2 and @psocratis.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2179](https://github.com/mfem/mfem/pull/2179) | @mlstowell | @tzanio | @kmittal2 + @psocratis | 04/15/21 | 04/15/21 | 04/20/21 | |

### CODE REVIEW

**Comment by mlstowell** [comment]
@sebastiangrimberg , I'd appreciate it if you could test the modified `trimmer` with your meshes to make sure it works as expected.

**Comment by sebastiangrimberg** [comment]
@mlstowell Looks to work perfectly fine to me, thanks!

**Review by kmittal2 — APPROVED** [review]

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by sebastiangrimberg — APPROVED** [review]

**Review by psocratis — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Review by tzanio — APPROVED** [review]
Thanks @mlstowell !

On a side note: should we add `Trimmer` to the web page?

**Pull request merged**
