### PR TITLE
Add backtrace to the mfem_error function

### PR DESCRIPTION
**Pull request by martemyev**
The backtrace is printed if it's a Linux OS,
and helps to figure out where the error is
coming from.

### CODE REVIEW

**Comment by martemyev** [comment]
Also, I modified the comment in the `mfem_error` function.

**Comment by tzanio** [comment]
I think this can be very useful for the developers. Do you know how portable it is?

**Comment by tanderson92** [comment]
According to the backtrace(3) man page, these are all GNU extensions, so this PR is necessarily limited to GNU/Linux. Using a library like libunwind is more portable and the code will be quite similar, but that would introduce an additional external library dependency (though maybe only when MFEM_DEBUG=YES).

**Comment by tanderson92** [comment]
I rewrote the pull request using libunwind for portability. I also added some ability to demangle the function names to print out the exact function prototype called. This could be useful, since it tells you the types that the functions were called with. It's more informative. I compare them below, where I inserted a mfem_error() call into CGSolver::Mult() just to test. Which is (1) more portable (2) presents the user more readable error output ? :)

Just note that I can't get the module information (the "./ex1" from backtrace() output) with libunwind. If someone knows how, I'd love to see it, but I don't think it is essential.

Using backtrace():
`./ex1(_ZN4mfem10mfem_errorEPKc+0x4f) [0x48499f]
./ex1(_ZNK4mfem8CGSolver4MultERKNS_6VectorERS1_+0x5e1) [0x4b2741]
./ex1(_ZN4mfem3PCGERKNS_8OperatorERNS_6SolverERKNS_6VectorERS5_iidd+0x1be) [0x4b2afe]
./ex1(main+0xb4f) [0x47f86f]
/lib64/libc.so.6(__libc_start_main+0xfc) [0x2aaaad3ced5c]
./ex1() [0x47ec58]
`

Using libunwind:
`(mfem::CGSolver::Mult(mfem::Vector const&, mfem::Vector&) const+0x5e1) [0x4b2741]
(mfem::PCG(mfem::Operator const&, mfem::Solver&, mfem::Vector const&, mfem::Vector&, int, int, double, double)+0x1be) [0x4b2afe]
(main+0xb4f) [0x47f86f]
(__libc_start_main+0xfc) [0x2aaaad3ced5c]
(_start+0x28) [0x47ec58]
`

The patch is attached. You need to link with -lunwind and to compare to Mikhail's you should use -rdynamic. That's another advantage: you don't need to add all symbols to the dynamic symbol table.

[libunwind.patch](https://github.com/mfem/mfem/files/426151/libunwind.txt)

**Comment by tanderson92** [comment]
Another followup comment: why are you printing the backtrace only if you are printing a message? Shouldn't this logically be outside the if (msg) {} block ?

**Comment by tanderson92** [comment]
I cleaned up things a bit and tested on some other compilers, since __cxa_demangle is not standard c++. You can find a more or less final version in a commit on my fork: https://github.com/mfem/mfem/commit/7bc8955f4320ac176b8151fd6f2e99eae828d339

I guess it's up to @tzanio what he wants to do here.

**Comment by tzanio** [comment]
Thanks for investigating this @tanderson92!

@martemyev, @v-dobrev and @jakubcerveny what do you think?

**Comment by v-dobrev** [comment]
I tried both branches and I liked the one using `libunwind` better - because of the portability (I tried linux and mac) and the de-mangling. By the way, on my mac, I had to remove `-lunwind` from `LIBUNWIND_LIB`, i.e. leave it empty.

**Comment by tanderson92** [comment]
@v-dobrev I don't have access to a mac which can compile the full mfem library but a minimal testcase indicates you are seeing something like this, with clang. Can you confirm?

`ld: library not found for -lunwind`

The linker is able to figure things out when no such flag is passed. I'm not too familiar with the mac toolchain so I don't have any insight here.

**Comment by v-dobrev** [comment]
@tanderson92, yes on mac there is no library `libunwind.a`, so I got an error message like the one you mentioned. However, removing `-lunwind` from the command line resolves the issue - probably because `libunwind` is part of some system library.

Anyway, this is easy to fix in `config/defaults.mk`, so it's not a problem.

**Comment by tanderson92** [comment]
This is fixed in 5e1ad496e40c27c7d26e944687707260a75e0b3a, as you suggest.

**Comment by tzanio** [comment]
@tanderson92, can you also issue a PR, so we can contrast and compare?

**Comment by tzanio** [comment]
@martemyev, will https://github.com/mfem/mfem/pull/82 work for you if we decide to go with that instead?

**Comment by martemyev** [comment]
Hi Tzanio,
Yes, of course.

Cheers,
Mikhail

**Comment by tzanio** [comment]
Reviewing internally... stay tuned

**Comment by v-dobrev** [comment]
Closing in favour of #82.

**Pull request closed without merging**
