### PR TITLE
Fix for linear/bilinear form domain integrators with markers

### LINKED ISSUE #2646: Possible issue with BilinearForm::AddDomainIntegrator with marker
I ran into an issue using a mesh with non-contiguous domain attribute tags and think the culprit is this check in `BilinearForm::Assemble`:

```
 if (domain_integs_marker[k] != NULL)
 {
    MFEM_VERIFY(mesh->attributes.Size() ==
                domain_integs_marker[k]->Size(),
                "invalid element marker for domain integrator #"
                << k << ", counting from zero");
 }
```

I think the correct behavior would be to check `mesh->attributes.Max()`. 

The boundary integrators with marker have a correct check that works with non-contiguous attributes, see the code starting at [this line](https://github.com/mfem/mfem/blob/167ff72edccc4e5b0a642ae3392ccaf50f455b9e/fem/bilinearform.cpp#L485).

### PR DESCRIPTION
**Pull request by sebastiangrimberg**
Resolves #2646

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2648](https://github.com/mfem/mfem/pull/2648) | @sebastiangrimberg | @mlstowell | @jamiebramwell + @dylan-copeland | 11/8/21 | 11/22/21 | 3/16/22 | |

### CODE REVIEW

**Comment by tzanio** [comment]
Some of the test are failing, can you take a look?

For example:

```
g++  -pedantic -Wall -Werror -O3 -std=c++11   -c mesh/ncmesh.cpp -o mesh/ncmesh.o
mesh/ncmesh.cpp: In member function ‘std::size_t mfem::PointMatrixHash::operator()(const mfem::NCMesh::PointMatrix&) const’:
mesh/ncmesh.cpp:2649:55: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
             hash = 31*hash + *((std::uint64_t*) &coord);
                                                       ^
mesh/mesh_readers.cpp: In member function ‘void mfem::Mesh::ReadGmshMesh(std::istream&, int&, int&)’:
mesh/mesh_readers.cpp:1580:55: error: ‘bb_max[2]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                                             bb_max[2] - bb_min[2]));
                                             ~~~~~~~~~~^~~~~~~~~~~
mesh/mesh_readers.cpp:1579:55: error: ‘bb_max[1]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                                    std::max(bb_max[1] - bb_min[1],
                                             ~~~~~~~~~~^~~~~~~~~~~
mesh/mesh_readers.cpp:1578:46: error: ‘bb_max[0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
          double bb_size = std::max(bb_max[0] - bb_min[0],
                                    ~~~~~~~~~~^~~~~~~~~~~
mesh/mesh_readers.cpp:1580:55: error: ‘bb_min[2]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                                             bb_max[2] - bb_min[2]));
                                             ~~~~~~~~~~^~~~~~~~~~~
mesh/mesh_readers.cpp:1579:55: error: ‘bb_min[1]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
                                    std::max(bb_max[1] - bb_min[1],
                                             ~~~~~~~~~~^~~~~~~~~~~
mesh/mesh_readers.cpp:1578:46: error: ‘bb_min[0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
          double bb_size = std::max(bb_max[0] - bb_min[0],
                                    ~~~~~~~~~~^~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by sebastiangrimberg** [comment]
I noticed this as well, and some other recently updated PRs seem to have the same issue. I didn't change anything in those files so I'm not sure why the CI is just now complaining. For the `mesh_readers.cpp` errors at least, it looks like just initializing bb_min and bb_max to 0.0 will resolve this. Not sure about the strict-aliasing error for `ncmesh.cpp`.

**Comment by v-dobrev** [comment]
You can ignore this error -- it is not related to this PR and it will be fixed in https://github.com/mfem/mfem/pull/2649.

**Comment by mlstowell** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by dylan-copeland** [comment]
@sebastiangrimberg Thanks for your contribution, but I am not sure why the new checks are necessary. In what case would there be a non-null `domain_integs_marker[k]` of size 0? My understanding is that in the case of no mesh attributes, `domain_integs_marker[k]` should simply be `NULL`, not a pointer to an array of size 0. Is there a good reason to have an array of size 0?

**Comment by sebastiangrimberg** [comment]
@dylan-copeland I agree that it would be unexpected usage, but I just based this on the code for boundary markers [here](https://github.com/mfem/mfem/blob/6ac1fb303c0eb03c0014b7446fb2760cb9504e80/fem/bilinearform.cpp#L486) and @v-dobrev's suggestion from #2646. Happy to go either way with this, the main point is to just fix the current buggy implementation.

**Comment by dylan-copeland** [comment]
@sebastiangrimberg Thanks for clarifying. This PR makes more sense in the context of issue 2646, with non-continugous attributes. The fix seems to be checking `Max` rather than `Size`. Just changing to `Max` would have the issue that `Max` is not defined when `Size` is 0, so I see why check that `Size` is positive. However, this allows for the case that `domain_integs_marker[k]` is a pointer to an array of size 0, which is a change I'm not sure is intended. Would it be better to do something like this?
`MFEM_VERIFY(mesh->attributes.Size() && domain_integs_marker[k]->Size() == mesh->attributes.Max()`

**Comment by sebastiangrimberg** [comment]
@dylan-copeland That is certainly also a viable option. From the user perspective, if the mesh has no boundary attributes, they would probably still proceed with creating a marker array of size `mesh->Attributes.Size()` (= 0) and pass that to the `AddDomainIntegrator`. If we want the code to error out during assembly, we should use your suggestion. Looking at how the marker is used, it looks like the access at line 439 would be out of bounds so that's not great and thus I guess your check makes more sense. 

Looking at the behavior for passing a marker with `AddBoundaryIntegrator`, I believe the current fix here is consistent, but it seems lik that there too if the mesh has no boundary attributes it will try to access the boundary marker of size 0 which would be problematic.

Perhaps others can better weigh in on the choice, I really do not have a preference and just want to get the `Max` fix in.

**Comment by v-dobrev** [comment]
The reason to allow `mesh->attributes.Size() == 0` is the case where (in parallel) a processor is not assigned any mesh elements, so no attributes are present locally.

On the other hand, typically, `mesh->attributes` are set to represent the global set of attributes, not just the local, see https://github.com/mfem/mfem/blob/2519a91d015d7842df62aa9cce4df9a17f443c9a/mesh/pmesh.hpp#L207-L208

However, just to be on the safe side, I thought it is better to also allow for cases where `mesh->attributes` lists just the local attributes. In such cases, the user will pass in an array of `mesh->attributes.Size() ? mesh->attributes.Max() : 0` to the method https://github.com/mfem/mfem/blob/2519a91d015d7842df62aa9cce4df9a17f443c9a/fem/bilinearform.hpp#L342-L345 or the method https://github.com/mfem/mfem/blob/2519a91d015d7842df62aa9cce4df9a17f443c9a/fem/linearform.hpp#L123-L126

Of course, they can use the methods without the marker arrays when `mesh->attributes.Size() == 0`, however, it does not cost us anything to allow it also with the versions with the marker array.

**Review by dylan-copeland — APPROVED** [review]

**Comment by sebastiangrimberg** [comment]
Hi everyone, any update on this? Not sure why the codecov check is failing, I didn't add any new code really...

**Comment by pazner** [comment]
@jamiebramwell, can you take a look at this when you get a chance?

**Review by jamiebramwell — APPROVED** [review]
Sorry for my tardiness and thank you for the fix!

**Comment by sebastiangrimberg** [comment]
Hi all, any chance this might also be ready for merge with 4.4? Thanks!

**Pull request merged**
