### PR TITLE
Pass dummy matrix to SNES at creation time

### PR DESCRIPTION
**Pull request by stefanozampini**
Fixes https://github.com/mfem/mfem/issues/2299

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2331](https://github.com/mfem/mfem/pull/2331) | @stefanozampini | @tzanio | @tzanio + @jandrej | 06/13/21 | 06/14/21 | 06/15/21 | |

### CODE REVIEW

**Comment by stefanozampini** [comment]
@tzanio This should be merged in 4.3

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
LGTM

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
