### PR TITLE
Removing redundant argument from Coefficient::Eval [coef-eval-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
The IntegrationPoint argument to Coefficient::Eval methods was made redundant by the addition of a IntPoint member to the ElementTransformation class.  This PR eliminates this argument and adds some robustness to the handling of integration points by the ElementTransformation class.

Because these changes have the potential to effect a great deal of code we also add an MFEM_DEPRECATED variable to enable the older API.  This will allow dependent codes to ignore these changes until they choose to deal with this issue.

### CODE REVIEW

**Comment by YohannDudouit** [comment]
I think it would be great to correct the `const` correctness of this class in the same time.

**Comment by mlstowell** [comment]
Hey, @YohannDudouit, I think I missed your comment at first.  Have a look at the branch `coef-eval-const-dev`.  Is this what you had in mind?

**Comment by YohannDudouit** [comment]
I was thinking that function like `Eval` should be `const`
`virtual double Eval(ElementTransformation &T) const;`
instead of
`virtual double Eval(ElementTransformation &T);`
I don't see why evaluating a `Coefficient` should change the state of the `Coefficient` in an observable way, that's why I'm suggesting `Eval` to be `const`.

**Comment by mlstowell** [comment]
Yes, I agree completely and that is the primary change in the other branch that I mentioned.  I also changed the "constness" of the `ElementTransformation` for a similar reason.  Requesting the Jacobian or transforming a point should not change the `ElementTransformation` object (the fact that it does is simply an implementation choice made for efficiency so this should be hidden from users).

**Comment by YohannDudouit** [comment]
Sorry, I looked at this branch indeed, my head is in the clouds... What you do in your other branch is exactly what I was thinking about.

**Comment by v-dobrev** [comment]
I don't like to make interface changes that affect a lot of code and there is no immediate need for the change.

Do you have a specific need to change the current interface?

**Comment by mlstowell** [comment]
I understand the reluctance to make such a pervasive API change but this is why I also added the `MFEM_DEPRECATED` option to the build system.  Initially I had used this incorrectly but I think it has the desired behavior now.  Specifically, if this is set to `YES` then existing coefficient implementations should not need to be changed at all.  I just added a short example code, `examples/ex_depr.cpp`, which can be used to test MFEM_DEPRECATED (we can remove this before merging).

Regarding a specific need to make this change I would argue that the existing API provides the opportunity to implement a bug which would be very difficult to locate.  For example whenever we call an `Eval(T, ip)` method we are passing two integration points.  We expect them to be the same but there is no requirement that they are in fact the same.  Therefore a developer could set one of them while the implementation of `Eval(T, ip)` uses the other one.  Often the result of such a mixup would be so subtle as to be nearly impossible to track down, assuming that it is even noticed.

**Comment by v-dobrev** [comment]
OK, I see that you _really_ want to go forward with the deprecation _now_.

However, I think there is a better, more standard way to do that. Namely, instead of removing the old `Eval` method immediately, we can deprecate it by marking it with a macro, say `MFEM_DEPRECATED`, which is set to `__attribute__ ((deprecated))` - see https://gcc.gnu.org/onlinedocs/gcc-3.3/gcc/Function-Attributes.html. This way the compiler will issue warnings whenever the old method is used, however, existing code will not need to be changed immediately.

Then later, after one or more releases, we can proceed with the actual removal of the method.

What do you think about this approach?

**Comment by mlstowell** [comment]
I do like that approach.  I looked for something like this but only found solutions for c++11.  If we can find a portable way to implement this macro then I'm definitely in favor of this.

**Comment by v-dobrev** [comment]
I tried modifying the branch by adding `__attribute__ ((deprecated))` to the old `Eval` methods in the base class `Coefficient`. This, however, did not have the desired effect - new classes derived from it that re-define the old `Eval` methods do not inherit the deprecated attribute, so no warnings are produced by the compiler for the derived class.

An alternative that may work better, is to add deprecation warnings at run-time which are printed once per execution. For example, one place we can do that is in the definition of the new `Eval` methods in the base class - during the deprecation period they will not be pure virtual (i.e. `= 0`) - they will need to call the old `Eval` methods. This is where we can issue a run-time warning, e.g. using the macro `MFEM_WARNING`. Using a global flag, we can make sure the warning is issued one time only. Also, in parallel, we can make sure to print the warning only from rank 0.

What do you think?

**Comment by mlstowell** [comment]
I put warnings in place.  They're a bit verbose.  If anyone wants to trim that's fine.  I left the MFEM_DEPRECATED preprocessor directives in place for two reasons.  Firstly, it should make it easier to remove the deprecated code whenever we choose to do so.  Secondly, it should allow users to disable the old code whenever they're ready to do so.

**Comment by v-dobrev** [comment]
I think we should remove the `MFEM_DEPRECATED` build option. Since we will be supporting both the old `Eval` methods (with a warning) and the new ones, I do not see a reason to keep `MFEM_DEPRECATED`. In particular, there is no reason to keep the old `Eval` methods in all derived coefficient classes in MFEM - we can transition them right away. Only coefficient classes defined in user code, outside of MFEM will be using the old `Eval` methods -- until that code is updated.

**Comment by mlstowell** [comment]
We could remove the old `Eval` methods from derived classes but then the old `Eval` method in the base class could not be pure virtual.  Also, we'd need to provide an implementation of the old `Eval` method, similar to what's done in the `FiniteElement` classes, which issues an error when called.  I would really prefer to catch these missing implementations at compile time.

We could remove `MFEM_DEPRECATED` from the list of build options.  Hide it internally someplace so the average user wouldn't need to know about it.

**Pull request closed without merging**
