### PR TITLE
Add DataCollection::prefix_path to save output files in a custom directory

### PR DESCRIPTION
**Pull request by martemyev**
Prefix path is set up by means of DataCollection::SetPrefixPath function which takes a const char* as an argument. If the pointer is NULL, the prefix path is cleared up.

### CODE REVIEW

**Comment by martemyev** [comment]
Hi Tzanio,

I just removed the previous pull request and created a new one based on the new files. I think this new solution is more in MFEM spirit, so you should've actually committed them right away.

Cheers,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

I considered updating the pull request, but I was not sure if I am allowed to push to your forked repository. There must be a better way to handle updates to pull requests like these, but I'm not sure what it is :).

BTW, why do you create another pull request instead of updating the old one? Couldn't you just push the changes in `martemyev:master`?

Tzanio

**Comment by martemyev** [comment]
Tzanio,
> BTW, why do you create another pull request instead of updating the old one? Couldn't you just push the changes in martemyev:master?
I could if I'd commit to the same branch. But I created a new branch based on the original mfem/master in my forked repository and cherry-pick'ed the latest changes about the RAP function to make a separate pull request (without mixing the changes related to prefix_path and RAP), so I had two different branches, and I decided to put new datacollection files in the new branch, therefore I think those changes wouldn't be automatically picked up by GitHub, so I created a new pull request. That seemed to be the easiest solution. I may be wrong though.

> I considered updating the pull request, but I was not sure if I am allowed to push to your forked repository.
I think you shouldn't push to my repository. I believe that the workflow for you is to commit to `develop` branch, and I'll then rebase my local repository and push to my GitHub forked repository to keep it updated.

Cheers,
Mikhail

**Comment by tzanio** [comment]
Thanks for the clarification, Mikhail.

We use a different workflow in our internal [Stash](https://www.atlassian.com/software/bitbucket/server) server, where features are developed in temporary branches, and pull requests from such branches are being automatically updated by pushing to the branch. Some of these pull requests have had long discussions with many updates to the branch/pull request, so I'm not sure it is a good to idea of update the target branch before the pull request is merged. (Sometimes we are not even sure if want to merge the feature, until several rounds of updates.)

I'll ask around to see if any of the GitHub experts here have a better suggestion.

Cheers,
Tzanio

**Comment by martemyev** [comment]
Tzanio,

> We use a different workflow in our internal Stash server

Since Stash is a git running server as well as GitHub, I think the workflow is pretty much the same, and the one that you described should be perfectly valid on GitHub. If I'd commit the changes to the same branch and push to my forked GitHub repo, the initial pull request would be updated, and this is basically the same as what you do on Stash. I was just saying that if you update the code internally in your local repository, you could just push the changes to GitHub without uploading the modified files so that I update the pull request. I just think it would be faster. That's it :)

Cheers,
Mikhail

**Comment by tzanio** [comment]
Hi Mikhail,

After some thinking and discussions, here is what I think the correct workflow should be:

  1. You create a branch with your changes, e.g. `martemyev:prefix-path-dev` and issue a pull request into `mfem:develop`.
  2. We pull these changes into branches `mfem:github-48` and `github-48` on GitHub and our internal Stash respectively.
  3. We discuss internally `github-48` and make changes in Stash, that we then propagate to `mfem:github-48` on GitHub.
  4. You pull `mfem:github-48`, and if you agree with the changes, merge it into `martemyev:prefix-path-dev`, thus updating the pull request.
  5. If you have further changes, you commit them to `martemyev:prefix-path-dev`, we update `mfem:github-48` and `github-48` and loop back to Step 3.
  6. When everybody is happy, we merge `github-48` locally, and then merge the pull request and delete `mfem:github-48` on GitHub.

What do you think, does this sound reasonable? The key for us is that we want the merging of `github-48` on Stash to correspond to the merging of the pull request on GitHub. (We also do not want to change `mfem:develop` until we are ready to merge the pull request.)

Cheers,
Tzanio

**Comment by martemyev** [comment]
Hi Tzanio,

Yes, this workflow looks very nice.

Cheers,
Mikhail

**Comment by tzanio** [comment]
Great, thanks!

**Pull request merged**
