### PR TITLE
Fix memory leak with nonconforming tet meshes [nc-tet-alloc-fix]

### PR DESCRIPTION
**Pull request by jakubcerveny**
This a fix of #1307 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1310](https://github.com/mfem/mfem/pull/1310) | @jakubcerveny | @tzanio | @tzanio + @v-dobrev | 02/22/20 | 02/24/20 | 02/27/20 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
Thanks @jakubcerveny! Is this ready for review?

**Comment by jakubcerveny** [comment]
Should be ready.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by v-dobrev** [comment]
It looks like the sample runs
```console
./ex15 -m ../data/escher.mesh -r 2 -tf 0.3
mpirun -np 4 ./ex15p -m ../data/escher.mesh -r 2 -tf 0.3
```
are now crashing.

**Comment by jakubcerveny** [comment]
Sorry, should now be fixed. Added swapping of `TetMemory` in Mesh::Swap.

**Comment by tzanio** [comment]
Re-merged in `next` for testing ...

**Comment by v-dobrev** [comment]
I don't understand what happened here ... why is this PR "closed" and not "merged"?

**Comment by tzanio** [comment]
I believe it was merged in https://github.com/mfem/mfem/commit/e6385f2992b9c2d9001265fe3283403bec30b417.

GitHub was [behaving weirdly](https://www.githubstatus.com/incidents/q07bfjh7jf1t) and several things, including the merge button did not behave properly...

**Pull request closed without merging**
