### PR TITLE
Add DGElasticityIntegrator

### PR DESCRIPTION
**Pull request by martemyev**
Added the new class DGElasticityIntegrator which implements different DG methods
if added to the "broken" ElasticityIntegrator. Also, the formulas describing the
computations are added in the form of doxygen comments.

### CODE REVIEW

**Comment by martemyev** [comment]
Hi All,

I've written the formulas for the computation of the local matrices, and I put everything in the form of comments to let you see how I think it should be. I may be wrong, though. So any feedback is highly appreciated. Also, I didn't take into account the transformations to the reference space in the formulas, but I tried include everything in the code itself. I made this new code in the form of the pull request, so that you could build a documentation with formulas for better explanation.
I'd be very grateful if you'd extend the formulas or correct them where they are wrong.
The code compiles and even runs, but I still suspect it's incorrect and I'll need some extra testing to check it. Nevertheless, I'd appreciate if you look at it at this stage, as I removed all possible optimizations for the sake of better understanding. The code therefore is pretty slow - but my main goal right now is to have something working, and then optimize it.

Thanks,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhail,

I am looking at the code and I noticed one issue: it is about the local numbering of the vector basis functions - mfem expects first all basis functions in the x-component, then y-component, etc. In other words the numbering must be
```latex
\vec{\phi}_{i+j*ndofs}^{k} = \delta_{jk} \phi_{i}
```
where `0 <= i < ndofs`, and `0 <= j,k < dim`. Note that you need to use two separate indices, (`j,k` in the above formula) when initializing the arrays `vShape[][]` and `vDshape[][][]`.

Veselin

**Comment by martemyev** [comment]
Hi Veselin,

Thank you for pointing this out! That was very important. I changed the code according to the order of scalar bases in the vector ones. Please, take a look and suggest any other improvements.

Thanks,
Mikhail

**Comment by v-dobrev** [comment]
In the description of `AssembleInteriorFaceMatrix`, the signs in the formula for `elmat` should be: +,-,+,-, instead of +,+,-,-, since the minus comes from v2. Also, the normal `n_2` should be replaced by `n_1`, since the definition of `{v.n}` should be `{v.n}=0.5*(v1.n1+v2.n1)`.

**Comment by martemyev** [comment]
Veselin,
I'm not sure I get this. Can you please describe it in some more details, starting from the bilinear form? I think we may use slightly different formulations for the average and jumps. So, details could shed some light on that.

Thanks,
Mikhail

**Comment by v-dobrev** [comment]
Here is how I interpret the notation `<{u.n},[v]>` for an internal face with a vector `u` and a scalar `v`:
```text
<{u.n},[v]> = <0.5*(u1.n+u2.n),(v1-v2)>
```
where `n` is chosen to point from `1` to `2`, and the jump of `v` is chosen in to agree with this choice for `n`, namely `[v]=v1-v2`. This way the bilinear form does not actually depend on the choice of the normal, i.e. if you pick `n=n2` then you must pick `[v]=v2-v1` and you get the same. If the definition `{u.n}=0.5*(u1.n+u2.n)` seems strange, think of a smooth function `u` - in that case we have `{u.n}=u.n` and the jump `[u.n]=0.5*(u1.n1+u2.n2)` is zero as expected for a smooth function: `[u.n]=0.5*(u.n1+u.n2)=0`.

**Comment by martemyev** [comment]
Veselin,

Thank you for clarification. I addressed those improvements in the new commit. Also, I'm testing this integrator on an elliptic problem, but still can't make it work. Here is the code with the same elliptic problem of linear elasticity solved by CG and DG. The CG method works great, while DG still doesn't. 

```cxx
#include "mfem.hpp"
#include <fstream>
#include <iostream>

using namespace std;
using namespace mfem;

const double LAMBDA = 1.0;
const double MU = 1.0;

const int MX = 1;
const int NX = 1;
const int MY = 1;
const int NY = 1;

const double SX = 100.0;
const double SY = 100.0;

void U_exact(const Vector &point, Vector &values) {
   const double x = point(0);
   const double y = point(1);
   values(0) = sin(M_PI*x*MX/SX)*sin(M_PI*y*NX/SY);
   values(1) = sin(M_PI*x*MY/SX)*sin(M_PI*y*NY/SY);
}

void F_exact(const Vector &point, Vector &values) {
   const double x = point(0);
   const double y = point(1);
   const double Pi = M_PI;

   values(0) = (Pi*Pi*(-((LAMBDA + MU)*MY*NY*SX*SY*cos((MY*Pi*x)/SX)*cos((NY*Pi*y)/SY)) +
                         (MU*NX*NX*SX*SX + LAMBDA*MX*MX*SY*SY + 2*MU*MX*MX*SY*SY)*sin((MX*Pi*x)/SX)*sin((NX*Pi*y)/SY)))/(SX*SX*SY*SY);
   values(1) = (Pi*Pi*(-((LAMBDA + MU)*MX*NX*SX*SY*cos((MX*Pi*x)/SX)*cos((NX*Pi*y)/SY)) + 
                         (LAMBDA*NY*NY*SX*SX + 2*MU*NY*NY*SX*SX + MU*MY*MY*SY*SY)*sin((MY*Pi*x)/SX)*sin((NY*Pi*y)/SY)))/(SX*SX*SY*SY);
}

int main(int argc, char *argv[]) {
   int order = 1;
   const double sigma = -1.0;
   double kappa = 10.0;

   OptionsParser args(argc, argv);
   args.AddOption(&order, "-o", "--order",
                  "Finite element order (polynomial degree).");
   args.AddOption(&kappa, "-k", "--kappa",
                  "Parameter of the DG bilinear form");

   args.Parse();
   if (!args.Good()) {
      args.PrintUsage(cout);
      return 1;
   }
   args.PrintOptions(cout);

   const int nx = 100;
   const int ny = 100;
   const int generate_edges = 1;
   Mesh *mesh = new Mesh(nx, ny, Element::QUADRILATERAL, generate_edges, SX, SY);
   const int dim = mesh->Dimension();

   ConstantCoefficient lambda(LAMBDA);
   ConstantCoefficient mu(MU);

   VectorFunctionCoefficient f(dim, F_exact);
   VectorFunctionCoefficient U(dim, U_exact);

   { // CG method
      FiniteElementCollection *fec = new H1_FECollection(order, dim);
      FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec, dim);
      Array<int> ess_tdof_list, ess_bdr(mesh->bdr_attributes.Max());
      ess_bdr = 1;
      fespace->GetEssentialTrueDofs(ess_bdr, ess_tdof_list);
      LinearForm *b = new LinearForm(fespace);
      b->AddDomainIntegrator(new VectorDomainLFIntegrator(f));
      b->Assemble();
      GridFunction x(fespace);
      x = 0.0;
      BilinearForm *a = new BilinearForm(fespace);
      a->AddDomainIntegrator(new ElasticityIntegrator(lambda, mu));
      a->Assemble();

      SparseMatrix A;
      Vector B, X;
      a->FormLinearSystem(ess_tdof_list, x, *b, A, X, B);
      GSSmoother M(A);
      PCG(A, M, B, X, 1, 500, 1e-8, 0.0);
      a->RecoverFEMSolution(X, *b, x);

      cout << "\n|| x_CG - U ||_{L^2} = " << x.ComputeL2Error(U) << endl;

      delete a;
      delete b;
      delete fespace;
      delete fec;
   }

   { // DG method
      FiniteElementCollection *fec = new DG_FECollection(order, dim);
      FiniteElementSpace *fespace = new FiniteElementSpace(mesh, fec, dim);
      VectorFunctionCoefficient f(dim, F_exact);
      LinearForm *b = new LinearForm(fespace);
      b->AddDomainIntegrator(new VectorDomainLFIntegrator(f));
      b->Assemble();
      GridFunction x(fespace);
      x = 0.0;
      BilinearForm *a = new BilinearForm(fespace);
      a->AddDomainIntegrator(new ElasticityIntegrator(lambda, mu));
      a->AddInteriorFaceIntegrator(new DGElasticityIntegrator(lambda, mu, sigma, kappa));
      a->AddBdrFaceIntegrator(new DGElasticityIntegrator(lambda, mu, sigma, kappa));
      a->Assemble();

      const SparseMatrix &A = a->SpMat();
      GSSmoother M(A);
      PCG(A, M, *b, x, 1, 500, 1e-8, 0.0);

      cout << "\n|| x_DG - U ||_{L^2} = " << x.ComputeL2Error(U) << endl;

      delete a;
      delete b;
      delete fespace;
      delete fec;
   }

   delete mesh;

   return 0;
}
```

Any feedback on where to look for an error is highly appreciated.

Thanks,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhail,

I looked at the code for computing `elmat` and I think the first and the third terms may be incorrect, basically transforming `nor` into `nh` only works for the second term. Here's how I would implement those expressions (what you call `E_{ij}`):

Start by splitting a (row,column) index `(i,j)` as:
```text
i=i1+i2*ndofs,   0 <= i1 < ndofs, 0 <= i2 < dim
j=j1+j2*ndofs,   0 <= j1 < ndofs, 0 <= j2 < dim
```
Define:
```text
phi(i,k)        = delta(i2,k)*shape(i1)
hat_grad(i,k,l) = delta(i2,k)*dshape(i1,l)
grad(i,k,l)     = sum_{t} (1/detJ)*adjJ(t,l)*hat_grad(i,k,t)
```
Then we can transform the expressions like this:

First term:
```text
sum_{d,r} grad(j,r,r)*phi(i,d)*n(d) =
sum_{d,r,t} (1/detJ)*adjJ(t,r)*hat_grad(j,r,t)*phi(i,d)*n(d) =
sum_{d,r,t} (1/detJ)*adjJ(t,r)*delta(j2,r)*dshape(j1,t)*delta(i2,d)*shape(i1)*n(d) =
sum_{t} (1/detJ)*adjJ(t,j2)*dshape(j1,t)*shape(i1)*n(i2)
```
Second term:
```text
sum_{d,r} phi(i,d)*grad(j,d,r)*n(r) =
sum_{d,r,t} phi(i,d)*(1/detJ)*adjJ(t,r)*hat_grad(j,d,t)*n(r) =
sum_{d,r,t} delta(i2,d)*shape(i1)*(1/detJ)*adjJ(t,r)*delta(j2,d)*dshape(j1,t)*n(r) =
sum_{r,t} delta(i2,j2)*shape(i1)*(1/detJ)*adjJ(t,r)*dshape(j1,t)*n(r)
```
Third term:
```text
sum_{d,r} phi(i,d)*grad(j,r,d)*n(r) =
sum_{d,r,t} phi(i,d)*(1/detJ)*adjJ(t,d)*hat_grad(j,r,t)*n(r) =
sum_{d,r,t} delta(i2,d)*shape(i1)*(1/detJ)*adjJ(t,d)*delta(j2,r)*dshape(j1,t)*n(r) =
sum_{t} shape(i1)*(1/detJ)*adjJ(t,i2)*dshape(j1,t)*n(j2)
```

Extract and pre-compute the common expression:
```text
dshape_phys(j1,j2) = sum_{t} (1/detJ)*adjJ(t,j2)*dshape(j1,t)
```
With that we have:

First term:
```text
dshape_phys(j1,j2)*shape(i1)*n(i2)
```
Second term:
```text
sum_{r} delta(i2,j2)*shape(i1)*dshape_phys(j1,r)*n(r)
```
(here, `sum_{r} dshape_phys(j1,r)*n(r)` can be pre-computed as well)
Third term:
```text
shape(i1)*dshape_phys(j1,i2)*n(j2)
```

Double check if the transformations I did are correct. This way there is no need to define `vShape` and `vDshape`. Replacing `n(k)` with `nor(k)` will give you the weight from the integral change of variables.

Veselin

**Comment by martemyev** [comment]
Hi Veselin,

Your suggestions look great. That will speed up the computations in times.
The only thing I'm not sure about is how to deal with the `jmat` term. I see it this way:
```
sum_{d} phi(i,d) phi(j,d) = sum_{d} delta(i2,d) shape(i1) delta(j2,d) shape(j1) = delta(i2,j2) shape(i1) shape(j1)
```
But I'm not sure about the transformation of the coordinates.

Thanks,
Mikhail

**Comment by martemyev** [comment]
Hi Veselin,

I updated the code w.r.t. to your suggestions. I double checked the formulas, and hopefully ported them correctly into the code. The elliptic problem, however, still doesn't work. Do you have any tests in mind that could prove the DG elasticity integrator works correctly?

BTW,
> Replacing n(k) with nor(k) will give you the weight from the integral change of variables.
Do I understand correctly that `\vec{nor} = \vec{n} |det J|`, where n is a unit vector?

Cheers,
Mikhail

**Comment by martemyev** [comment]
Veselin,

I found the error - it was at the very end, when the elmat matrix was computed as -elmat + sigma*elmat^t + kappa*jmat. That's my bad.

Cheers,
Mikhail

**Comment by martemyev** [comment]
Veselin,

Even though I fixed that error, the elliptic problem that I use as a test works well with DG only when the cells have size 1, i.e. the transformation to the reference cell is identity. So, I believe I mixed something up in the normals or Jacobians, or both.

I'd be really grateful if you'd look into that in the code.

Thanks,
Mikhail

**Comment by v-dobrev** [comment]
Hi Mikhail,

In the formula
```c++
const double jmatcoef = w * detJ1 * (L1 + 2.0*M1 + L2 + 2.0*M2);
```
the weight `detJ1` is not correct, it should be the `Weight()` of the face transformation: `Trans.Face->Weight()` or equivalently `sqrt(nor * nor)`. In addition, I think there should be a scaling on the order of `1/h` in this term - sometimes it is considered to be part of `kappa`. The natural way to define `h` is to use the element size in direction perpendicular to the face, which can be computed as the ratio `element_weight/face_weight`. With this definition, the formula for `jmatcoef` becomes:
```c++
const double jmatcoef = w * (nor * nor) * ((L1+2*M1)/detJ1 + (L2+2*M2)/detJ2);
```
This type of formula is used in `DGDiffusionIntegrator` as well.

Veselin

**Comment by martemyev** [comment]
Hi Veselin,

Thanks for correct formulas! Now everything works well. I pushed some more commits with some sort of optimizations of computations. Please, let me know if you have any concerns about the code.

Cheers,
Mikhail

**Comment by tzanio** [comment]
@martemyev and @v-dobrev, I was wondering what's the status of this PR: do you think this is something we want to have in the library (or is it too specialized), and if you do, is it ready to be merged?

**Comment by martemyev** [comment]
I would really like to have it in the library. There are integrators for diffusion with CG and DG, and for elasticity with CG. So, to me it looks like DG for elasticity is a missing piece. I've used it for elastic wave simulations, so I'd say it's fully implemented (I guess that counts against the readiness).

Cheers,
Mikhail

**Comment by tzanio** [comment]
Reviewing internally... stay tuned

**Pull request merged**
