### PR TITLE
Add winsock initialization to socketstream

### LINKED ISSUE #2000: winsock usage
Before using any winsock functions, `WSAStartup` has to be called:
https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-wsastartup

Adding the following code to [socketstream.cpp](https://github.com/mfem/mfem/blob/master/general/socketstream.cpp#L58) solved the problem for me:
```c
int socketbuf::open(const char hostname[], int port)
{
   // ...
#ifdef _WIN32
   WSADATA wsaData;
   WSAStartup(MAKEWORD(2, 2), &wsaData);
#endif
   hp = gethostbyname(hostname); // <- will always be null without WSAStartup
   if (hp == NULL)
   // ...
}
```

EDIT: calling `WSAStartup` in the constructor and `WSACleanup` in the destructor of the `socketstream` class would be cleaner .

### PR DESCRIPTION
**Pull request by kanye-quest**
Should fix #2000.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2009](https://github.com/mfem/mfem/pull/2009) | @kanye-quest | @tzanio | @tzanio + @v-dobrev | 01/25/21 | 02/02/21 | 02/03/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
@wo80, I can't add you as a reviewer until you join the MFEM organization, so can you approve informally by posting a message below?

**Review by tzanio — APPROVED** [review]
Neat solution, @kanye-quest.

**Comment by wo80** [comment]
@tzanio Approved!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Thanks @kanye-quest

**Pull request merged**
