### PR TITLE
Shifted bug fix

### PR DESCRIPTION
**Pull request by atallah727**
Fixed a bug in sbm_solver.cpp file. I have to reset the temp_elvect vector to zero at the beginning of the quadrature point loop. 
I also fixed a small typo in the comments pertaining to the sign of the penalty term in variational form.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2754](https://github.com/mfem/mfem/pull/2754) | @atallah727 | @tzanio | @vladotomov + @kmittal2 | 01/05/22 | 01/14/22 | 01/17/22 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by vladotomov — APPROVED** [review]
Thanks Nabil, good catch.

**Comment by kmittal2** [comment]
Hi @atallah727, 
Earlier we were calculating the integral in `temp_elvect` and setting `elvect = temp_elvect` at the end (I was accidentally doing it inside the loop over quadrature points instead of outside.. it should not change the final `elvect` but I was doing more FLOPS than needed). 
What we are doing now is that we are setting `temp_elvect = 0` for each quadrature point and adding the contribution as `elvect += temp_elvect` inside the loop. 
Seems like the final result should be the same in both cases? I did a quick check but let me know what you find out as well.
If you agree, I think it might be more computationally efficient to keep the original approach and move the `elvect = temp_elvect` part outside the loop over quadrature points. 
p.s. We should fix this in the BilinearFormIntegrator as well (including the ones for Neumann boundary condition). I can help you with that once we agree on which approach to use.

**Comment by atallah727** [comment]
Hello Ketan,

We can talk tomorrow to discuss your proposition. Let me know when would be a good time.

Thank you.

Best

Nabil
________________________________

**Comment by kmittal2** [comment]
Had offline discussions with @atallah727 and made changes accordingly.
@vladotomov, can you please take a look at the PR again?

**Review by kmittal2 — APPROVED** [review]

**Review by vladotomov — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Review by tzanio — APPROVED** [review]
Thanks for the fix @atallah727

**Pull request merged**
