### PR TITLE
Scalar and Vector Products [linear-interp-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
This branch implements five types of scalar and vector products as linear interpolators.  These can be used to compute products of fields or products with arbitrary coefficients.

Since these only use interpolation, care must be taken to ensure that the range space has a high enough order to adequately represent the desired product.

### CODE REVIEW

**Comment by mlstowell** [comment]
There also exists a branch in the "tests" repository which contains a test code for these changes.

**Comment by tzanio** [comment]
Mention in `CHANGELOG` before merging.

**Comment by v-dobrev** [comment]
@mlstowell, what is good way to test the changes I made?

**Comment by mlstowell** [comment]
I put a few simple test cases in the "tests" repository on our internal BitBucket server.  See the file "unit-test.cose/fem/test_lin_interp.cpp" in the "linear-interp-dev" branch.

**Comment by v-dobrev** [comment]
The internal unit tests go through without any issues. I'm merging into `next`.

**Pull request merged**
