### PR TITLE
Adding get-values miniapp [get-values-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
This miniapp was requested by RF SciDAC collaborators but I felt it would be generally useful.  It is a modified version of the `load-dc` miniapp which uses `Mesh::FindPoints` and `GridFunction::GetValue` or `GridFunction::GetVectorValue` to extract field data from a previously saved `VisitDataCollection`.  The points can either be supplied on the command line or through a data file.  The output can either be displayed to the screen or written to an output file.  It includes the option to dump all field data or a selected subset of fields.

| PR | Author | Editor | Reviewers  | Assignment | Approval | Merge |
| --- | --- | --- | ---  | --- | --- | --- |
| https://github.com/mfem/mfem/pull/1179 | @mlstowell | @v-dobrev | @psocratis + @rw-anderson | 12/13/19 | 01/10/20 | ⌛due 01/17/20 |

### CODE REVIEW

**Comment by tzanio** [comment]
@v-dobrev, can you take this one?

**Comment by psocratis** [comment]
Hi @mlstowell, 

I seems that there is a naming mismatch between the volta miniapp and the get-values tool. A sample run of the volta miniapp produces the directories "Volta-AMR-Parallel_00000x and the files "Volta-AMR-Parallel_00000x.mfem_root" starting with x=1, but get-values is looking for "Volta-AMR-Parallel_000000". 

Thanks, 
Socratis

**Comment by mlstowell** [comment]
Good catch, @psocratis !  We can set the cycle on the command line so I altered the sample run to use cycle 1.  The default cycle is still zero which I believe is used for initial conditions in the time-dependent examples.

**Comment by psocratis** [comment]
Hi @mlstowell , 

I just tested it now and it works fine. Autotest suite also passed. 

There is one more small detail. Correct me if I am wrong, but the number of mpi ranks used by get-values has to match the the number of mpi ranks used by the miniapp/example. Otherwise there is a warning and then an exit error during loading the data. This warning doesn't appear when only on mpi rank was used for the miniapp and more than one by get-values. The code just terminates with a non-zero exit code. 

Other than the above, it looks good to me. 

Socratis

**Comment by rw-anderson** [comment]
I've reviewed this and I think it looks good.

I think the value of the mini-app would increase if it was generalized to not only find points in space, but in time.  In other words, to interpolate between cycles.  Much like the value of querying in space rather than at vertices or integration points, querying in time rather than at cycles provides additional value, especially when used as a testing tool or for comparison solutions quantitatively.

But perhaps it's out of scope for the initial mini-app.

**Comment by mlstowell** [comment]
Hi, @psocratis ,
I wonder if that's an issue within the `VisitDataCollection`.   The mini app itself does very little error checking of this sort. 

Mark

**Comment by tzanio** [comment]
Merged in `next` for testing ...

**Comment by tzanio** [comment]
Add in `.gitignore`, see https://mybitbucket.llnl.gov/projects/MFEM/repos/autotest/commits/bedd62f8ef667e3d24fb7619d7f42a967f02c912#tux426/2020-01-13-llnl-gh-next/gitignore.err

**Comment by tzanio** [comment]
Re-merged in `next` for testing ...

**Comment by tzanio** [comment]
Please make sure that all relevant items from the PR checklist are addressed:

- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.

**Comment by tzanio** [comment]
Re-merged in `next` for testing ...

**Pull request merged**
