### PR TITLE
Fix for Tetrahedral Mesh Refinement [conforming-tet-refinement-fix]

### LINKED ISSUE #512: Shape regularity for adaptive tetrahedral meshes
Hello,

it seems that using adaptive mesh refinement on tetrahedral meshes destroys the shape regularity of the mesh. 

In order to avoid any influences from my own code, I modified Example 6 (serial) such that it calls the function `Mesh::PrintCharacteristics(...)` in each AMR iteration and increased the maximum number of dofs up to 500000, i.e.,
```
...
const int max_dofs = 500000;
for (int it = 0; ; it++)
{
   ...
   Vector v1, v2;
   mesh.PrintCharacteristics(&v1, &v2, std::cout);
   ...
}
...
```
I tested the mesh [data/inline-tet.mesh](https://github.com/mfem/mfem/blob/master/data/inline-tet.mesh)  and monitored the behavior of `kappa_min`and `kappa_max` where you can see that `kappa_max` is increasing dramatically during the iterations (c.f. below).
ex6_kappa_cube

I tested also a second mesh which i created with NETGEN ([mesh.zip](https://github.com/mfem/mfem/files/2089741/mesh.zip)), a big cube with one smaller cube cut out in a corner. Here, the value of `kappa_max` increases even more than before (c.f. below)
ex6_kappa_lshape

Best regards,
Andreas

### PR DESCRIPTION
**Pull request by aschaf**
Fixed the local refinement for tetrahedral meshes such that no degeneration occurs. I followed @v-dobrev 's suggestion in #512  and used the `HashTable<Hashed2>` object instead of a `DSTable`.

I redid the numerical experiments that led me to this issue and now their results are as expected. 

For now the way `NumOfVertices` is updated is somewhat dirty. Maybe we can add another member variable to `Mesh` that contains the number of vertices of the unrefined mesh and update `NumOfVertices` as before.

Resolves #512.

### CODE REVIEW

**Comment by v-dobrev** [comment]
I was doing some testing and the following sample run failed:
```console
mpirun -np 4 ./ex15p -m ../data/escher.mesh -r 2 -tf 0.3 -no-vis
```
The same run on 1 and 2 processors seems to work fine.

The issue is probably in the way refinements are exchanged between neighbour processors. In particular, the method
https://github.com/mfem/mfem/blob/abd5c313d9d49c8b7894fd9c323430adae7bc4aa/mesh/pmesh.hpp#L67
does not support arbitrary refinements and that is probably causing the failure.

Any ideas about resolving this in a simple way?

**Comment by aschaf** [comment]
Maybe one could not only check the face itself but also the newly generated faces if they are again split and then if they are split and so on. However I I'm not sure if this is really feasible and how to communicate this. 
Do we have any upper bound on how often a face can be split?

**Comment by aschaf** [comment]
I don't know if this helps but when I force bisection instead of octasection by changing
```
marked_elements.Append(Refinement(el));
```
to
```
marked_elements.Append(Refinement(el,1));
```
in `mesh_operators.cpp` the example works fine again.

**Comment by v-dobrev** [comment]
I do not know if there is an upper bound on the number of face splittings.

**Comment by v-dobrev** [comment]
The issue with the sample run
```console
mpirun -np 4 ./ex15p -m ../data/escher.mesh -r 2 -tf 0.3 -no-vis
```
is fixed now.

**Comment by v-dobrev** [comment]
I think I fixed the issue. Thanks for catching that - it was a serious bug.

**Comment by tzanio** [comment]
@jakubcerveny can you take a look at this PR?

**Comment by jakubcerveny** [comment]
I don't understand the algorithm precisely, but the changes seem OK. I tried ex6p on the Escher mesh. It works and the refinements even look a little more reasonable (fewer refinements in the center of the domain, but it can be a coincidence).

**Comment by jakubcerveny** [comment]
Nice work @aschaf!

**Comment by tzanio** [comment]
Thank you for the contribution @aschaf, very nice work!

**Pull request merged**
