### PR TITLE
Use cuda-shared in ex1p to avoid differences in autotest.

### PR DESCRIPTION
**Pull request by YohannDudouit**
This PR "comments" the device run in `ex1p` using `-d ceed-cuda`, and adds a device run using the cuda-shared backend of libCEED instead.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1580](https://github.com/mfem/mfem/pull/1580) | @YohannDudouit | @tzanio | @tzanio + @camierjs | 06/27/20 | 06/30/20 | 07/04/20 | |

### CODE REVIEW

**Comment by tzanio** [comment]
Should we modify also `ex1.cpp`?

**Comment by YohannDudouit** [comment]
We could, but the problem doesn't show up in the tests as far as I know.

**Comment by YohannDudouit** [comment]
@tzanio I added it to `ex1` too.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
