### PR TITLE
Add missing files to cmake

### LINKED ISSUE #1264: Compiling MFEM in parallel fails
In my macOS 10.14.6, using openMPI 1.8.5 with clang-1001.0.46.4, I build the MFEM in parallel with hypre-2.10.0b and metis 4.0. When linking the examples, I get this error:

```
[ 39%] Linking CXX executable ex1
cd /Users/salazardetro1/scicomp_libraries/mfem/mfem/build/examples && /usr/local/Cellar/cmake/3.15.3/bin/cmake -E cmake_link_script CMakeFiles/ex1.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++  -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/ex1.dir/ex1.cpp.o  -o ex1 ../libmfem.a /Users/salazardetro1/scicomp_libraries/mfem/metis-4.0/libmetis.a
 "mfem::GradientIntegrator::AssemblePA(mfem::FiniteElementSpace const&, mfem::FiniteElementSpace const&)", referenced from:
      vtable for mfem::GradientIntegrator in libmfem.a(bilininteg.cpp.o)
  "mfem::VectorDivergenceIntegrator::AssemblePA(mfem::FiniteElementSpace const&, mfem::FiniteElementSpace const&)", referenced from:
      vtable for mfem::VectorDivergenceIntegrator in libmfem.a(bilininteg.cpp.o)
  "mfem::GradientIntegrator::AddMultTransposePA(mfem::Vector const&, mfem::Vector&) const", referenced from:
      vtable for mfem::GradientIntegrator in libmfem.a(bilininteg.cpp.o)
  "mfem::GradientIntegrator::AddMultPA(mfem::Vector const&, mfem::Vector&) const", referenced from:
      vtable for mfem::GradientIntegrator in libmfem.a(bilininteg.cpp.o)
  "mfem::VectorDivergenceIntegrator::AddMultTransposePA(mfem::Vector const&, mfem::Vector&) const", referenced from:
      vtable for mfem::VectorDivergenceIntegrator in libmfem.a(bilininteg.cpp.o)
  "mfem::VectorDivergenceIntegrator::AddMultPA(mfem::Vector const&, mfem::Vector&) const", referenced from:
      vtable for mfem::VectorDivergenceIntegrator in libmfem.a(bilininteg.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed 
exit code 1 (use -v to see invocation)
```

Do I need some external library to habilitate PA? Maybe CEED? The linker is c++, but I enabled MPI, maybe that is the problem? Thanks.

Edit: Adding the symbols output as suggested by Geoff [symbols_output.txt](https://github.com/mfem/mfem/files/4119291/symbols_output.txt), also included the whole output that I forgot earlier (similar messages)

### PR DESCRIPTION
**Pull request by jandrej**
This adds the missing files that are missing in the cmake build.

Fixes #1264

| PR | Author | Editor | Reviewers  | Assignment | Approval | Merge |
| --- | --- | --- | ---  | --- | --- | --- |
| https://github.com/mfem/mfem/pull/1265 | @jandrej  | @tzanio | @tzanio  + @adrienbernede   | 01/27/20 | 01/27/20 | 01/27/20 |

### CODE REVIEW

**Comment by tzanio** [comment]
@salazardetroya and @bslazarov, does this fix work for you?

**Comment by bslazarov** [comment]
I can compile without any problems

**Comment by v-dobrev** [comment]
Any idea why this was not caught by the appveyor ci?

**Comment by tzanio** [comment]
> Any idea why this was not caught by the appveyor ci?

Apparently that doesn't build examples in parallel: https://github.com/mfem/mfem/blob/master/.appveyor.yml#L43

**Comment by v-dobrev** [comment]
> > Any idea why this was not caught by the appveyor ci?
> 
> Apparently that doesn't build examples in parallel: https://github.com/mfem/mfem/blob/master/.appveyor.yml#L43
> 
> We should change that...

It seems like the missing files should also affect the serial build. If the serial build was fine, this may be due to the way symbols are resolved under windows+visual studio.

**Comment by salazardetroya** [comment]
Works for me. Thanks.

**Pull request merged**
