### PR TITLE
Add support for RAJA versions >= 0.12.0.

### PR DESCRIPTION
**Pull request by YohannDudouit**
| PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1743](https://github.com/mfem/mfem/pull/1743) | @YohannDudouit | @tzanio | @artv3 + @camierjs | 09/06/20 | ⌛due 09/15/20 | ⌛due 09/22/20 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
@YohannDudouit, you merged this branch into https://github.com/mfem/mfem/pull/1626, so it should be reviewed there. Unless you were planning on reverting the merge into that branch?

**Comment by artv3** [comment]
For this version, could we update to RAJA::Teams? We are seeing improved performance in some cases. Also perhaps add RAJA-HIP?

**Comment by YohannDudouit** [comment]
@v-dobrev From what I understand Raja is not supporting `mutable` lambdas, and it's not clear if they are willing to. In this context I think it is not reasonable to postpone this PR until there is a fix for Raja (which might never come). Would it cause a problem that this gets merged in next even though it's included in the other PR? I think #1626 might have to be abandoned because of the incompatibility with Raja, or at least postponed to avoid preventing `next` to compile.

@artv3 I'm not sure this PR is the best place to do this, I think it would make more sense to create a new PR, but I'm okay with it if you want to add code to this PR, it might delay the fix for raja v0.12.0 though.

**Comment by YohannDudouit** [comment]
@tzanio Do you know if I have to rewrite this PR because we "reverted" it since it was included in #1626 ?

**Comment by tzanio** [comment]
If it was merged in #1626, it will be better to re-write it, i.e. use new commits.

**Review by artv3 — APPROVED** [review]

**Comment by artv3** [comment]
Easy approval,  I just set up the following PR https://github.com/mfem/mfem/pull/1752 to use newer features of RAJA (though there might be more testing to do with that PR).

**Comment by YohannDudouit** [comment]
@artv3 Be careful, I might have to send new commits for this due to the reverted merge of #1626 .

**Comment by YohannDudouit** [comment]
I'm closing this in favor of #1752

**Pull request closed without merging**
