### PR TITLE
Change Add and ParAdd for hypre matrices to use hypre parcsradd

### PR DESCRIPTION
**Pull request by ben-s-southworth**
Addresses segfault raised here: https://github.com/mfem/mfem/issues/1238 and https://github.com/mfem/mfem/issues/1276 with suggestion by @liruipeng to use the hypre Parcsradd function. Runs successfully on the example I constructed that previously led to seg faults.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1305](https://github.com/mfem/mfem/pull/1305) | @ben-s-southworth | @tzanio | @jandrej + @acfisher | 03/12/20 | 03/27/20 | 03/31/20 | |

### CODE REVIEW

**Comment by ben-s-southworth** [comment]
@liruipeng What version of hypre was this version of hypre_parcsrAdd added in?

**Comment by v-dobrev** [comment]
It is probably best to keep the current implementations for older versions of hypre and use the new methods when using a new version of hypre. For example, if the new function was added in hypre 2.14.0 we can use:
```c++
#if MFEM_HYPRE_VERSION < 21400
   // code for hypre versions before 2.14.0
#else
   // code for hypre 2.14.0 and later
#endif
```
This way the PR will least disruptive.

**Comment by acfisher** [comment]
I agree with Veselin. We should address the HYPRE upgrade in it's own PR and handle all of those complexities in that PR.

**Comment by ben-s-southworth** [comment]
I agree with the version #if, just looking into which version of hypre this function was added in. Will update the PR when I figure it out.

**Comment by tzanio** [comment]
@jandrej and @acfisher what's the status of your reviews... do you need more time?

**Comment by jandrej** [comment]
LGTM

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
