### PR TITLE
Small bug fix: computation of H1/Hdiv/Hcurl for ParGridFunction

### PR DESCRIPTION
**Pull request by psocratis**
| PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2046](https://github.com/mfem/mfem/pull/2046) | @psocratis | @tzanio | @tzanio + @gillette7 | 02/09/21 | 02/11/21 | 02/15/21 | |

### CODE REVIEW

**Review by tzanio — APPROVED** [review]
Nice catch!

**Review by raphaelzanella — APPROVED** [review]
I tested ComputeH1Error.

**Review by gillette7 — APPROVED** [review]
A very subtle error - good you found this!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
