### PR TITLE
Shifted boundary method - Neumann boundary condition + multiple level sets

### PR DESCRIPTION
**Pull request by kmittal2**
This PR enables
- Neumann boundary conditions with the shifted boundary method.
- Multiple level sets to impose different shifted boundary conditions in different parts of the domain.

fittedshifted

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2448](https://github.com/mfem/mfem/pull/2448) | @kmittal2 | @tzanio | @vladotomov + @bslazarov | 08/06/21 | 10/29/21 | 10/31/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by vladotomov — APPROVED** [review]
Great job Ketan!
Some capabilities should be further improved, but the basic method is good for merging.

**Comment by tzanio** [comment]
@bslazarov -- your review is due

**Comment by tzanio** [comment]
is it fixed now?

**Comment by kmittal2** [comment]
> is it fixed now?

Yes should be resolved now.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
