### PR TITLE
MFEM2PUMI and PUMI2MEM field transfer for 2D Triangular Meshes

### PR DESCRIPTION
**Pull request by mortezah**
This pull request achieves the following:

1. Adds the tables needed to figure out relative orientation of pumi vs mfem simplex entities in one location (that is pumi.cpp)
2. Adds the necessary changes for the solution transfer of fields on 2D triangular meshes.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2060](https://github.com/mfem/mfem/pull/2060) | @mortezah | @tzanio | @tzanio + @YohannDudouit | 02/24/21 | 02/26/21 | 03/04/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
Reminder to mark this as `ready-for-review` when it is ready, see https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Review by YohannDudouit — APPROVED** [review]
This seems good to me, the code is very clean, I only ran `make test` to test it though.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
