### PR TITLE
Change to README.md and add license badge [shahzebsiddiqui:patch-1]

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**

### CODE REVIEW

**Comment by tzanio** [comment]
We have a similar badge in `CONTRIBUTING.md` is that not sufficient?

**Comment by shahzebsiddiqui** [comment]
This is license badge, actually what motivated this change was I was trying to capture all the CI badges for E4S products by looking at README and we should have badges in README since that's what github renders when someone visit the github page. You can certainly keep badges in contributing.md if you prefer.

The repo I am working on is called https://github.com/E4S-Project/e4s-ci-badges which shows all ci badges for e4s product

**Comment by tzanio** [comment]
Please use the following badges in your project (from `CONTRIBUTING.md`):

<a href="https://github.com/mfem/mfem/blob/master/LICENSE">License</a> <a href="https://travis-ci.org/mfem/mfem">Build Status</a> <a href="https://ci.appveyor.com/project/mfem/mfem">Build Status</a> <a href="https://mfem.github.io/doxygen/html/index.html">Doxygen</a>

```html
<a href="https://github.com/mfem/mfem/blob/master/LICENSE"><img alt="License" src="https://img.shields.io/badge/License-BSD-brightgreen.svg"></a>
<a href="https://travis-ci.org/mfem/mfem"><img alt="Build Status" src="https://travis-ci.org/mfem/mfem.svg?branch=master"></a>
<a href="https://ci.appveyor.com/project/mfem/mfem"><img alt="Build Status" src="https://ci.appveyor.com/api/projects/status/19non9sqm6msi2wy?svg=true"></a>
<a href="https://mfem.github.io/doxygen/html/index.html"><img alt="Doxygen" src="https://img.shields.io/badge/code-documented-brightgreen.svg"></a>
```

GitHub autodetects our license (and displays it as  `BSD-3-Clause License` at https://github.com/mfem/mfem).

**Comment by shahzebsiddiqui** [comment]
Okay i have added the badges for mfem in this PR: https://github.com/E4S-Project/e4s-ci-badges/pull/2 

I will add a contributing guide. Occasionally we would like if each team can update their ci badges when new CI pipelines or badges are reported in their project. Generally they are part of `README`. In any case you can merge or close this PR. I dont have any preference

**Pull request closed without merging**
