### PR TITLE
Remove duplicated code.

### PR DESCRIPTION
**Pull request by YohannDudouit**
This PR removes duplicated code in the different `Mult` and `AddMultTranspose` `FaceRestriction` methods, and factorize verification code that was inlined into a `CheckFESpace` method.

### CODE REVIEW

**Comment by YohannDudouit** [comment]
@v-dobrev @artv3 @rwa I would like to merge this PR into #2195 , it should make it easier to review as it only removes duplicated code, but I would like your approval first so that it's not too disruptive.

**Comment by rw-anderson** [comment]
Sounds good to me.

**Review by artv3 — APPROVED** [review]

**Comment by tzanio** [comment]
Please mark as `ready-for-review` when this is ready.

**Comment by v-dobrev** [comment]
> Please mark as `ready-for-review` when this is ready.

This PR is toward another branch/PR, #2195, so no need to mark as `ready-for-review`.

**Comment by v-dobrev** [comment]
@YohannDudouit, can you please fix the test failures before we merge this into #2195?

**Comment by YohannDudouit** [comment]
Thanks @v-dobrev , I didn't realize I had introduced a bug... All tests are now passing.

**Pull request merged**
