### PR TITLE
Improve memory movement in CheckFinite & DenseTensor(k)

### PR DESCRIPTION
**Pull request by tomstitt**
- `HostRead()` instead of `GetData()` in `CheckFinite` so that it works on device-only-valid objects

- Don't use non-const method from `const DenseTensor::operator()(k)` so we can avoid unnecessary `HostReadWrite()`s

For example in master this fails with `Assertion failed: (Empty() || ((flags & VALID_HOST) && (std::is_const<T>::value || !(flags & VALID_DEVICE)))) is false` during the 2nd call because the constness is lost:
```
DenseTensor t(...);
t.Read();
AsConst(t)(0, 0, 0); // Fine
AsConst(t)(0)(0, 0); // Fails
```

and while you can do:

```
DenseTensor t(...);
t.Read();
AsConst(t)(0, 0, 0); // Fine
t.HostReadWrite();
AsConst(t)(0)(0, 0); // Fine
```

it is not great for data movement

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3178](https://github.com/mfem/mfem/pull/3178) | @tomstitt | @tzanio | @camierjs + @artv3 | 9/16/22 | 9/16/22 | 9/20/22 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Review by artv3 — APPROVED** [review]
yes!

**Comment by artv3** [comment]
I approve, but testing has to pass.

**Comment by tzanio** [comment]
@tomstitt, there seems to be an issue with one of the TMOP tests

**Comment by tzanio** [comment]
> @tomstitt, there seems to be an issue with one of the TMOP tests

ping @tomstitt

**Comment by tomstitt** [comment]
> > @tomstitt, there seems to be an issue with one of the TMOP tests
> 
> ping @tomstitt -- please let us know if you need help resolving this

I dug into it a bit and the issue seems like a double-free/incorrect-alias, the issue is that the call to `at` [here](https://github.com/mfem/mfem/blob/master/general/mem_manager.cpp#L387) fails because the pointer no longer exists.

If I revert the non-const case all the tests pass locally, which is fine with me but it does feel like this should use the reference-based alias.

@camierjs the failure is happening in the `TMOP_Integrator` destructor, do you want to take a look or should we avoid changing `DenseMatrix &operator()(int k)` for now? 

*Reverting this change fixes things:*
```
    DenseMatrix &operator()(int k)
    {
       MFEM_ASSERT_INDEX_IN_RANGE(k, 0, SizeK());
-      Mk.data = Memory<double>(tdata, SizeI()*SizeJ()*k, SizeI()*SizeJ());
+      Mk.data = Memory<double>(GetData(k), SizeI()*SizeJ(), false);
```

**Comment by camierjs** [comment]
The line `AsConst(t)(0, 0, 0); // Fine` is in fact not that 'fine' and should trigger the `VALID_HOST` error, as it is a host read while the data has been moved to the device.

I've set up an additional test below, let me know if you agree and if we should add it here:
```
TEST_CASE("DenseTensor CheckFinite", "[DenseTensor][DebugDevice]")
{
#ifdef MFEM_USE_EXCEPTIONS
   Device debug("debug");
   mfem::set_error_action(ErrorAction::MFEM_ERROR_THROW);
   auto invalid_host_pointer_access = Contains("invalid host pointer access");

   DenseTensor t(2,3,4);
   for (int i=0; i<t.TotalSize(); ++i) { t.Data()[i] = i; }

   const double *host_adrs = t.Data();
   const double *device_adrs = t.Read();

   // Fine, if last access on device was Read
   REQUIRE_NOTHROW(AsConst(t)(0,0,0));

   // Fails if the last access on device was ReadWrite
   t.HostReadWrite(), t.ReadWrite();
   REQUIRE_THROWS_WITH(AsConst(t)(0,0,0), invalid_host_pointer_access);

   // Put back memory in Read mode
   t.HostRead(), t.Read();
   // Can use 'AsConst', as the memory flags are now in read
   REQUIRE_NOTHROW(assert(AsConst(t).Data() == host_adrs));
   REQUIRE_NOTHROW(assert(AsConst(t).Read() == device_adrs));

   // This one seem fine, but it must be a compiler optimization
   // this should fail, as we are reading in device memory
   REQUIRE_NOTHROW(AsConst(t)(0,0,0));
   t.ReadWrite(); // set back to rw mode to avoid MMU error
   // now this 'AsConst(t)(0,0,0)' triggers an 'invalid host pointer access'
   REQUIRE_THROWS_WITH([&]()
   {
      volatile double r = AsConst(t)(0,0,0);
      (void) r;
   }(), invalid_host_pointer_access);

   // back to the host, rw mode and do some sanity checks
   t.HostReadWrite();
   REQUIRE(t.Data() == host_adrs);
   REQUIRE_NOTHROW(AsConst(t)(0)(0,0));
   REQUIRE(AsConst(t)(0).Data() == host_adrs);
   REQUIRE(AsConst(t)(1).Data() == host_adrs + 1*t.SizeI()*t.SizeJ());
   REQUIRE_NOTHROW([&]() {volatile double r = AsConst(t)(0)(0,0); (void) r;}());

   auto rw_T = Reshape(t.ReadWrite(),2,3,4);
   REQUIRE_NOTHROW(MFEM_FORALL(i,1, rw_T(0,0,1) = M_PI;));
   REQUIRE_THROWS_WITH(t(0,0,1) = M_PI, invalid_host_pointer_access);

   // Fails, as we are reading in device memory
   REQUIRE_THROWS_WITH(AsConst(t)(0)(0,0), invalid_host_pointer_access);

   // back to host for verifications
   t.HostReadWrite();
   REQUIRE(t(0,0,1) == M_PI);
   REQUIRE(AsConst(t)(1)(0,0) == M_PI);
#endif // MFEM_USE_EXCEPTIONS
}
```

**Comment by tomstitt** [comment]
> The line `AsConst(t)(0, 0, 0); // Fine` is in fact not that 'fine' and should trigger the `VALID_HOST` error, as it is a host read while the data has been moved to the device.

We actually don't want this to be a `VALID_HOST` error but I should have made my original example more clear! What we are really doing is getting read-only views into `t` on the device then the host, like:

```
DenseTensor t(...);
const double * d_t = t.Read();
const double h_000 = AsConst(t)(0, 0, 0); // Fine
const DenseMatrix m_0 = AsConst(t)(0)(0, 0); // Fails
````

We have a number of cases where we setup some `t` once then use it read-only on the host, then read-only on the device, then read-only on the host, then read-only on the device, etc (mostly because we aren't fully GPU yet). Because `AsConst(t)(0)(0, 0)` fails we have to `HostReadWrite` `t` even though we only want a read-only view and even though we only had a read-only view on the device, which leads to the extra memcpys. Does that make sense?

**Comment by tomstitt** [comment]
I understand why this is okay:
```
   const double *host_adrs = t.Data();
   const double *device_adrs = t.Read();

   // Fine, if last access on device was Read
   REQUIRE_NOTHROW(AsConst(t)(0,0,0));
```

I understand why this is not okay/fails:
```
   // Fails if the last access on device was ReadWrite
   t.HostReadWrite(), t.ReadWrite();
   REQUIRE_THROWS_WITH(AsConst(t)(0,0,0), invalid_host_pointer_access);
```

I don't understand what you mean by `this should fail, as we are reading in device memory`. Since we `HostRead` then `Read` my understanding is that both the host and device are valid. If we then `AsConst(t)(0,0,0)` you are using the Memory's `[]` operator and that will just get you host memory right?
```
   // Put back memory in Read mode
   t.HostRead(), t.Read();
   // Can use 'AsConst', as the memory flags are now in read
   REQUIRE_NOTHROW(assert(AsConst(t).Data() == host_adrs));
   REQUIRE_NOTHROW(assert(AsConst(t).Read() == device_adrs));

   // This one seem fine, but it must be a compiler optimization
   // this should fail, as we are reading in device memory
   REQUIRE_NOTHROW(AsConst(t)(0,0,0));
```

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by camierjs — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
