### PR TITLE
Added backlog to the constructor of socketserver [fix-backlog-socketstream]

### PR DESCRIPTION
**Pull request by stefanozampini**
used backlog=4 for backward compatiblity

### CODE REVIEW

**Comment by tzanio** [comment]
Thanks @stefanozampini!

I think it is fine to switch to a larger default.

**Comment by stefanozampini** [comment]
It’s up to you. I’m not an expert of sockets. Let’s wait for Veselin’s advice
I was thinking that we could also read a .glvisrc configuration file when glvis is run to select the backlog value we want (are there other hidden parameters one can tweak?)

**Comment by stefanozampini** [comment]
Can I merge directly to master this simple change?

**Comment by v-dobrev** [comment]
We can increase the default value but I don't think it's necessary.

**Comment by v-dobrev** [comment]
I'm fine with merging the PR in `master`, just merge it in `next` as well.

**Comment by stefanozampini** [comment]
Instead of merging a single simple branch to next, you should consider regularly merge master in next.

**Comment by jedbrown** [comment]
I see that `git log next..master` contains only merges, which is good
(expected with this model).  It's still useful to merge 'master' into
'next' once in a while.  That shouldn't be an excuse for not merging
"small" branches through 'next' -- that's just laziness, which is a
valid reason when the risk is negligible.

**Comment by stefanozampini** [comment]
I've pushed to next as I'm not authorized to push to master

**Comment by dalcinl** [comment]
@v-dobrev Why do you think increasing the backlog is not necessary? When clients run in parallel, they suddenly flood the server with connection requests. Any incoming connection request that cannot be handled is put in a queue of max size backlog, once the queue is full the connection is rejected. Increasing the backlog should help a lot with improving the reliability of the glvis app for parallel runs. In fact, @stefanozampini was not longer able to break things (in his desktop machine) after he increased the backlog to the maximum size of 128 (this is the default max for Linux and Darwin kernels).

```
$ uname
Linux
$ sysctl net.core.somaxconn
net.core.somaxconn = 128
```

```
$ uname
Darwin
$ sysctl kern.ipc.somaxconn
kern.ipc.somaxconn: 128
```

**Comment by v-dobrev** [comment]
Hi @dalcinl,

I was just talking about the default value for the `socketserver` class - any application that's using it, like GLVis, can set its own backlog value. That's why I said, it is not necessary to increase the default - we can do it in GLVis. I don't really know what's a good default value in general - I assume that there is some sort of performance and/or resource limitation, seeing that the default maximum in both Linux and MacOS (128 as you pointed out) is a relatively small number. This was my reasoning to keep the default value in `socketserver` conservative.

That said, if you think that a default of `4` is too small, I'm not opposed to changing it. Feel free to change it.

**Comment by dalcinl** [comment]
@v-dobrev OK, sorry about the confusion, the default value should be kept small, however IMHO GLVis should use a larger value.

**Comment by tzanio** [comment]
According to the Internet, e.g. http://petzold.io/#!/p/somaxconn, the penalty may not be that big, especially on Linux. 

I'm OK either way, but it seems it is safe to have a larger default (it gets truncated to the system max). We should definitely increase the value in GLVis.

**Comment by v-dobrev** [comment]
@dalcinl, I agree - we should increase the backlog value in GLVis to something like 64 or 128 - do you want to make the update?

**Comment by dalcinl** [comment]
@v-dobrev I can do it once this PR lands in master. Are you planning to merge it soon?

**Comment by v-dobrev** [comment]
@dalcinl, I'm OK with merging it now. @tzanio, any objections to merge this now?

**Comment by tzanio** [comment]
Nope

**Pull request merged**
