### PR TITLE
PA for some more H(curl) integrators

### PR DESCRIPTION
**Pull request by dylan-copeland**
This PR adds PA support for `MixedScalarCurlIntegrator` in 2D and `MixedVectorGradientIntegrator` in 2D and 3D, as well as their transposes.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2856](https://github.com/mfem/mfem/pull/2856) | @dylan-copeland | @tzanio | @tzanio + @YohannDudouit | 3/1/22 | 3/2/22 | 3/3/22 | |

### CODE REVIEW

**Comment by pmocz** [comment]
I am leaving a comment per Tzanio's request to check whether MultTranspose() works with MixedVectorCurlIntegrator(), MixedVectorGradientIntegrator(), MixedScalarCurlIntegrator()

**Comment by dylan-copeland** [comment]
@pmocz This PR adds support for `MixedVectorGradientIntegrator` (2D and 3D) and `MixedScalarCurlIntegrator` (2D), as well as their transposes. In 3D, `MixedVectorWeakCurlIntegrator` can be used as the transpose of `MixedVectorCurlIntegrator`. It may be more convenient in some cases to have `AddMultTransposePA` supported in `MixedVectorCurlIntegrator`, and we can add that if needed. Please let us know if you are not able to simply use `MixedVectorWeakCurlIntegrator`, or if you need anything else.

**Comment by dylan-copeland** [comment]
@tzanio I don't know what the failing codecov check means.

**Comment by tzanio** [comment]
It means a lot of code was added without corresponding tests 😁

**Comment by dylan-copeland** [comment]
> It means a lot of code was added without corresponding tests 😁

I'm not sure how it counts testing, but I added more test cases to an existing unit test, completely covering the new features. Also, note that the unit tests pass on lassen.

**Comment by tzanio** [comment]
Maybe it is the changes in `master`... let me check

**Comment by tzanio** [comment]
Codecov looks good now

**Review by tzanio — APPROVED** [review]
Thanks @dylan-copeland !

**Review by pmocz — APPROVED** [review]

**Review by YohannDudouit — APPROVED** [review]
We may want to provide more optimized versions of the kernels later, but this looks good otherwise. Thanks for doing this @dylan-copeland !

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
