### PR TITLE
changed AMS smoothers; fixed CSRAdd

### PR DESCRIPTION
**Pull request by liruipeng**
1. Changed default AMS smoothers on GPUs to l1-Jacobi 
2. Changes due to interface changes of CSRMatrixAdd of hypre

### CODE REVIEW

**Comment by liruipeng** [comment]
Btw, does it make sense to you getting rid of this function in mfem https://github.com/mfem/mfem/blob/cd72cccf83383fa8e3f78e8bd97e59edd5619316/linalg/hypre_parcsr.cpp#L1776
but just use hypre's. They seem to have the same functionality, but hypre's does not have the scalability issue you commented and also supports GPU matrices.

**Comment by v-dobrev** [comment]
We use this when building with older hypre versions that did not have this function.

**Comment by v-dobrev** [comment]
I merged this directly in https://github.com/mfem/mfem/tree/hypre-cuda-dev (PR #1492), see 935dd857.

Thanks @liruipeng!

**Comment by tzanio** [comment]
Thanks for the quick fix @liruipeng !

**Pull request closed without merging**
