### PR TITLE
Load balancing with custom partitioning [custom-rebalance-dev]

### PR DESCRIPTION
**Pull request by jakubcerveny**
This PR addresses the request for user-defined ParNCMesh partitioning in #958.

A new overload `ParMesh::Rebalance(const Array<int> &partition)` is added. It takes an array of element-rank assignments which is used to migrate elements in any way the user needs. 

The old function `ParMesh::Rebalance()` should work exactly as before, with the default SFC based partitioning, like this for example (ex15p):

custom-part-0

However, the user can now specify any destination rank for each element, for example based on the X coordinate of the center of each element (surely a better algorithm can be devised):

custom-part-4

Custom partitioning may be more expensive than the default SFC algorithm, because it needs synchronous sends and a barrier. I have only tested this on a desktop.

### CODE REVIEW

**Comment by tzanio** [comment]
Thanks @jakubcerveny !

**Comment by tzanio** [comment]
@cwsmith, can you confirm if this works for you?

**Comment by cwsmith** [comment]
I don't see any issues with the interface and the demonstration in #1021 looks good. Thank you.

When I get back into this I'll work through #939 then test out `ParMesh::Rebalance(...)`.

**Comment by jakubcerveny** [comment]
I think this can be merged after testing in `next` since the changes are minimal in the API (new `Mesh::Rebalance` overload).

**Pull request merged**
