### PR TITLE
Reshape interface for Vector and Array

### PR DESCRIPTION
**Pull request by YohannDudouit**
Using incorrectly `GetData()`, `Read()`, `ReadWrite()` is the most common issue encountered by new `MFEM_FORALL` developers, this PR removes the need to extract the pointer from `Vector` and `Array` to instead directly use the `Vector` and `Array` with the `Reshape` function.

```c++
void foo(Vector &v)
{
  auto V = Reshape(v.ReadWrite(), ... );
}
```
becomes
```c++
void foo(Vector &v)
{
  auto V = Reshape(v, ... );
}
```
and
```c++
void foo(const Vector &v)
{
  auto V = Reshape(v.Read(), ... );
}
```
becomes
```c++
void foo(const Vector &v)
{
  auto V = Reshape(v, ... );
}
```

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1651](https://github.com/mfem/mfem/pull/1651) | @YohannDudouit | @tzanio | @camierjs + @pazner + @jakubcerveny + @v-dobrev | 08/25/20 | ⌛due 09/08/20 | ⌛due 09/15/20 | |

### CODE REVIEW

**Comment by camierjs** [comment]
Do you know the cost/implication of the added `mutable` qualifier for the lambda body?
This is something that needs to be looked at.

**Comment by camierjs** [comment]
And the `Write` only case should be also handled - which might be harder to distinguish.

**Comment by camierjs** [comment]
The interface looks much cleaner!

**Comment by YohannDudouit** [comment]
@camierjs My assumption would be that the `mutable` keyword has absolutely no cost, the difference is that the copy is done as you would expect instead of returning a `const` object. But I agree that we need to verify that it doesn't impact the performance.

**Comment by YohannDudouit** [comment]
@camierjs I don't think the `Write` case should be handled, it is a low level optimization I think.

**Comment by YohannDudouit** [comment]
Unfortunately, the type is not what I expected with the `auto`, in
```c++
void foo(const Vector &v)
{
  auto V = Reshape(v, ... );
}
```
`V` has type `DeviceTensor` and not `const DeviceTensor` because it is calling the copy constructor.
Therefore we would have to add `const` to `auto` to fully achieve what I wanted:
```c++
void foo(const Vector &v)
{
  const auto V = Reshape(v, ... );
}
```

**Comment by pazner** [comment]
> Unfortunately, the type is not what I expected with the `auto`, in
> 
> ```c++
> void foo(const Vector &v)
> {
>   auto V = Reshape(v, ... );
> }
> ```
> 
> `V` has type `DeviceTensor` and not `const DeviceTensor` because it is calling the copy constructor.
> Therefore we would have to add `const` to `auto` to fully achieve what I wanted:
> 
> ```c++
> void foo(const Vector &v)
> {
>   const auto V = Reshape(v, ... );
> }
> ```

Are you using this `const auto` anywhere?

**Comment by camierjs** [comment]
I definitely like that it is cleaner.

However, I'm not sure how that would 'prevent bugs' if we don't add the `const` in front of the `auto` for the `Read`s. Without it, an input might be written and we will miss the compilation error.

So it looks like we are trading a `Read` for a `const` - which might be ok.

Another issue I'm perhaps fore-looking is that `DeviceTensor` was for now a header only file. Using `Read` and `ReadWrite` from the `vector.hpp` will pull the `vector.o` ⇒ `libmfem.a`, leading to the need for `JIT` to relink with it, ⇒ it has to be compiled with `-fPIC` - which is something we might want to avoid.

**Comment by YohannDudouit** [comment]
@pazner I have #1653 that does just that, I preferred to separate the two PRs, but I can merge it with this one if desired.

@camierjs The way it prevents bugs is mostly by preventing users to have to know that `GetData()` does not work with `Reshape` and `MFEM_FOR_ALL`, and that there is a hidden interface `Read()`, `ReadWrite()`, and `Write()` that must be known. A few persons mentioned that it was very bug prone for them when they started writing GPU kernels.
Regarding the `const`, it is not required here, because the type is `DeviceTensor<const double, Dim>`, so the data is protected even without the `const` in front. It was a concern in the past because I introduced a new `Reshape` function that would have changed this behavior, but this `Reshape` function has been discarded.
I agree that we don't want this to impact negatively the JIT which is more important. Needing everything to be header only seems like a big constraint though, but I like it because it means more use of templates for writing modular code.

**Comment by pazner** [comment]
> @pazner I have #1653 that does just that, I preferred to separate the two PRs, but I can merge it with this one if desired.

I think it makes sense to merge that here, but it's up to you of course.

**Comment by YohannDudouit** [comment]
@tzanio You were correct, I had missed a few `const` for input `Vector`. I realized that I was saying something inaccurate during the meeting, it doesn't matter from a performance point of view if we use `Read()` or `ReadWrite()` to read the data. The performance difference is potentially between `ReadWrite()` and `Write()`. So omitting a `const` in the input parameters __will not have__ a performance impact, there is just a risk to modify something we should not, which is exactly the semantic of `const`.

**Comment by YohannDudouit** [comment]
@pazner @camierjs I used `Reshape` for the weights in the Setup kernels, it's more homogeneous like this.

**Comment by pazner** [comment]
Looks good to me. It would be great to do some performance regression testing (apropos the call today) just to be sure that nothing changed.

**Comment by camierjs** [comment]
You can still avoid a copy doing a `Read` vs `ReadWrite` when you just need the data on the device, but update (the BC for example) on the host (Host->Device->Host).

**Comment by YohannDudouit** [comment]
@pazner The potentially expensive cost is "reading" (i.e. host/device or device/host copy), both `Read()` and `ReadWrite()` result in the memory being read. Only `Write()` is potentially less expensive, but this PR doesn't modify this behavior.

**Comment by YohannDudouit** [comment]
@camierjs You're right, I didn't think about this case. `ReadWrite()` invalidates the memory whereas `Read()` does not.

**Comment by pazner** [comment]
> @pazner The potentially expensive cost is "reading" (i.e. host/device or device/host copy), both `Read()` and `ReadWrite()` result in the memory being read. Only `Write()` is potentially less expensive, but this PR doesn't modify this behavior.

One of the important points of performance regression would be to catch unintended or unexpected changes in performance, i.e. corner cases or other hard-to-predict behaviors that nevertheless could have performance implications.

I think this is something we should do for all PRs, not just this one. But this is a particularly good candidate because it touches a lot of performance critical code (yes, in a way that looks benign, but it's good to be sure).

**Comment by v-dobrev** [comment]
> it doesn't matter from a performance point of view if we use `Read()` or `ReadWrite()` to read the data

The performance implication for using `ReadWrite()` where only `Read()` is needed is that you may incur unnecessary host-device copies outside the current function if the data is being read by alternating between host and device reads.

**Comment by v-dobrev** [comment]
I, personally, as an "expert", prefer the clarity that the explicit calls to `Read()`, `ReadWrite()`, and `Write()` bring. Hiding these behind the `const` or non-`const` of the `Vector` parameter will make things a bit harder for me to follow and, I'd guess, *a lot harder* for non-"experts" to follow.

Also, when you can just write `auto X = Reashape(x, ...)`, it is much easier to forget to consider the implications of the implicit `Read()` or `ReadWrite()`. (As discussed previously, this can be a problem, from a performance point of view, in the case when `x` is non-`const` and when `Read()` or `Write()` are actually the correct/optimal choice.)

In this case, I'm not I sure I agree that a "shorter code" is a "cleaner code".

In any case, I'll be interested to hear what other people, who have written/used code like this, think: @artv3, @tomstitt, @stefanhenneking, @dylan-copeland, or anyone else.

**Comment by YohannDudouit** [comment]
ping: @rcarson3

**Comment by artv3** [comment]
> I, personally, as an "expert", prefer the clarity that the explicit calls to `Read()`, `ReadWrite()`, and `Write()` bring. Hiding these behind the `const` or non-`const` of the `Vector` parameter will make things a bit harder for me to follow and, I'd guess, _a lot harder_ for non-"experts" to follow.
> 
> Also, when you can just write `auto X = Reashape(x, ...)`, it is much easier to forget to consider the implications of the implicit `Read()` or `ReadWrite()`. (As discussed previously, this can be a problem, from a performance point of view, in the case when `x` is non-`const` and when `Read()` or `Write()` are actually the correct/optimal choice.)
> 
> In this case, I'm not I sure I agree that a "shorter code" is a "cleaner code".
> 
> In any case, I'll be interested to hear what other people, who have written/used code like this, think: @artv3, @tomstitt, @stefanhenneking, @dylan-copeland, or anyone else.

I agree with @v-dobrev here, I think there is clarity to having the developers making the Read, ReadWrite calls.

**Comment by v-dobrev** [comment]
Other than my comment above, the PR looks good. It will be a good addition for users that prefer the brevity and understand clearly the implications.

The mfem kernels (as something new users, looking to define their own kernels, are likely to read) may benefit from the more expressive use of `Read()`, `Write()`, and `ReadWrite()` but ultimately the new implementations seems to be exactly equivalent, so I'll be fine with the PR if the majority likes the changes.

**Comment by dylan-copeland** [comment]
I agree with @v-dobrev, and I like this PR. For clarity, `Read()` and `Write()` can be used, but for the simple cases described in the initial PR comment by @YohannDudouit this new interface is simpler and cleaner. I think the old and new interfaces should be used where appropriate.

**Comment by rcarson3** [comment]
For the regular users that just want to write kernels that can be used on the GPU, I think this will be a nice addition. I agree with the others that it's nice that the other versions are still around for those that want to revert to them for various use cases.

**Comment by jakubcerveny** [comment]
(Sorry for being late to review this) I am bit on the fence here. I think @v-dobrev's concerns are valid: there is a lot of value in the code being explicit. On the other hand, the code does look cleaner, which is also valuable. Still, one doesn't want to get to the state (which is easy with C++) where it's hard to tell what exactly is being called. Having multiple overloads that differ by small details makes the code actually harder to understand. That said, I don't have enough experience developing these kernels, so I'm hesitant to take a side here.

**Comment by YohannDudouit** [comment]
I understand that this PR is creating some concerns, I think the discussion in #1626 solves these concerns. I will be refactoring these two PRs (#1626 and #1651), taking into account the feedback.

**Comment by tzanio** [comment]
Can we delete this branch?

**Pull request closed without merging**
