### PR TITLE
Fix reading XML VTK meshes with zlib enabled [vtk-xml-fix]

### LINKED ISSUE #2094: gzstream seek and tell broken
I catched another minor bug, but this time I am not sure how to fix it, therefore the issue. Turns out ``ifgzstream``, ``named_ifgzstream``, ... do not correctly implement seeking and telling. Seek and tell is used when loading VTU meshes.

The issue should be reproducible by using GlVis to load any VTU mesh. If not, then it may be related to using clang with libc++ (instead of gcc with libstdc++).

### PR DESCRIPTION
**Pull request by pazner**
Resolves #2094.

Works around the problem of `named_ifgzstream` not supporting seeking and telling by passing the first line as a buffer prefix to the XML mesh reader.

Also improves the error message in the case of Julian's mesh. In this case, the mesh file had what is known as "raw appended data", which is raw binary data placed at the end of the XML file. This is not technically valid XML, and TinyXML (correctly) gives an error trying to parse it. (This is the reason why VTK format also allows base64 binary data, which is valid XML). The error message has been improved, so now it says:

```
MFEM abort: Could not parse XML VTK file. This could be caused by raw binary data in the XML file. MFEM supports only ASCII data.
```

If the XML file is parsed successfully, but binary data (base64 or otherwise) is encountered, a more helpful error message will also be given. In the future, we could work on supporting reading meshes with binary data if there is user demand.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2107](https://github.com/mfem/mfem/pull/2107) | @pazner | @tzanio | @jandrej + @v-dobrev + @bslazarov | 03/18/21 | 04/08/21 | 04/10/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by jandrej — APPROVED** [review]

**Comment by pazner** [comment]
> If the XML file is parsed successfully, but binary data (base64 or otherwise) is encountered, a more helpful error message will also be given. In the future, we could work on supporting reading meshes with binary data if there is user demand.

For those interested, this is now available in #2150 🙂

**Comment by tzanio** [comment]
@v-dobrev and @bslazarov the reviews for this PR are due. Can you take a quick look if you are interested?

**Review by bslazarov — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
