### PR TITLE
Five small changes to resolve memory leaks [bugfix/memcheck]

### PR DESCRIPTION
**Pull request by mlstowell**
I'm glad I volunteered to track these down because it seems I was responsible for 60% of the problems.

### CODE REVIEW

**Comment by mlstowell** [comment]
I should also mention that I could not confirm all of the memcheck errors from the nightly tests on my desktop machine.  Consequently, I cannot be sure that all of the issues have been addressed.  If other issues persist I'll be happy to track them down.

**Comment by pazner** [comment]
All of these changes look good to me. At some point it might be worth going through some of the examples and cleaning up the use of pointers where they are not needed (like you did in ex9), but that can be done later.

I haven't gotten a chance to run the tests myself. Once I do and confirm no leaks I'll comment back here.

**Comment by mlstowell** [comment]
No, `ex9p` was fine but I did double check that.

**Comment by v-dobrev** [comment]
@mlstowell,

The deletion of `faces_tbl` in `ParMesh::UniformRefinement3D()` was already addressed in #808.

**Comment by mlstowell** [comment]
Thanks, @v-dobrev ,  I noticed that but I didn't see that it was already `in-next`.  I can back out that change to avoid meaningless merge conflicts.

**Comment by v-dobrev** [comment]
@mlstowell, I think you created another branch called `bugfix-memcheck` (it currently points one commit behind `bugfix/memcheck`) -- do you need that?

**Comment by mlstowell** [comment]
@v-dobrev , no I meant to delete that.  Thanks for catching that.

**Comment by v-dobrev** [comment]
I'm testing this, and in addition to the memory leak addressed in #808 (`mesh.cpp:4641`), I see a leak at [`pncmesh.cpp:932`](https://github.com/mfem/mfem/blob/19672731c5574c9b5e05cb02444192ac8775937a/mesh/pncmesh.cpp#L932), according to valgrind. @jakubcerveny, do you have any suggestion how to fix that?

**Comment by tzanio** [comment]
@pazner, were you able to test this (if so, can you approve)?

**Comment by v-dobrev** [comment]
Why did you merge this? It has not gone through the weekend regression tests ...

**Comment by tzanio** [comment]
> Why did you merge this? It has not gone through the weekend regression tests ...

It is an important bugfix, which seems to resolve the issue... I don't think we should wait a week for bug fixes

**Pull request merged**
