### PR TITLE
Fix for issue 4107 in ParSubMesh

### PR DESCRIPTION
**Pull request by mlstowell**
This PR uncomments a pair of lines from a version of ParTransferMap predating the addition of ND/RT support. This appears to resolve issue #4107 but may introduce undesirable side effects in the parallel ND/RT support. An additional test may be needed to capture this type of failure with different field types.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4109](https://github.com/mfem/mfem/pull/4109) | @mlstowell | @tzanio | @psocratis + @jandrej | 2/3/24 | 2/6/24 | 2/9/24 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Review by psocratis — APPROVED** [review]

**Review by ryanblack129 — APPROVED** [review]
Thanks so much for fixing

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by mlstowell** [comment]
This fix does introduce a problem with the RT space. I've also looked at ND spaces and seen no issues there yet. I acknowledge that support for H1 spaces may be more urgent than ND and RT. If we choose to merge this fix before resolving the RT issue I'll create a separate PR focused on ND and RT support.

**Comment by psocratis** [comment]
> This fix does introduce a problem with the RT space. I've also looked at ND spaces and seen no issues there yet. I acknowledge that support for H1 spaces may be more urgent than ND and RT. If we choose to merge this fix before resolving the RT issue I'll create a separate PR focused on ND and RT support.

@mlstowell Can you share the example that the issue with RT spaces appears? I can also take a look

**Comment by mlstowell** [comment]
> 
> @mlstowell Can you share the example that the issue with RT spaces appears? I can also take a look

Happy for the assist. I put together ND and RT variants of `miniapps/multidomain/multidomain.cpp` mini app. I see trouble immediately when running:
```
mpirun -np 7 ./multidomain_rt -tf .002
```
Running with fewer processors seems fine. I have not seen any issues yet with `multidomain_nd` but perhaps I haven't tried the right combination.

I've also been thinking of putting together a unit test to catch this issue but I have something else I need to complete first.

**Comment by mlstowell** [comment]
FYI: The new ND and RT variants are not ready for inclusion in `master`. If people want to keep them I'd be happy to clean them up otherwise we can remove them before merging.

**Comment by psocratis** [comment]
> This fix does introduce a problem with the RT space. I've also looked at ND spaces and seen no issues there yet. I acknowledge that support for H1 spaces may be more urgent than ND and RT. If we choose to merge this fix before resolving the RT issue I'll create a separate PR focused on ND and RT support.

@mlstowell, I can also reproduce the issue with RT spaces. However, I see that the issue is there with and without the fix for the H1 spaces. So maybe we can push this fix soon and work on extending the fix for RT spaces as well on a separate PR (if we can't figure it out soon)

**Comment by mlstowell** [comment]
@psocratis, I'm glad you checked that. I didn't get a chance to. I think you have a good plan. We can merge this fix and I'll look closer at the RT issue.

**Comment by mlstowell** [comment]
I'll pull out the ND and RT variants of multidomain and use them in the next branch.

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
