### PR TITLE
Fix bug in FiniteElementSpace::GetRestrictionTransposeOperator

### LINKED ISSUE #2988: Potential memory leak in ParFiniteElementSpace::GetRestrictionOperator() ?
Folks, it looks like we are rebuilding `R_transpose = new TransposeOperator(R);` below for every GetRestrictionOperator() call:

https://github.com/mfem/mfem/blob/23cd6a78177e0bc17eef26da3f74e2c08ec2d9f1/fem/pfespace.cpp#L1211-L1213

Is this right? and could this be a memory leak?

### PR DESCRIPTION
**Pull request by pazner**
The transpose of the restriction operator is not the prolongation operator (even in serial). This can be seen, for example, on AMR meshes.
    
Also fixes a similar bug in `BilinearForm::GetOutputRestrictionTranspose` and adds a unit test to check correct behavior.

Also resolves #2988 (memory leak in the parallel nonconforming case).

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3821](https://github.com/mfem/mfem/pull/3821) | @pazner | @tzanio | @mlstowell + @psocratis | 8/12/23 | 9/19/23 | 9/24/23 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by v-dobrev** [comment]
We can try to resolve #2988 here too -- it is related to some extend.

**Comment by pazner** [comment]
If we wanted to, we could also use `unique_ptr` to avoid these kinds of memory leaks. The changes aren't too intrusive: https://github.com/mfem/mfem/compare/restriction-transpose-bugfix...restriction-transpose-bugfix-unique-ptr

**Comment by sebastiangrimberg** [comment]
Forgive me for chiming in here but I wanted to offer what I would view as a simplifying alternative here. It looks to me like the only purpose of having the `GetOutputRestrictionTranspose` and `GetRestrictionTransposeOperator` methods is because the `PADiscreteLinearOperatorExtension` is trying to keep using `Operator::SetupRAP` which is building a `RAPOperator` instead of just building a `TripleProductOperator` directly like done for `Operator::FormDiscreteOperator`. I'm not sure this was the best way of implementing it in the first place, as we are only constructing `Ro^T` so we can pass it to a method which computes a triple product as `Po^T A Pi = R A Pi`.

It seems to me to be more straightforward and helpful to reducing code complexity and bugs like these in the long run to just eliminating the construction or storage of `R^T` in the first place if it's only ever used as `(R^T)^T`.

I realize this is a huge diff to look through, but if you look at https://github.com/mfem/mfem/pull/3644, I made this change along with the larger change of removing the need for the `bilinearform_ext.hpp/cpp` classes to even have these `FormSystemMatrix`/`FormRectangularSystemOperator` methods. From `BilinearForm`/`MixedBilinearForm`/`DiscreteLinearOperator`, you can just call the base class `Operator` methods directly for the `ext` case to build the operator you need. For the case we are talking about here, it just looks like 

```
void DiscreteLinearOperator::FormDiscreteOperatorMatrix(OperatorHandle &A)
{
   if (ext)
   {
      Operator *oper;
      ext->FormDiscreteOperator(oper);
      A.Reset(oper);
      return;
   }
   ...
```

Anyway, I understand if you don't want to go this route, but I think it's a simpler and preferable adjustment and just wanted to express the alternative option.

**Comment by pazner** [comment]
Thanks for the input @sebastiangrimberg (your opinion is always welcome)!

I believe that one of the reasons that we explicitly keep around `R^T` (instead of just `R`) is because in parallel, the action of `R^T` can be computed using `ConformingProlongationOperator` or `DeviceConformingProlongationOperator`. In this case, `R^T` is actually the "primitive" operator, and `R` is actually just a `TransposeOperator` wrapper. In this situation, if you formed `TransposeOperator(R)`, it would actually be `((R^T)^T)^T` (which isn't the end of the world, but it is a little weird). Providing access to `R^T` directly avoids stacking transposes in this way.

I didn't follow completely your suggestion. When you write `Po^T A Pi = Ro A Pi`, part of the issue (and the bug that is fixed in this PR) is that `Po^T` and `Ro` are not the same.

**Comment by sebastiangrimberg** [comment]
> I didn't follow completely your suggestion. When you write Po^T A Pi = Ro A Pi, part of the issue (and the bug that is fixed in this PR) is that Po^T and Ro are not the same.

Sorry, what I meant was: Currently the code `PADiscreteLinearOperatorExtension::FormRectangularSystemOperator` uses `GetOutputRestrictionTranspose` (`Ro^T`) and passes it to `SetupRAP(Operator *Pi, Operator *Po)` which computes `Po^T A Pi` (names local to the function scope, not referring to the `FiniteElementSpace` objects). Thus `SetupRAP` computes `Ro A Pi` (`FiniteElementSpace` objects). Indeed `Po^T` and `Ro` from the `FiniteElementSpace` are not the same, I was referring to `Po` the local name inside `SetupRAP`, an alias for `Ro^T` as called). Hopefully that clarifies the confusion.

 I think in the end you still understood my point. I did not remember that about the `ConformingProlongationOperator` optimization from https://github.com/mfem/mfem/pull/1761. I was always curious if this ever actually profiled and shown to provide any meaningful improvement than just always having the restriction operator as a `SparseMatrix`. But anyway if you do want to directly build `R^T` using the `ConformingProlongationOperator` then supplying `R` via a `TransposeOperator` would still be cleaner in my opinion. Basically my argument is that I am pretty sure no one outside of the `FiniteElementSpace` should ever need `R^T` as an operation and the API and usage should reflect that.

**Comment by pazner** [comment]
Thanks — yes, that definitely makes sense.

In the big picture, I agree with you, and I would be fine removing (or deprecating) the APIs that deal with the restriction transpose operator. It's pretty clear that these are not frequently used, and they are a bit confusing from an interface point of view.

There are some instances where the transpose of the restriction is needed (e.g. when dealing with dual vectors, this came up in #3557), but it's relatively infrequent.

**Comment by sebastiangrimberg** [comment]
Thanks!

Yes indeed it seems like for the cases where people really need `R^T`, like in #3557, they can just use `GetRestrictionOperator` with `MultTranspose` (as #3557 already does). Since both the `SparseMatrix` and `TransposeOperator(*ConformingProlongationOperator)` representations of `R` have a `MultTranspose`, this would support `y = R^T x`. That way `FiniteElementSpace`/`ParFiniteElementSpace` can simplify their API without messing up user code.

Speaking for myself this would certainly be a nice simplification and improvement to some core library code!

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by psocratis — APPROVED** [review]

**Comment by tzanio** [comment]
ping: @mlstowell

**Review by mlstowell — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
