### PR TITLE
Split Mesh Explorer partition and material handling

### LINKED ISSUE #2062: Mesh Explorer miniapp attribute inconsistency
Hi together,

I found an inconsistency in the mesh explorer when running the mesh explorer "serial", i.e. via
```bash
miniapps/meshing/mesh-explorer -m mesh
```
then "m" shows the actual attributes. However, if we run it in "parallel", i.e. via
```
miniapps/meshing/mesh-explorer -np 16 -m mesh
```
then for "m" instead of the attributes the partitioning is presented, which is also a nice to have, but we cannot actually check for attributes with the miniapp anymore.

### PR DESCRIPTION
**Pull request by termi-official**
Resolves #2062 .

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2081](https://github.com/mfem/mfem/pull/2081) | @termi-official | @tzanio | @tzanio + @mlstowell | 03/04/21 | 03/15/21 | 03/18/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
LGTM

**Review by tzanio — APPROVED** [review]
Thank you @termi-official!

Please mention in `CHANGELOG`

**Comment by termi-official** [comment]
Thanks Tzanio! Sorry, I really forgot the changelog again. It is included now.

**Comment by tzanio** [comment]
No worries, thank you.

**Review by mlstowell — APPROVED** [review]

**Comment by tzanio** [comment]
LGTM

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
LGTM

**Pull request merged**
