### PR TITLE
Let's forget about 2020

### PR DESCRIPTION
**Pull request by adrienbernede**
Update 2020 to 2021 in copy-right headers.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2021](https://github.com/mfem/mfem/pull/2021) | @adrienbernede | @tzanio | @tzanio + @v-dobrev + @acfisher | 01/28/21 | 02/02/21 | 02/03/21 | |

### CODE REVIEW

**Comment by adrienbernede** [comment]
Modifies a large number of files, hence the failure in Travis.

**Review by tzanio — APPROVED** [review]
Thanks for updating this @adrienbernede.

We just have to be on the lookout for new files with 2020 in the current PRs.

**Comment by adrienbernede** [comment]
@tzanio I felt it was a good timing (hope you like the PR number ;) ).

**Comment by tzanio** [comment]
Yep, I noticed that 😁

**Comment by tzanio** [comment]
@acfisher and @v-dobrev, it will be preferable if this PR is approved and merged quickly (since it changes many files)

**Review by v-dobrev — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
@adrienbernede, can you please help monitor that no files with 2020 copyrights are introduced in master (e.g. from current PRs).

**Comment by adrienbernede** [comment]
@tzanio I'm thinking of creating a small Github action for it and push it. Would that work for you?

**Comment by tzanio** [comment]
Sure

**Pull request merged**
