### PR TITLE
[WIP] Update TRT branch to MFEM master

### PR DESCRIPTION
**Pull request by ben-s-southworth**
Merged trt-dev-new with MFEM master and AIR branch. No major conflicts in merge, and Terry's //ADDED// comments made it easy to see what was different in trt-dev-new.

Few outstanding issues:
- The `GetGhostTransformation()` function had to change argument types to
```
ParMesh::GetGhostFaceTransformation(FaceElementTransformations* FETr, 
                                         IsoparametricTransformation &FaceTransformation,
                                         Element::Type face_type, Geometry::Type face_geom)
```
Previously, the last two arguments were integers. This will have to be changed accordingly anywhere in the LDRD code. 

- Also, `Table group_sface;` is no longer a member of the Parmesh class. I added it back to make sure everything else would compile, but the added function `GetSharedFacesInGroups()` returns `group_sface` in 3d, so this still needs to be addressed. 

- New MFEM requires C++11 to compile. I thought I had added that to the default CXX flags, but this is not used in builder.py for MFEM. Adding -std=c++11 to the optim flags solves this problem: `configStr = addConfigArg(configStr,"OPTIM_FLAGS='-O3 -std=c++11'")`

### CODE REVIEW

**Comment by vladotomov** [comment]
Is trt_merge = trt_dev + master + pair?

What is trt_dev_new?

**Comment by ben-s-southworth** [comment]
Yes, trt_merge = trt_dev + pAIR, and the pAIR branch had master merged into it in August sometime. I wanted to get the ball rolling to have our branches up to date, but ran into a few problems mentioned above. I think trt_dev_new is almost the same as trt_dev, but had some updated solver/LU stuff.

**Comment by tzanio** [comment]
Folks, just curious -- what is the status of this?

**Comment by tzanio** [comment]
ping: @terryhaut

**Comment by tzanio** [comment]
@ben-s-southworth, should we also delete the `trt-merge` branch?

**Comment by ben-s-southworth** [comment]
> @ben-s-southworth, should we also delete the `trt-merge` branch?

I am copying a few commits off right now but will delete when I am done.

**Pull request closed without merging**
