### PR TITLE
Two fixes to improve autotest CI

### PR DESCRIPTION
**Pull request by adrienbernede**
This PR fixes two things:

- Remove a remaining ".txt" extension that prevented the diffs to appear correctly.
- Simplify the rules under which the autotest report jobs run.

For the autotest rules, the choice is to run the reports only if `AUTOTEST` variable is set to `YES` in CI. In practice, this is done in the settings of the `scheduled pipeline`. No other pipeline, even for `master` or `next` will commit to autotest without this variable set.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2325](https://github.com/mfem/mfem/pull/2325) | @adrienbernede | @tzanio | @tzanio + @jandrej | 06/11/21 | 06/11/21 | 06/11/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]
Thanks @adrienbernede !

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
LGTM

**Pull request merged**
