### PR TITLE
Use shared actions

### PR DESCRIPTION
**Pull request by adrienbernede**
Sharing Github Actions in a dedicated repo to avoid duplication with Laghos, Remhos and GLVis.

Related work:
https://github.com/mfem/mfem-actions
https://github.com/GLVis/glvis/pull/164
https://github.com/CEED/Remhos/pull/30
https://github.com/CEED/Laghos/pull/143

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2146](https://github.com/mfem/mfem/pull/2146) | @adrienbernede | @tzanio | @tzanio + @pazner | 04/08/21 | 04/09/21 | 04/10/21 | |

### CODE REVIEW

**Comment by adrienbernede** [comment]
Unless there is a fundament disagreement of the strategy (sharing actions in a separate repo), I think this is straightforward enough to be merged for 4.3.

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by pazner — APPROVED** [review]
Looks like a good way to reuse actions/reduce duplication. Thanks @adrienbernede!

**Review by tzanio — APPROVED** [review]
Thanks @adrienbernede !

**Comment by tzanio** [comment]
I have a slight preference for naming the new repo just `actions`, similar to the current `web` and `downloads`, but that's not critical to me.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by pazner** [comment]
> I have a slight preference for naming the new repo just `actions`, similar to the current `web` and `downloads`, but that's not critical to me.

Or maybe `github-actions` just for clarity?

**Comment by adrienbernede** [comment]
OK, I’ll do that now since it will impact all the related PRs.

**Comment by tzanio** [comment]
Re-merged in `next` for testing ...

**Comment by adrienbernede** [comment]
I just found out that one of the workflows (the main one: builds_and_tests) was failing because of a syntax error.
However, this kind of failure does not appear in the tests summary, and does not result in a global "failure" status.
I will report this to GitHub, while fixing the error in this branch.

**Comment by tzanio** [comment]
Re-merged in `next` for testing ...

**Pull request merged**
