### PR TITLE
Use a standard C function to define a coefficient [lib_coeff_dev]

### PR DESCRIPTION
**Pull request by IdoAkkerman**
This can be a useful way to specify c-functions  as input for for instance miniapps without the need to recompile.

### CODE REVIEW

**Comment by IdoAkkerman** [comment]
Building on windows probably requires the following packages:
https://github.com/dlfcn-win32/dlfcn-win32

Is this desirable, or complicates things to much? Reject PR?

**Comment by tzanio** [comment]
I am inclined to reject, but I'd like to hear first from @v-dobrev.

It seems to me if the users want to be able to change coefficients without rebuilding, they will be more interested in input files where the function can be edited directly, e.g. as we do in BLAST where the initial/boundary conditions (and more) are provided via Lua functions...

**Comment by v-dobrev** [comment]
As it is, I think that classes like this are better suited for the applications built on top of MFEM.

If this class is split into two separate classes: one `Coefficient` subclass that takes pointer to a function with a signature like this:
```c++
double func(int dim, const double *x, double t); // time dependent coefficient
```
or like this:
```c++
double func(int dim, const double *x); // time independent coefficient
```
and then another class or function that handles the dynamic library loading, then the first one can definitely go in MFEM.

However, I think it's best to keep the second one outside of MFEM.

**Comment by tzanio** [comment]
@IdoAkkerman, I will reject this version. You can resubmit if you want as @v-dobrev suggested above, or just keep that class as part of your application.

**Pull request closed without merging**
