### PR TITLE
Rearrange sample runs in ex6p [ex6p-runs-dev]

### PR DESCRIPTION
**Pull request by jakubcerveny**
After merging #2038, I would like to modify the sample runs in `ex6p` so that:

* The most representative runs are at the top.
* Conforming runs, which are much less useful due to the lack of load balancing, should be scarce and not at the top.
* `star-hilbert.mesh` is used instead of `star.mesh` because of ordering.
* Runs that benefit from coarse mesh reordering use the new `-rm` option.

I realize this interferes with autotesting but hopefully with no other changes in the PR this will be more manageable.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2105](https://github.com/mfem/mfem/pull/2105) | @jakubcerveny | @tzanio | @tzanio + @v-dobrev | 03/17/21 | 03/25/21 | 03/27/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Comment by v-dobrev** [comment]
This is not just re-arranging the sample runs.

I'd suggest splitting this in 2 steps (in whichever order you prefer): 1) re-arrange sample runs, 2) modify (any string modification) and add new sample runs without changing their order. Mixing them makes it a pain to track in the autotests.

**Comment by jakubcerveny** [comment]
Yes, the runs are also modified. I can split this into two PRs, but I don't see why that would be useful - in all cases the autotest outputs will differ (a lot). What is it that we want to track in the diffs?

**Comment by tzanio** [comment]
Unless there are errors, I will be OK if we just merge this in master and update the baselines after 1 day of testing

**Comment by tzanio** [comment]
@jakubcerveny, can you split in two PRs as @v-dobrev suggested above?

This will make it easier to review, and ultimately may go in faster.

**Comment by jakubcerveny** [comment]
OK the runs are now only rearranged in this PR. I will make a follow-up PR that will actually change the runs.

**Comment by tzanio** [comment]
Thank you

**Review by tzanio — APPROVED** [review]

**Review by tzanio — APPROVED** [review]

**Review by v-dobrev — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
