### PR TITLE
Lapack generalized eigenvalue systems

### PR DESCRIPTION
**Pull request by psocratis**
- [x] Add LAPACK interface needed for fractional PDE examples.
- [x] Modify `DenseMatrixSVD` to optionally return singular vectors.
- [x] Add some unit tests.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2844](https://github.com/mfem/mfem/pull/2844) | @psocratis | @tzanio | @cjvogl + @jwang125 | 2/22/22 | 3/12/22 | 3/13/22 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by cjvogl** [comment]
Documenting my review progress here:
- [x] read through code changes
- [ ] confirm code builds with MFEM_USE_LAPACK enabled
- [ ] run unit tests

**Comment by tzanio** [comment]
@jwang125, can you please review if you have a few minutes?

**Comment by jwang125** [comment]
Yes!

**Comment by jwang125** [comment]
Compiled and ran the tests and all passed. Options: `MFEM_USE_MPI=ON` and `MFEM_USE_LAPACK=ON`. One note: I need set `MFEM_ENABLE_MINIAPPS` on to pass all 107 tests when MPI is also on.

**Review by jwang125 — APPROVED** [review]
No errors detected.

**Comment by tzanio** [comment]
Thanks Frank!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
