### PR TITLE
Small improvements in CEED unit tests [ceed-tests-update]

### PR DESCRIPTION
**Pull request by v-dobrev**
In `makefile`, make sure files in `tests/unit/ceed` are included when calling `make style`.

Make sure the CEED unit tests are properly built when using an out-of-source GNU make build.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1866](https://github.com/mfem/mfem/pull/1866) | @v-dobrev | @tzanio | @tzanio + @YohannDudouit | 04/14/21 | 04/15/21 | 04/18/21 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
@YohannDudouit, I was running the libCEED unit tests and they were taking a very long time, e.g. the `cuda-*` backends took more than 15 min to run, each. Am I doing something wrong, or was this intentional?

**Comment by tzanio** [comment]
> @YohannDudouit, I was running the libCEED unit tests and they were taking a very long time, e.g. the cuda-* backends took more than 15 min to run, each. Am I doing something wrong, or was this intentional?

We need to do something about this, maybe have a separate "extensive tests" vs "quick tests" target, or maybe removing some of the unit tests from `make tests`.

On my tux box, here is the result of `make unittest` with the libCEED + debug + cuda build of MFEM:

```
    Unit tests [ unit_tests ... ]: OK  (255.53s 82364kB)
    Unit tests [ sedov_tests_cpu ... ]: OK  (8.28s 18280kB)
    Unit tests [ sedov_tests_debug ... ]: OK  (9.80s 19580kB)
    Unit tests [ sedov_tests_cuda ... ]: OK  (3.98s 730136kB)
    Unit tests [ sedov_tests_cuda_uvm ... ]: OK  (5.00s 726476kB)
    Unit tests [ cunit_tests ... ]: OK  (142.83s 790864kB)
    CEED Unit tests (cpu) [ ceed_tests ... ]: OK  (320.29s 224992kB)
    CEED Unit tests (cuda-ref) [ ceed_tests ... ]: OK  (682.00s 940948kB)
    CEED Unit tests (cuda-shared) [ ceed_tests ... ]: OK  (718.90s 941072kB)
    CEED Unit tests (cuda-gen) [ ceed_tests ... ]: OK  (792.19s 987764kB)
```

That's about 49 minutes for just the unit tests... I don't think any user will wait for that

**Comment by tzanio** [comment]
It is even worse in parallel:

```
    Parallel unit tests [ mpirun -np 1 punit_tests ... ]: OK  (11.49s 41456kB)
    Parallel unit tests [ mpirun -np 4 punit_tests ... ]: OK  (3.44s 28044kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_cpu ... ]: OK  (8.31s 23912kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_cpu ... ]: OK  (3.33s 22552kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_debug ... ]: OK  (10.12s 25468kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_debug ... ]: OK  (5.65s 24148kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_cuda ... ]: OK  (4.24s 732700kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_cuda ... ]: OK  (48.27s 732984kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_cuda_uvm ... ]: OK  (4.57s 733240kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_cuda_uvm ... ]: OK  (99.13s 749536kB)
    Unit tests [ unit_tests ... ]: OK  (249.33s 83240kB)
    Unit tests [ sedov_tests_cpu ... ]: OK  (8.06s 19168kB)
    Unit tests [ sedov_tests_debug ... ]: OK  (9.88s 20352kB)
    Unit tests [ sedov_tests_cuda ... ]: OK  (4.12s 738904kB)
    Unit tests [ sedov_tests_cuda_uvm ... ]: OK  (4.94s 728756kB)
    Unit tests [ cunit_tests ... ]: OK  (147.35s 793232kB)
    CEED Unit tests (cpu) [ ceed_tests ... ]: OK  (318.19s 225792kB)
    CEED Unit tests (cuda-ref) [ ceed_tests ... ]: OK  (676.96s 938420kB)
    CEED Unit tests (cuda-shared) [ ceed_tests ... ]: OK  (732.75s 938608kB)
    CEED Unit tests (cuda-gen) [ ceed_tests ... ]: OK  (792.79s 985452kB)
```

(Keep in mind this is a relatively powerful machine)

**Comment by YohannDudouit** [comment]
I'm open to propositions, I can remove any test that we find unnecessary.

**Comment by tzanio** [comment]
For the record, here is what I get in parallel with a non-debug build:

```
    Parallel unit tests [ mpirun -np 1 punit_tests ... ]: OK  (1.02s 40140kB)
    Parallel unit tests [ mpirun -np 4 punit_tests ... ]: OK  (0.67s 26748kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_cpu ... ]: OK  (1.09s 22936kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_cpu ... ]: OK  (0.56s 21484kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_debug ... ]: OK  (1.85s 24460kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_debug ... ]: OK  (2.24s 23144kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_cuda ... ]: OK  (3.61s 731240kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_cuda ... ]: OK  (47.78s 731524kB)
    Parallel unit tests [ mpirun -np 1 psedov_tests_cuda_uvm ... ]: OK  (3.92s 731692kB)
    Parallel unit tests [ mpirun -np 4 psedov_tests_cuda_uvm ... ]: OK  (108.23s 747188kB)
    Unit tests [ unit_tests ... ]: OK  (18.67s 82404kB)
    Unit tests [ sedov_tests_cpu ... ]: OK  (0.90s 18272kB)
    Unit tests [ sedov_tests_debug ... ]: OK  (1.65s 19452kB)
    Unit tests [ sedov_tests_cuda ... ]: OK  (3.45s 730604kB)
    Unit tests [ sedov_tests_cuda_uvm ... ]: OK  (4.28s 735532kB)
    Unit tests [ cunit_tests ... ]: OK  (10.69s 791596kB)
    CEED Unit tests (cpu) [ ceed_tests ... ]: OK  (34.21s 224652kB)
    CEED Unit tests (cuda-ref) [ ceed_tests ... ]: OK  (372.19s 937264kB)
    CEED Unit tests (cuda-shared) [ ceed_tests ... ]: OK  (408.81s 937408kB)
    CEED Unit tests (cuda-gen) [ ceed_tests ... ]: OK  (460.89s 984212kB)
```

**Comment by v-dobrev** [comment]
I'll mark this as `ready-for-review` now -- the long runtime of the CEED tests can be addressed in a separate PR.

**Comment by v-dobrev** [comment]
LGTM

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]

**Review by YohannDudouit — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
