### PR TITLE
[WIP] Block operator issue with GPU for blocks of size 0

### PR DESCRIPTION
**Pull request by stefanhenneking**
@dylan-copeland observed an issue with the block operator on GPU when a block size is 0. A reproducer (`examples/ex5p_blockop`) shows the problem: for example, `lrun -n 4 ./ex5p_blockop -r 2 -pa -d cuda` on `Ray`.

<details>

<summary>lrun -n 4 ./ex5p_blockop -r 2 -pa -d debug</summary>

```
Options used:
   --mesh ../data/star.mesh
   --refine 2
   --order 1
   --serial-format
   --partial-assembly
   --device debug
   --visualization
   --no-adios2-streams
Device configuration: debug,cpu
Memory configuration: host-debug,device-debug
Mesh::GeneratePartitioning(...): edgecut = 38


Assertion failed: (bytes <= alias.bytes) is false:
 --> internal error
 ... in function: void *mfem::MemoryManager::GetAliasDevicePtr(const void *, size_t, bool)
 ... in file: general/mem_manager.cpp:1208

***********************************************************
dim(R) = 41280
dim(W) = 20480
dim(R+W) = 61760
***********************************************************


Assertion failed: (bytes <= alias.bytes) is false:
 --> internal error
 ... in function: void *mfem::MemoryManager::GetAliasDevicePtr(const void *, size_t, bool)
 ... in file: general/mem_manager.cpp:1208



Assertion failed: (bytes <= alias.bytes) is false:
 --> internal error
 ... in function: void *mfem::MemoryManager::GetAliasDevicePtr(const void *, size_t, bool)
 ... in file: general/mem_manager.cpp:1208

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 3 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------


Assertion failed: (bytes <= alias.bytes) is false:
 --> internal error
 ... in function: void *mfem::MemoryManager::GetAliasDevicePtr(const void *, size_t, bool)
 ... in file: general/mem_manager.cpp:1208

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```
</details>

This PR is for fixing this issue.

### CODE REVIEW

**Comment by stefanhenneking** [comment]
The following code snippet reproduces the issue that occurs in the BlockOperator:

```
   int vsize = 100;
   Vector v(vsize); v.UseDevice(true); v = 1.0;
   Vector v1, v2; 
   v1.MakeRef(v, 0, 0); 
   v2.MakeRef(v, 0, vsize);
   v2.ReadWrite();
```

On `v2.ReadWrite()`, the following error message in printed:

```
Assertion failed: (bytes <= alias.bytes) is false:
 --> internal error
 ... in function: void *mfem::MemoryManager::GetAliasDevicePtr(const void *, size_t, bool)
 ... in file: general/mem_manager.cpp:1208
```

@dylan-copeland One possible solution is to ensure that aliases are only created with non-zero size and distinct offsets. This should be easy to ensure in the `BlockVector::Update` for this particular case (where `BlockOperator` causes this problem when using blocks of size 0), and I can certainly add that fix in this PR.

@v-dobrev Is the behavior above expected? The error message that is printed here seems a bit confusing.

**Comment by stefanhenneking** [comment]
@v-dobrev As a follow-up question: the code snippet
```
   Vector v;
   v.SetSize(0);
   v.Read();
   v.SetSize(100);
```
results in an error
```
MFEM abort: internal error
 ... in function: static mfem::MemoryType mfem::MemoryManager::GetDeviceMemoryType_(void *)
 ... in file: general/mem_manager.cpp:913
```
which to me looks like a bug.

**Comment by v-dobrev** [comment]
The checks using the alias `bytes` field can simply be removed I think. This is what I also suggested earlier here: https://github.com/mfem/mfem/pull/1646#discussion_r461216734. Another possibility is to update the `bytes` field to be the largest value from all different aliases using that address but I'm not sure how useful that will be.

The other issue has to do with how we deal with size 0 `Memory` objects -- they are not registered since (at least by default) the host pointer is `NULL`, so we cannot really store its "device" memory type. It seems easier to just have `Read()` return `NULL` and keep the `Memory` flagged as not registered and still just valid on host. That should allow safe re-allocation with the larger size (on host) and the device allocation will actually happen when the larger `Memory` is used. This will probably require just a simple tweak in the `Read`, `ReadWrite`, and `Write` methods in the `Memory` class.

**Comment by stefanhenneking** [comment]
@tzanio I closed this stale PR -- it hasn't been worked on or been referenced in any issue for quite a while.

**Pull request closed without merging**
