### PR TITLE
Expose DiagonalPolicy to the user interface

### PR DESCRIPTION
**Pull request by agrayver**
This PR merely enables a user to choose DiagonalPolicy introduced in #340 when assembling the system matrix. The default parameter value of DIAG_KEEP ensures backward compatibility.

### CODE REVIEW

**Comment by v-dobrev** [comment]
I think the interface will be cleaner if the diagonal policy for the `BilinearForm` is set with a separate method, instead of adding it as a parameter to multiple methods.

What do you guys think about this alternative?

**Comment by tzanio** [comment]
> I think the interface will be cleaner if the diagonal policy for the BilinearForm is set with a separate method, instead of adding it as a parameter to multiple methods.

I'm OK with that approach too... no strong preference.

**Comment by agrayver** [comment]
> What do you guys think about this alternative?

I agree. I have changed the code accordingly.

**Comment by v-dobrev** [comment]
Thanks, @agrayver!

**Pull request merged**
