### PR TITLE
Add additional caliper macros

### PR DESCRIPTION
**Pull request by artv3**
These sweet caliper macros will make profiling a breeze. 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2467](https://github.com/mfem/mfem/pull/2467) | @artv3 | @tzanio | @bslazarov + @tzanio | 08/17/21 | 08/17/21 | 08/18/21 | |

### CODE REVIEW

**Review by tomstitt — APPROVED** [review]

**Comment by v-dobrev** [comment]
Don't forget to add the `ready-for-review` label when ready.

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]
Thanks @artv3!

**Comment by bslazarov** [comment]
@artv3 - It will be nice to have the scope annotation in some of the examples.

**Comment by artv3** [comment]
> @artv3 - It will be nice to have the scope annotation in some of the examples.

Done!

**Review by bslazarov — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
