### PR TITLE
Testing travis feedback with allows failures [Optional test]

### PR DESCRIPTION
**Pull request by adrienbernede**
Just a test
Puts optional checks in a "allow_failures" section.
Interesting if [travis adds a "success with warnings" status](https://github.com/travis-ci/travis-ci/issues/4730).

### CODE REVIEW

**Comment by tzanio** [comment]
I assume this didn't work?

**Comment by adrienbernede** [comment]
No, allow_failures will let the global status be "success". That’s why I participate in pushing for a new ["success with warnings" status in Travis](https://github.com/travis-ci/travis-ci/issues/4730), just like it exists in gitlab.

**Comment by tzanio** [comment]
Do you still need the PR and the branch then?

**Comment by adrienbernede** [comment]
No I can keep it "at home" for later :).

**Pull request closed without merging**
