### PR TITLE
 Fixes for AmgX solver class memory leaks

### PR DESCRIPTION
**Pull request by artv3**
An effort for issue https://github.com/mfem/mfem/issues/2027 .

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2047](https://github.com/mfem/mfem/pull/2047) | @artv3 | @tzanio | @tzanio + @barker29 | 02/12/21 | 02/23/21 | 02/24/21 | |

### CODE REVIEW

**Comment by nghiakvnvsd** [comment]
Hi @artv3 I have just run my problem based on this branch but it also returns the issue similar.

**Comment by artv3** [comment]
> Hi @artv3 I have just run my problem based on this branch but it also returns the issue similar.

Hi @nghiakvnvsd , would you be able to provide more of the valgrind ouput? It might also help to build both mfem + hypre in debug mode to get line numbers. Generating the valgrind info may take while but would be super useful. 

The memory leak addressed here is the only one I've been able to track down. 

One other thing to try in your code is instead of using 
``    OperatorPtr K;
`` 
On line 167 is to use ``HypreParMatrix K``. I'm not sure if new is being used on line 182 when doing ``    amgx.SetOperator(*K.As<HypreParMatrix>());`` 

@tzanio , @barker29 what do you guys think? I think there is a memory leak somewhere but I'm not sure where.

**Comment by artv3** [comment]
Proferssor @nghiakvnvsd can you try the latest branch again? I just pushed some adjustments, I had the free in the the wrong place.... 

I was able to replicate the error on my end, and with the latest push I don't seem to run out of memory anymore. 
Thanks for checking out our work! Definitely has helped make it more robust!

**Comment by nghiakvnvsd** [comment]
> Professor @nghiakvnvsd can you try the latest branch again? I just pushed some adjustments, I had the free in the wrong place....
> 
> I was able to replicate the error on my end, and with the latest push I don't seem to run out of memory anymore.
> Thanks for checking out our work! Definitely has helped make it more robust!

It worked for me. Thank you very much for your help!!!

**Comment by artv3** [comment]
> > Professor @nghiakvnvsd can you try the latest branch again? I just pushed some adjustments, I had the free in the wrong place....
> > I was able to replicate the error on my end, and with the latest push I don't seem to run out of memory anymore.
> > Thanks for checking out our work! Definitely has helped make it more robust!
> 
> It worked for me. Thank you very much for your help!!!

Wonderful! If the code in this PR looks good, could I get an approval?

**Review by nghiakvnvsd — APPROVED** [review]

**Review by tzanio — APPROVED** [review]

**Review by barker29 — APPROVED** [review]
This looks good.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
