### PR TITLE
[CEED] Use Strided restricitions instead of Identity restrictions

### PR DESCRIPTION
**Pull request by YohannDudouit**
A PR CEED/libCEED#456 that is about to get merged in libCEED will remove Identity restriction and replace them with Strided restrictions. This PR should be merged synchronously with CEED/libCEED#456 gets merged in libCEED's master.
We should also run a benchmark using this PR to make sure that CEED/libCEED#456 does not impact negatively performance.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1328](https://github.com/mfem/mfem/pull/1328) | @YohannDudouit | @tzanio | @tzanio + @camierjs | 03/06/20 | 03/06/20 | 03/07/20 | |

### CODE REVIEW

**Comment by YohannDudouit** [comment]
CEED/libCEED#456 just got merged into master, I'll fix the Travis issues to proceed with the review of this PR.

**Comment by tzanio** [comment]
Should this be merged in mfem-4.1 or can it wait?

**Comment by tzanio** [comment]
> [CEED/libCEED#456](https://github.com/CEED/libCEED/pull/456) just got merged into master, I'll fix the Travis issues to proceed with the review of this PR.

Update also the libceed requirement in `INSTALL`

**Comment by YohannDudouit** [comment]
libCEED integration won't work with the current master branch of libCEED. It might be interesting to get it merged if users tend to use release versions rather than the master branch of MFEM, otherwise it can be merged any time after MFEM 4.1.

**Comment by YohannDudouit** [comment]
@tzanio Should I anticipate and mention a requirement for libCEED 0.6? Like this with have everything working with release versions.

**Comment by YohannDudouit** [comment]
I mention the v0.6 but I give the git-hash of the merged of CEED/libCEED#456

**Comment by YohannDudouit** [comment]
@barker29 You might be interested to take a look at this PR to see how to migrate from `IdentityRestriction` to `StridedRestriction`

**Comment by tzanio** [comment]
I manually cherry-picked the new commits from this PR (without the `mfem-4.1-dev` merge) in `master` so that should also work with the new libCEED version on tux429.

**Pull request merged**
