### PR TITLE
Allowing to work with 1D meshes in ParMesh::PrintAsOne().

### PR DESCRIPTION
**Pull request by homijan**
In ParMesh::PrintAsOne(std::ostream &out), number of vertices is based on IntRule of given geometry.
This did not work for SEGMENT, because Geometries.GetVertices(SEGMENT) == NULL. A simple workaround returning 2 vertices solves the problem.

### CODE REVIEW

**Comment by homijan** [comment]
Sorry, the solution is not so simple (and the above is not valid in general).

**Comment by homijan** [comment]
Now the logic of mesh writing is correct.

**Comment by vladotomov** [comment]
Addressed in #300 (similar fix).

**Comment by homijan** [comment]
@vladotomov  has already provided a better fix in #300, so this request can be closed.

**Pull request closed without merging**
