### PR TITLE
Enables shared library builds for MSVC  [shared-msvc-dev]

### LINKED ISSUE #1396: Shared build of mfem on Windows
Is ``mfem`` interested in being able to build as a shared library (i.e. a ``dll``) on Windows/``msvc``?

The [axom](https://github.com/LLNL/axom) project has been working on automating its Windows build, which requires building its third-party libraries, including ``mfem``, in shared mode.

#### Details:

One of the main differences between ``gcc``/``clang`` and ``msvc`` in their treatment of shared libraries has to do with how symbols are exported.  ``gcc``/``clang`` export all symbols by default, while ``msvc`` exports none of the symbols by default.

The CMake flag -- [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html) -- gets you most of the way there, but it does not export symbols for global variables, e.g. ``extern`` variables or ``static const`` class members.
I think this flag is available in ``CMake@3.7+``

I've developed a partial solution for this in https://github.com/LLNL/axom/pull/213 in the form of a patch to get ``mfem@4.0`` to link to axom (see https://github.com/LLNL/axom/blob/aaac337f2e6d3168d550c92094d633fc9864cb9b/scripts/uberenv/vcpkg_ports/mfem/export-extern-vars.patch ).  This solution requires very few changes to ``mfem``. I think this only covers the symbols that are currently used by ``axom``, and I haven't tried building ``mfem``'s examples or tests, so there is likely more work to be done.

My understanding is that shared mode is also required for Python support, so this might have relevance to a Windows build of https://github.com/mfem/PyMFEM, or it might already be a solved issue (?)

### PR DESCRIPTION
**Pull request by kennyweiss**
This PR enables building mfem in shared mode on Windows with MSVC.
* Most symbols are exported via the CMake config variable: `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`
* Extern and static variables require explicit ``dllExport``/``dllImport`` tags, which is achieved through the ``MFEM_EXPORT`` macro and CMake's `GenerateExportHeader` feature.
* I augmented the `make` build system to generate a corresponding ``mfem_export.h`` file
* I tested ``shared`` and ``static`` builds with MSVC 2017 and a serial ``gcc`` build on linux.

Configuring CMake for shared builds requires the following config variables;
```cmake
set(BUILD_SHARED_LIBS ON CACHE BOOL "")
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON CACHE BOOL "")
```

TODO:
- [ ] Add a shared build configuration to appveyor

Resolves #1396

### CODE REVIEW

**Comment by kennyweiss** [comment]
@v-dobrev, @acfisher -- I think I need a little help with the ``make``-based build system.

E.g. in the travis `gitignore` job:
```
make -C config all
make[1]: Entering directory '/home/travis/build/mfem/mfem/config'
mpicxx -I../../hypre/src/hypre/include get_hypre_version.cpp -o get_hypre_version
./get_hypre_version > get_hypre_version.out
HYPRE version: 21000
/bin/sh: 1: cannot create /mfem_export.h: Permission denied
```
https://travis-ci.org/github/mfem/mfem/jobs/672008087?utm_medium=notification&utm_source=github_status

``mfem/mfem_export.h`` is a new generated file that creates `dllExport`/`dllImport` in shared MSVC builds. I put it in the same location as the generated ``mfem.hpp` and added it to `.gitignore` so it will not be added to `git`, but it probably needs to be generated in the build directory instead.

**Comment by kennyweiss** [comment]
Unfortunately, the code is compiling in my version of "Visual Studio 2017" / CMake, but not appveyor's.

My versions are:
```
-- Selecting Windows SDK version 10.0.15063.0 to target Windows 10.0.18362.
-- CMake Version: 3.17.0
-- The CXX compiler identification is MSVC 19.11.25506.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe - works
```

Appveyor's are:
```
-- Building for: Visual Studio 15 2017
-- CMake Version: 3.16.2
-- The CXX compiler identification is MSVC 19.16.27035.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
```

**Comment by kennyweiss** [comment]
I updated my local compiler to ``MSVC 19.16.27038.0`` which is pretty close to ``appveyor``'s and was able to successfully build and test ``mfem`` in shared mode on this branch.   

Next, I'll check if downgrading to ``CMake@3.16`` helps reproduce the issue.

**Comment by acfisher** [comment]
I gave it a whirl on my laptop and it worked well and built the DLL:
cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DBUILD_SHARED_LIBS=ON
-- Building for: Visual Studio 16 2019
-- (optional) USER_CONFIG = C:/Users/fisher47/Desktop/linux/mfem/mfem/config/user.cmake
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.16299.
-- CMake Version: 3.17.20032601-MSVC_2
-- USE_XSDK_DEFAULTS = 'OFF'
-- The CXX compiler identification is MSVC 19.26.28806.0

**Comment by kailaix** [comment]
Is there any solution for shared build on Windows currently? I am working on a project where I want to link to the shared mfem library on Windows.
Thanks!

**Comment by kennyweiss** [comment]
@kailaix -- Last I checked, this PR worked (built, linked and passed all tests) within the CMake/Windows build system when I built it locally (and same for @acfisher), but it ran some linking problems when built through the `appveyor` CI that were difficult to figure out. 

This PR also needed some help to integrate the changes into the make-based build system.

**Comment by acfisher** [comment]
This has been sitting here forever.  What is the status of this PR?

**Comment by kennyweiss** [comment]
Thanks for pointing this out @acfisher -- I'll try to revamp the PR and mark it as ready

**Comment by cyrush** [comment]
Looking at the appveyor failure, something is crossed with the dll import vs dll export logic.

```
[00:04:25] C:\projects\mfem\general\device.cpp(64,32): error C2491: 'mfem::Device::device_singleton': definition of dllimport static data member not allowed [C:\projects\mfem\build_parallel\mfem.vcxproj]
```

During compilation, it should be `dllexport`

I suggest -- we use a simpler header that isn't autogenerated, here is a pass:

```
//
// mfem_exports.h
//
// when compiled with shared libs on windows, 
// CMake should add: -DMFEM_WINDOWS_DLL_EXPORTS

#if defined(MFEM_EXPORTS) || defined(mfem_EXPORTS)
    /* define catch all def */
    #define MFEM_EXPORTS_DEFINED 1
#endif

#if defined(_WIN32)
    #if defined(MFEM_WINDOWS_DLL_EXPORTS)
        #if defined(MFEM_EXPORTS_DEFINED)
            #define MFEM_API __declspec(dllexport)
        #else
            #define MFEM_API __declspec(dllimport)
        #endif
    #else
        #define MFEM_API /* empty for static builds */
    #endif

    #if defined(_MSC_VER)
        /* Turn off warning about lack of DLL interface */
        #pragma warning(disable:4251)
        /* Turn off warning non-dll class is base for dll-interface class */
        #pragma warning(disable:4275)
        /* Turn off warning about identifier truncation */
        #pragma warning(disable:4786)
    #endif
#else
    #define CONDUIT_API /* default */
#endif
```

This header will work for both the cmake and non cmake case, we don't need any extra logic to gen.

**Comment by v-dobrev** [comment]
This PR was superseded by #3513.

**Pull request closed without merging**
