### PR TITLE
Fixing wedge elements in Mesh::PrintVTK and beam-wedge.vtk [vtk-wedge-fix]

### PR DESCRIPTION
**Pull request by mlstowell**
This PR addresses issue #1887 which pointed out that the `beam-wedge.vtk` mesh contains invalid wedge elements.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1888](https://github.com/mfem/mfem/pull/1888) | @mlstowell | @tzanio | @tzanio + @pazner | 11/17/20 | 11/17/20 | 11/20/20 | |

### CODE REVIEW

**Comment by pazner** [comment]
Awesome, thanks @mlstowell! I think `Mesh::PrintVTU` should probably be fixed too (around line 9255).

**Review by tzanio — APPROVED** [review]
Thanks for the quick fix @mlstowell !

**Comment by tzanio** [comment]
I checked `data/fichera-mixed-p2.vtk` also and that appears to be OK.

**Comment by mlstowell** [comment]
> Awesome, thanks @mlstowell! I think `Mesh::PrintVTU` should probably be fixed too (around line 9255).

Good catch.  I think we'll need to change this in `vtk.cpp`.  I'll need to take a closer look.

**Comment by pazner** [comment]
> Good catch. I think we'll need to change this in `vtk.cpp`. I'll need to take a closer look.

The mappings in `vtk.cpp` are for high-order Lagrange VTK elements, and are (hopefully) already correct. It should be sufficient to do the same permutation as in `Mesh::PrintVTK`.

**Comment by mlstowell** [comment]
> > Good catch. I think we'll need to change this in `vtk.cpp`. I'll need to take a closer look.
> 
> The mappings in `vtk.cpp` are for high-order Lagrange VTK elements, and are (hopefully) already correct. It should be sufficient to do the same permutation as in `Mesh::PrintVTK`.

I see.  Do we have a way to check the output from `Mesh::PrintVTU`?

**Comment by pazner** [comment]
> I see. Do we have a way to check the output from `Mesh::PrintVTU`?

We can load the mesh in ParaView and see if it looks correct (I checked and it does). The only thing is I think the "wrong" ordering still looked fine, so it's not really a comprehensive test. I did look at the ASCII output and verified that the ordering was what we expect.

Now that I am looking into it, the way we save VTU meshes, the vertices are always duplicated between elements, which means that they are not suitable for reading. So maybe this is not so consequential.

I pushed a minor change simplifying the code slightly and introducing `vtk_prism_perm` to avoid manually reproducing this permutation in many places in the code. This same permutation appears in the VTK mesh reader, so I am planning on using this mapping in my work on the high-order VTK reader, and so this seems like a good place to introduce it.

If you prefer your earlier version, feel free to revert my commit.

**Comment by mlstowell** [comment]
> If you prefer your earlier version, feel free to revert my commit.

No, this is a good idea.  Thanks!

**Review by pazner — APPROVED** [review]

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
