### PR TITLE
Don't duplicate unit test output in parallel

### PR DESCRIPTION
**Pull request by pazner**
Small change to the unit tests so that Catch will only write to `cout`, `cerr`, and `clog` from MPI rank 0 when running in parallel. This should avoid duplicating messages such as "All tests passed".

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2918](https://github.com/mfem/mfem/pull/2918) | @pazner | @tzanio | @jandrej + @acfisher | 3/24/22 | 3/28/22 | 3/30/22 | |

PR Checklist
    
- [x] Code builds.
- [x] Code passes `make style`.

### CODE REVIEW

**Comment by jandrej** [comment]
Yes please!

**Review by jandrej — APPROVED** [review]

**Comment by adrienbernede** [comment]
LGTM

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by acfisher** [comment]
Looks like a good way of handling this.

**Review by acfisher — APPROVED** [review]

**Pull request merged**
