### PR TITLE
Fix CMake TPLs ordering issue

### PR DESCRIPTION
**Pull request by v-dobrev**
In `CMakeLists.txt`, move `STRUMPACK` before `METIS` in the list `MFEM_TPLS`.

Issue reported in #3342.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#3348](https://github.com/mfem/mfem/pull/3348) | @v-dobrev | @tzanio | @cjvogl + @sebastiangrimberg | 11/29/22 | 12/9/22 | 12/12/22 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by sebastiangrimberg** [comment]
I apologize for chiming in here, but I had noticed this same issue when using static linkage in the past and worry if this is the right fix respect to the leading comment:

```
# List all possible libraries in order of dependencies.
# [METIS < SuiteSparse]:
#    With newer versions of SuiteSparse which include METIS header using 64-bit
#    integers, the METIS header (with 32-bit indices, as used by mfem) needs to
#    be before SuiteSparse.
set(MFEM_TPLS OPENMP HYPRE LAPACK BLAS SuperLUDist STRUMPACK METIS SuiteSparse
    SUNDIALS PETSC SLEPC MESQUITE MUMPS AXOM FMS CONDUIT Ginkgo GNUTLS GSLIB
    NETCDF MPFR PUMI HIOP POSIXCLOCKS MFEMBacktrace ZLIB OCCA CEED RAJA UMPIRE
    ADIOS2 CUBLAS CUSPARSE MKL_CPARDISO AMGX CALIPER CODIPACK BENCHMARK PARELAG
    MPI_CXX HIP HIPSPARSE MOONOLITH BLITZ ALGOIM ENZYME)
```

Namely, according to the comment, packages depending on METIS should only be listed after METIS. I think the real issue is a few lines down where duplicates are removed:

```
list(REMOVE_DUPLICATES TPL_LIBRARIES)
list(REMOVE_DUPLICATES TPL_INCLUDE_DIRS)
```

In this case the CMake behavior is to keep the first entry and remove all later ones. What you really want for a static link line is for the last duplicate to be kept and all prior ones removed, so I have found that using instead:

```
list(REVERSE TPL_LIBRARIES)
 list(REMOVE_DUPLICATES TPL_LIBRARIES)
list(REVERSE TPL_LIBRARIES)
```

works and allows the `MFEM_TPLS` list to be constructed in order of dependency as the comment suggests. Note that this would also apply to `SuperLUDist` which also has a `METIS` dependency. I think the correct ordering of the first line in order of dependency would probably be:

```
set(MFEM_TPLS OPENMP LAPACK BLAS  MPI_CXX HYPRE METIS SuperLUDist STRUMPACK SuiteSparse
```

Anyway, just thought I would voice my experience as this worked for me when building with MUMPS/STRUMPACK/SuperLUDist support and might be a preferred long-term solution. At the very least if this isn't preferred then the original comment should be ammended.

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by v-dobrev** [comment]
@sebastiangrimberg, thanks for the suggestion about `TPL_LIBRARIES` -- I added that to the PR.

Regarding your comment: " ... according to the comment, packages depending on METIS should only be listed after METIS." The case of `METIS < SuiteSparse` is an exception to the rule and concerns a special case where SuiteSparse is built and linked with its internal version of METIS (which is a slightly modified METIS-5.1.0 using 64-bit indices) and we are compiling and linking with another METIS build. In this case it is important to include `metis.h` NOT from the SuiteSparse directory but the one we want -- that's why METIS should come before SuiteSparse (because include dirs are searched in the order they appear on the command line, as far as I know).

In general, in the `TPL_LIBRARIES` we want A before B whenever A depends on B. This makes sense when A depends on B but `A_LIBRARIES` does not include `B_LIBRARIES`. However, when removing duplicates in `TPL_LIBRARIES` as before (i.e. keeping the first occurrence of a library), we can get undesired behavior, e.g. when two different libraries depend on the same library.

With the change you suggested (to keep the last occurrence), I think the ordering in `MFEM_TPLS` should only matter is the special case when A depends on B and `A_LIBRARIES` does not include `B_LIBRARIES` which is contrary to the expected behavior: `A_LIBRARIES` should include all libraries needed for linking with A.

I think the updated logic in `CMakeLists.txt` (as it is now in this PR) about the handling of `MFEM_TPLS` and `TPL_LIBRARIES` should be correct. Do you see any cases where there still may be problems?

**Comment by sebastiangrimberg** [comment]
@v-dobrev Thanks for explaining that, I kind of misread the comment about METIS and SuiteSparse thinking this was an example for how dependencies should be ordered. I agree with everything you've said, and especially that none of this becomes an issue when the user correctly is specifying the `A_REQUIRED_PACKAGES` and `A_REQUIRED_LIBRARIES`, with their correct ordering as well.

Looks good to me and works in my tests.

**Review by sebastiangrimberg — APPROVED** [review]

**Comment by sebastiangrimberg** [comment]
Hi again @v-dobrev, I had a couple more thoughts I wanted to share as they could be related to this PR.

1. CMake 3.8 (released April 2017) fixed the handling of `CMAKE_CXX_STANDARD`, etc. for `try_compile`, so it could be worth reverting your additions to `config/cmake/modules/MfemCmakeUtilities.cmake` and just bumping the minimum `cmake_required_version` to 3.8 in my opinion (see https://cmake.org/cmake/help/latest/policy/CMP0067.html).
2. Suggested change for C++14 requirements adding STRUMPACK (https://github.com/mfem/mfem/blob/master/CMakeLists.txt#L85):
```
# SUNDIALS, STRUMPACK, and Ginkgo require C++14:
if ((MFEM_USE_SUNDIALS OR MFEM_USE_STRUMPACK OR MFEM_USE_GINKGO) AND
    ("${CMAKE_CXX_STANDARD}" LESS "14"))
  set(CMAKE_CXX_STANDARD 14)
endif()
```
3. When building with OpenMP support, and using dependencies which use OpenMP, I have run into the following issue with CMake. Adding `OpenMP` to `<PACKAGE>_REQUIRED_PACKAGES` doesn't correctly add the compiler flags because it doesn't use an imported target and only adds the include directories and link libraries. This makes any test programs fail at link time due to unresolved symbols. Alternatively, the `find_package(OpenMP)` block [here](https://github.com/mfem/mfem/blob/master/CMakeLists.txt#L268) does not set the compiler flags, which are only set later on (after third-party library finding) [here](https://github.com/mfem/mfem/blob/master/CMakeLists.txt#L513). If these blocks were earlier on in the `CMakeLists.txt` file, the flags would be automatically used by the `try_compile` statements and resolve the issue. Thus, I propose adding the below block to line 188 (at beginning of TPLs) or 201 (after HIP) so that the flags are set for any test builds later on:
```
# OpenMP
if (MFEM_USE_OPENMP OR MFEM_USE_LEGACY_OPENMP)
  if (NOT MFEM_THREAD_SAFE AND MFEM_USE_LEGACY_OPENMP)
    message(FATAL_ERROR " *** MFEM_USE_LEGACY_OPENMP requires MFEM_THREAD_SAFE=ON.")
  endif()
  find_package(OpenMP REQUIRED)
  set(OPENMP_LIBRARIES ${OpenMP_CXX_LIBRARIES})
  if(APPLE)
    # On macOS, the compiler needs additional help to find the <omp.h> header.
    # See issue #2642 for more information.
    set(OPENMP_INCLUDE_DIRS ${OpenMP_CXX_INCLUDE_DIRS})
  endif(APPLE)
  if (OPENMP_FOUND)
    message(STATUS "MFEM: using package OpenMP")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    if (MFEM_USE_CUDA)
      set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Xcompiler=${OpenMP_CXX_FLAGS}")
    endif()
  endif()
endif()
```

I realize I may not have done the best job explaining the change, so I'm attaching a diff of my proposed change.

[diff.txt](https://github.com/mfem/mfem/files/10179053/diff.txt)

**Comment by v-dobrev** [comment]
@sebastiangrimberg, all your suggestions sound good to me. Why don't you go ahead and add them to this PR directly, if you don't mind?

I think the STRUMPACK headers actually work fine with just C++11 but I think STRUMPACK is being compiled with C++14 in recent versions, so bumping to C++14 seems reasonable, even though it does not seem to be strictly necessary at the moment.

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Re-merged in `next` for testing...

**Comment by v-dobrev** [comment]
One of the commits never made it in `next` (9a7f764a). Merge `master` in `next`?

**Comment by tzanio** [comment]
> One of the commits never made it in next (https://github.com/mfem/mfem/commit/9a7f764ac78ab23c51d30659d913f7080ae16b4a)

Sorry, I dropped the ball on this one.

> Merge `master` in `next`?

Yes. I can do that if you want.

**Comment by v-dobrev** [comment]
> > Merge `master` in `next`?
> 
> Yes. I can do that if you want.

Go for it.

**Comment by tzanio** [comment]
Done

**Pull request merged**
