### PR TITLE
Updated sample runs in ex30 to remove warnings

### PR DESCRIPTION
**Pull request by brendankeith**
Updated sample runs in ex30 to remove warnings

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2881](https://github.com/mfem/mfem/pull/2881) | @brendankeith | @tzanio | @tzanio + @psocratis | 3/10/22 | 3/10/22 | 3/11/22 | |

<details>
<summary>PR Checklist</summary>
    
- [x] Code builds.
- [x] Code passes `make style`.
- [x] All sample runs at the top of the example source file work.
- [x] (LLNL only) After merging: Update internal tests to include the new features.

</details>

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by psocratis** [comment]
at the bottom of ex30p.cpp the code 

````cpp
   sol_sock.precision(8);
   sol_sock << "parallel " << num_procs << " " << myid << "\n";
   sol_sock << "mesh\n" << pmesh << flush;
````
should go in an `if(visualization)` statement

**Review by psocratis — APPROVED** [review]

**Review by tzanio — APPROVED** [review]
Thanks for the quick fix @brendankeith !

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
