### PR TITLE
Lambda const propagation [lambda-capture-problem]

### PR DESCRIPTION
**Pull request by jakubcerveny**
As a follow-up to yesterday's PR #850, I was trying to look at the PTX code generated for the different instances:
```
nvcc   -O3 -std=c++11 -x=cu --expt-extended-lambda -arch=sm_60 -ccbin g++   -c fem/bilininteg_ext.cpp -ptx -o fem/bilininteg_ext.ptx
```

It seems there is a problem propagating the constants into the lambda correctly. Even though the compiler knows that something is a compile-time constant, sometimes they seem to get captured as regular variables and the desired behavior is lost:
```c++
   const int CONST = 2;
   MFEM_FORALL(e, NE,
   {
      for (int i = 0; i < CONST; i++) // not unrolled, CONST is treated as run-time (captured as [=]?)
      {
         _y[D1D*e + i] = 12345;
      }
      Dummy<CONST> dummy; // but this apparently works!
   }
```
Not even constexpr works:
```c++
   constexpr int CONST = 2;
   MFEM_FORALL(e, NE,
   {
      for (int i = 0; i < CONST; i++) // not unrolled
      {
         _y[D1D*e + i] = 12345;
      }
   }
```
Could this be a bug in nvcc? Only this works as expected:
```c++
   MFEM_FORALL(e, NE,
   {
      const int CONST = 2;
      for (int i = 0; i < CONST; i++) // unrolled OK
      {
         _y[D1D*e + i] = 12345;
      }
   }
```
Using actual template parameters such as `T_D1D` also works, but that defeats our purpose :-(

### CODE REVIEW

**Comment by jakubcerveny** [comment]
This also works, but won't compile for the run-time size kernel:
```c++
template<int N>
struct CaptureConst
{
   enum { value = N };
};
```
```c++
   const int CONST = 2;
   MFEM_FORALL(e, NE,
   {
      const int CONST2 = CaptureConst<CONST>::value;
      for (int i = 0; i < CONST2; i++)
      {
         _y[D1D*e + i] = 12345;
      }
   });
```
Could we use some metaprogramming to get around this problem?

**Comment by artv3** [comment]
@jakubcerveny , do we see the same issues with the CPU version? I believe the CPU lambdas capture by reference so I'm curious to know if the issue is also there.

**Comment by jakubcerveny** [comment]
Ha! Defining the constant again inside the lambda does the trick:
```c++
   MFEM_FORALL(e, NE,
   {
      const int D1D = T_D1D ? T_D1D : d1d; // nvcc workaround
      for (int i = 0; i < D1D; i++)
      {
         _y[D1D*e + i] = 12345;
      }
   });
```
Now I get four different optimized kernels and a generic one...

**Comment by v-dobrev** [comment]
So, is the conclusion that we do not need to modify the lambdas we have in the okina branch? The last version looks similar to what's in the branch.

**Comment by jakubcerveny** [comment]
It should be "fixed" now in all the kernels. When/if they fix nvcc we can remove the workarounds. I looked at the PTX and all the kernels are different now, the optimized ones are full of operations with very few branches and the generic kernels are on the other hand full of branches -- it seems to work nicely.

**Comment by jakubcerveny** [comment]
BTW, as far as I can tell with my limited understanding of the PTX assembly, the optimized kernels contain very few integer instructions, which likely means that the compiler can see the compile-time constants through the `DeviceTensor` class. The generic kernels on the other hand are laden with 32-bit integer instructions to do the indexing, which is what one would expect. We can investigate if the current indexing is optimal for the generic kernels, but the optimized kernels seem to be good already. I think this is pretty cool.

**Comment by camierjs** [comment]
Again, that looks awesome: thank you @jakubcerveny !

**Pull request merged**
