### PR TITLE
Unify coefficient evaluation for PA

### PR DESCRIPTION
**Pull request by pazner**
Each PA integrator replicates a bunch of complicated logic for the evaluation of coefficients (scalar, vector, matrix, symmetric matrix, etc.) at quadrature points, including some optimizations (for constant coefficients only storing one number, if it is a quadrature function coefficient then just setting a pointer, etc.).

This PR centralizes all of this logic in a new class called `CoefficientVector`.

By default, `CoefficientVector` behaves essentially like a `QuadratureFunction`, and gives an array of shape `(vdim, nqpts, nelements)`. The caller can choose opt-in to optimizations such as:

* For `ConstantCoefficient`, `VectorConstantCoefficient`, and `MatrixConstantCoefficient`, only one value is stored.
* For `SymmetricMatrixCoefficient`, only the upper triangular part of the matrix needs to be stored.

However, by default, a full vector is created, so integrator code does not need to be special-cased if it's not required for performance.

Additionally, the evaluation of the coefficients at quadrature points is performed using a new function `QuadratureFunction::ProjectCoefficient`. Optimizations can be made to this function (such as using `QuadratureInterpolator` to evaluate a `GridFunctionCoefficient` on device), and all integrators using `CoefficientVector` will automatically benefit.

This should make writing PA integrators with coefficients significantly easier and less bug-prone.

<details>
<summary>Example (click to expand)</summary>

```diff
diff --git a/fem/bilininteg_convection_pa.cpp b/fem/bilininteg_convection_pa.cpp
index a1ea4c663..5e964dbeb 100644
--- a/fem/bilininteg_convection_pa.cpp
+++ b/fem/bilininteg_convection_pa.cpp
@@ -1399,66 +1399,10 @@ void ConvectionIntegrator::AssemblePA(const FiniteElementSpace &fes)
    dofs1D = maps->ndof;
    quad1D = maps->nqpt;
    pa_data.SetSize(symmDims * nq * ne, mt);
-   Vector vel;
-   if (VectorConstantCoefficient *cQ =
-          dynamic_cast<VectorConstantCoefficient*>(Q))
-   {
-      vel = cQ->GetVec();
-   }
-   else if (VectorGridFunctionCoefficient *vgfQ =
-               dynamic_cast<VectorGridFunctionCoefficient*>(Q))
-   {
-      vel.SetSize(dim * nq * ne, mt);
 
-      const GridFunction *gf = vgfQ->GetGridFunction();
-      const FiniteElementSpace &gf_fes = *gf->FESpace();
-      const QuadratureInterpolator *qi(gf_fes.GetQuadratureInterpolator(*ir));
-      const bool use_tensor_products = UsesTensorBasis(gf_fes);
-      const ElementDofOrdering ordering = use_tensor_products ?
-                                          ElementDofOrdering::LEXICOGRAPHIC :
-                                          ElementDofOrdering::NATIVE;
-      const Operator *R = gf_fes.GetElementRestriction(ordering);
+   QuadratureSpace qs(*mesh, *ir);
+   CoefficientVector vel(*Q, qs, CoefficientStorage::COMPRESSED);
 
-      Vector xe(R->Height(), mt);
-      xe.UseDevice(true);
-
-      R->Mult(*gf, xe);
-      qi->SetOutputLayout(QVectorLayout::byVDIM);
-      qi->DisableTensorProducts(!use_tensor_products);
-      qi->Values(xe,vel);
-   }
-   else if (VectorQuadratureFunctionCoefficient* vqfQ =
-               dynamic_cast<VectorQuadratureFunctionCoefficient*>(Q))
-   {
-      const QuadratureFunction &qFun = vqfQ->GetQuadFunction();
-      MFEM_VERIFY(qFun.Size() == dim * nq * ne,
-                  "Incompatible QuadratureFunction dimension \n");
-
-      MFEM_VERIFY(ir == &qFun.GetSpace()->GetElementIntRule(0),
-                  "IntegrationRule used within integrator and in"
-                  " QuadratureFunction appear to be different");
-
-      qFun.Read();
-      vel.MakeRef(const_cast<QuadratureFunction &>(qFun),0);
-   }
-   else
-   {
-      vel.SetSize(dim * nq * ne);
-      auto C = Reshape(vel.HostWrite(), dim, nq, ne);
-      DenseMatrix MQ_ir;
-      for (int e = 0; e < ne; ++e)
-      {
-         ElementTransformation& T = *fes.GetElementTransformation(e);
-         Q->Eval(MQ_ir, T, *ir);
-         for (int q = 0; q < nq; ++q)
-         {
-            for (int i = 0; i < dim; ++i)
-            {
-               C(i,q,e) = MQ_ir(i,q);
-            }
-         }
-      }
-   }
    PAConvectionSetup(dim, nq, ne, ir->GetWeights(), geom->J,
                      vel, alpha, pa_data);
 }
```
</details>

(Note that this PR is based on #2836, which should explain a lot of the diffs).

### CODE REVIEW

**Comment by v-dobrev** [comment]
There's another PR with a similar goal: #1656.

**Comment by artv3** [comment]
Lots of warnings from this branch: 

```
fem/fe/fe_nd.hpp(498): warning: overloaded virtual function "mfem::FiniteElement::Project" is only partially overridden in class "mfem::ND_R2D_SegmentElement"

fem/fe/fe_nd.hpp(547): warning: overloaded virtual function "mfem::FiniteElement::Project" is only partially overridden in class "mfem::ND_R2D_FiniteElement"

fem/fe/fe_rt.hpp(331): warning: overloaded virtual function "mfem::FiniteElement::Project" is only partially overridden in class "mfem::RT_R1D_SegmentElement"

fem/fe/fe_rt.hpp(418): warning: overloaded virtual function "mfem::FiniteElement::Project" is only partially overridden in class "mfem::RT_R2D_FiniteElement"
```

**Comment by pazner** [comment]
> Lots of warnings from this branch:

It was just because of something unrelated that got merged into master, see #2886.

I just merged more recent master, hopefully it's fixed now.

**Comment by pazner** [comment]
Keeping open for now, but this can be closed once #3066 is merged.

**Comment by pazner** [comment]
Closed in favor of #3066

**Comment by tzanio** [comment]
@pazner, can we delete this branch?

**Comment by pazner** [comment]
Yes, just deleted it, thanks.

**Pull request closed without merging**
