### PR TITLE
Bug fix in ParLinearForm and changing integrator names

### PR DESCRIPTION
**Pull request by kmittal2**
This PR addresses #2363 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2375](https://github.com/mfem/mfem/pull/2375) | @kmittal2 | @v-dobrev | @mlstowell + @jandrej | 07/01/21 | 07/09/21 | 07/13/21 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by robert-chiodi — APPROVED** [review]
Looks good to me. Thanks again for the quick fix and giving more expressive names to the integrator variables.

**Review by jandrej — APPROVED** [review]

**Review by pazner — APPROVED** [review]
Big improvement to readability (in addition to fixing the bug)!

**Comment by v-dobrev** [comment]
Merged in `next` for testing...

**Pull request merged**
