### PR TITLE
Bug fix for MixedVectorCurlIntegrator PA

### PR DESCRIPTION
**Pull request by dylan-copeland**
A bug is fixed, which affected ex24, and a unit test case is added.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1754](https://github.com/mfem/mfem/pull/1754) | @dylan-copeland | @v-dobrev | @psocratis + @mlstowell | 09/10/20 | 09/22/20 | 09/29/20 | |

### CODE REVIEW

**Review by psocratis — APPROVED** [review]

**Comment by v-dobrev** [comment]
@mlstowell, this is a hotfix for `master`, so I'd like to get it merged soon -- can you please prioritize this review?

**Review by mlstowell — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Re-merged in `next` for testing ...

**Comment by tzanio** [comment]
This is a hotfix, so I'll merge it in.

**Pull request merged**
