### PR TITLE
Adding AttrToMarker function to remove duplicated code [attr-to-marker-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
As I was about to add this functionality to yet another code it occurred to me that I should write a function to do this...

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1364](https://github.com/mfem/mfem/pull/1364) | @mlstowell | @tzanio | @cjvogl + @psocratis | 03/19/20 | 03/25/20 | 03/27/20 | |

### CODE REVIEW

**Comment by cjvogl** [comment]
Looks like Travis stalled on a few tests... @tzanio or @v-dobrev, can you restart (or indicate how I would restart them)?

**Comment by tzanio** [comment]
The Mac test on Travis have been really slow... I restarted them

**Comment by mlstowell** [comment]
@cjvogl, there are three sample runs in `maxwell.cpp` which use the `-dbcs` flag.  I suppose we could compare results between this branch and master.  I didn't actually do this for `maxwell` but I did verify `volta` and `tesla`.

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
