### PR TITLE
Trigger Actions on all PRs, and on merge in next

### PR DESCRIPTION
**Pull request by adrienbernede**
As mentioned here (https://github.com/mfem/mfem/pull/2130#issuecomment-806233271), Actions should be run on any PR.

Also added a trigger on next, so that merging in next is tested too.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2131](https://github.com/mfem/mfem/pull/2131) | @adrienbernede | @tzanio | @pazner + @tzanio | 03/24/21 | 03/24/21 | 03/26/21 | |

### CODE REVIEW

**Review by pazner — APPROVED** [review]
Looks good to me! Thanks @adrienbernede

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
Do we not want the same change in the other workflows?

**Comment by adrienbernede** [comment]
You are right, I got distracted...

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
