### PR TITLE
[WIP] extensions for Okina  (Ex 9 and others) [artv3/okina-extension] 

### PR DESCRIPTION
**Pull request by artv3**
Example 9 served as a good starting point for my application and learning about Okina.
We have enough machinery to carryout example 9's time-stepping on the GPU. The pre-conditioned iterative solvers are not yet completely supported on the GPU and I am instead using a standard CG method (like in example 1). 

By adding a few lines of Okina code, I've observed an ~ 8x speed up on the GPU vs CPU. I'l keep pushing features to this branch for my target application.

### CODE REVIEW

**Comment by artv3** [comment]
@tzanio , In this PR I mostly have minor changes to okina to help debug the proxy app. Should I move the proxy app here?

**Comment by tzanio** [comment]
If these changes are intended to be merged in master, I think it is better to keep the miniapp separate, as we will likely not want to include it in the library (similar to Laghos).

If this is just a working branch that is not intended for merging, than you can add it, but maybe not push to the server?

**Comment by artv3** [comment]
@tzanio , sounds good. This is more like a working branch to keep track of changes made to Okina to help port my application.  There might be some changes that could be pushed back to master. To be safe I'll keep the miniapp separate.

**Comment by artv3** [comment]
Branch is now outdated. Using newer version of Okina now.

**Pull request closed without merging**
