### PR TITLE
ADIOS2 output switch material to MFEM attribute in CellData

### PR DESCRIPTION
**Pull request by williamfgc**
Minor change to sync up with ParaViewDataCollection
Changes in variable creation and VTK XML schema

Related to #1616 and #1825 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1837](https://github.com/mfem/mfem/pull/1837) | @williamfgc | @tzanio | @rcarson3 + @tzanio + @v-dobrev | 10/24/20 | 10/24/20 | 10/24/20 | |

### CODE REVIEW

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Review by tzanio — APPROVED** [review]

**Comment by benzwick** [comment]
Is it too late to add this to MFEM 4.2? It is quite a minor change and related to the similar change in ParaView output.

**Comment by tzanio** [comment]
No it is not too late, @v-dobrev do you mind approving?

**Review by v-dobrev — APPROVED** [review]

**Review by benzwick — APPROVED** [review]

**Review by rcarson3 — APPROVED** [review]

**Comment by tzanio** [comment]
That was quick, thanks guys!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
