### PR TITLE
Adding a desired LOD field to the visit output [visit-lod-dev]

### PR DESCRIPTION
**Pull request by IdoAkkerman**
This PR adds a desired field to the visit meta data. This allows visit to represent the data at a higher LOD (level-fo-detail). This is a need feature for plotting higher order solutions such as NURBS.

For this to work a small patch needs to be applied to visit.

### CODE REVIEW

**Comment by IdoAkkerman** [comment]
The patch to visit 2.12.3 is the following:

--- ../../orig2/visit2.12.3/src/databases/MFEM/avtMFEMFileFormat.C	2017-05-23 20:48:13.000000000 +0200
+++ databases/MFEM/avtMFEMFileFormat.C	2018-05-24 15:11:52.847079689 +0200
@@ -181,7 +181,7 @@
     root_md.DataSets(dset_names);
 
     // enumerate datasets)
-
+    selectedLOD = 0;
     for(int i=0;i<(int)dset_names.size();i++)
     {
         JSONRootDataSet &dset =  root_md.DataSet(dset_names[i]);
@@ -222,6 +222,11 @@
         for(size_t j=0;j<field_names.size();j++)
         {
             JSONRootEntry &field = dset.Field(field_names[j]);
+
+            std::string slod = field.Tag("lod");
+            int ilod = std::min(md->GetMeshes(i).LODs,atoi(slod.c_str()));
+            selectedLOD = std::max(selectedLOD,ilod);
+
             std::string f_assoc = field.Tag("assoc");
 
             if(f_assoc == "elements")
@@ -757,8 +762,7 @@
                 tuple_vals[2] = 0.0;
                 tuple_vals[0] = vec_vals(0,j);
                 tuple_vals[1] = vec_vals(1,j);
-                if (vec_vals.Height() > 2)
-                    tuple_vals[2] = vec_vals(2,j);
+
                 rv->SetTuple(ref_idx, tuple_vals); 
                 ref_idx++;
             }

**Comment by IdoAkkerman** [comment]
The appropriate visit patches are:

[mfem-lod-visit2.13.1.txt](https://github.com/mfem/mfem/files/2038276/mfem-lod-visit2.13.1.txt)
[mfem-lod-visit2.12.3.txt](https://github.com/mfem/mfem/files/2038277/mfem-lod-visit2.12.3.txt)

**Comment by cyrush** [comment]
Thanks for working on this, I'll take a look next week!

**Comment by cyrush** [comment]
Looks like i missed "next week" bit a mile -- sorry, not sure when I'll have free time but I'll try to tackle soon.

**Pull request merged**
