### PR TITLE
Fix some issues in miniapps/solvers

### PR DESCRIPTION
**Pull request by v-dobrev**
Fix the `clean-exec` target in `miniapps/solvers/makefile`.

Another issue I noticed is that sometimes the tests in `miniapps/solvers` will fail randomly on my Mac laptop. It turned out that running valgrind reports a number of errors like this (with the valgrind option ` --track-origins=yes`):
```console
==23727== Conditional jump or move depends on uninitialised value(s)
==23727==    at 0x6043698: sqrt (in /usr/lib64/libm-2.17.so)
==23727==    by 0x4BBA2E: mfem::MINRESSolver::Mult(mfem::Vector const&, mfem::Vector&) const (solvers.cpp:1394)
==23727==    by 0x41959B: mfem::blocksolvers::BDPMinresSolver::Mult(mfem::Vector const&, mfem::Vector&) const (div_free_solver.cpp:343)
==23727==    by 0x41B1F5: mfem::blocksolvers::DivFreeSolver::SolveParticular(mfem::Vector const&, mfem::Vector&) const (div_free_solver.cpp:503)
==23727==    by 0x41BA41: mfem::blocksolvers::DivFreeSolver::Mult(mfem::Vector const&, mfem::Vector&) const (div_free_solver.cpp:559)
==23727==    by 0x40BECF: main (block-solvers.cpp:354)
==23727==  Uninitialised value was created by a heap allocation
==23727==    at 0x4C2AC38: operator new[](unsigned long) (vg_replace_malloc.c:433)
==23727==    by 0x4113E6: mfem::Memory<double>::Alloc<16ul, true>::New(unsigned long) (mem_manager.hpp:468)
==23727==    by 0x40F9B7: mfem::Memory<double>::New(int, mfem::MemoryType) (mem_manager.hpp:699)
==23727==    by 0x40CD61: mfem::Vector::SetSize(int) (vector.hpp:489)
==23727==    by 0x41B11D: mfem::blocksolvers::DivFreeSolver::SolveParticular(mfem::Vector const&, mfem::Vector&) const (div_free_solver.cpp:497)
==23727==    by 0x41BA41: mfem::blocksolvers::DivFreeSolver::Mult(mfem::Vector const&, mfem::Vector&) const (div_free_solver.cpp:559)
==23727==    by 0x40BECF: main (block-solvers.cpp:354)
```
Let's use this branch to address this issue(s).

cc: @chakshinglee

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2057](https://github.com/mfem/mfem/pull/2057) | @v-dobrev | @tzanio | @tzanio + @jandrej | 05/01/21 | 05/03/21 | 05/04/21 | |

### CODE REVIEW

**Comment by v-dobrev** [comment]
@chakshinglee, do you think you'll be able to take a look at the above valgrind issue soon? It will be good to get this resolved for the v4.3 release, if possible.

**Comment by tzanio** [comment]
@chakshinglee, if you can take a look at the valgrind issues above this week, we can push the fix as part of the mfem release due at the end of the month.

**Review by tzanio — APPROVED** [review]

**Comment by jandrej** [comment]
The uninitialized values should be fixed with the recent commit.

**Comment by tzanio** [comment]
@v-dobrev, did you get a chance to test this? I am also happy to test myself.

**Comment by v-dobrev** [comment]
I tried this on my laptop and I don't see the random failures anymore. 🎉 

Thanks for fixing this, @jandrej! I suspect you already ran this through `valgrind` and it was clean?

Unfortunately, the nightly baseline tests do not run this example at the moment, so I opened this issue: #2213.

**Comment by v-dobrev** [comment]
Hmm, I just noticed this: https://github.com/mfem/mfem/blob/5b81176e18b5cb42ca63adfc984928df07cce1e7/miniapps/solvers/div_free_solver.cpp#L488-L489

and class `Array` does not really support non-pod types, so it should be used with class `Vector` -- I'm sure how this even works now. 😃 

It'll be best to replace these with `std::vector<Vector>` or something like that.

**Comment by v-dobrev** [comment]
LGTM

**Comment by tzanio** [comment]
LGTM

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by v-dobrev** [comment]
@adrienbernede, this type of output in the gitlab logs is quite annoying: https://lc.llnl.gov/gitlab/mfem/mfem/-/jobs/234811#L17 (it looks like the output from a verbose `git clean`). Unfortunately, it looks like something gitlab is generating -- do you know a way to suppress it?

**Review by tzanio — APPROVED** [review]

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by chakshinglee** [comment]
@v-dobrev @tzanio guys sorry that I did not respond to this PR (I just notice this now while cleaning up my emails, I guess I will need a better way to organize my github notifications).
@jandrej Thanks for fixing the issue!

**Pull request merged**
