### PR TITLE
Add code to derive from ParMesh.

### PR DESCRIPTION
**Pull request by koning**
These are additions I needed  to derive from ParMesh for an existing parallel decomposed mesh.

### CODE REVIEW

**Comment by tzanio** [comment]
Hi @koning, a few questions:

  - Why do you need a virtual destructor for `GroupTopology` are you planning to inherit from it?
  - Shouldn't the `ParMesh()` constructor at least initialize some data?
  - Can you please replace `{;}` by `{}`? (Just commit in `koning:develop` to update the pull request.)

Thanks!
Tzanio

P.S. It might be more convenient for you to work with the internal LLNL repo, https://mystash.llnl.gov/projects/mfem.

**Comment by koning** [comment]
- Why do you need a virtual destructor for GroupTopology are you planning to inherit from it?
That is a potential,  it was forward looking change at this point. 
-     Shouldn't the ParMesh() constructor at least initialize some data?
Yes, but since this is still new to me I thought I would elicit so comments like this one. It will call the Mesh default ctor, so which of the other objects need defaults? I added the MPI member variable defaults.
-     Can you please replace {;} by {}? (Just commit in koning:develop to update the pull request.)
Done.

**Comment by v-dobrev** [comment]
Hi @koning, I think we should make this default constructor protected, so it can be called only from derived classes. Also, ParMesh has some public data members - `have_face_nbr_data`, and `pncmesh` that should be initialized too.

**Comment by tzanio** [comment]
Thanks Joe, merged (also internally).

**Pull request merged**
