### PR TITLE
Pass bp_index group instead of global group to SidreDataCollection with external DS [sidredc-groups-dev]

### PR DESCRIPTION
**Pull request by tomstitt**
When using an external `SidreDataCollection` pass in the `blueprint_index` group instead of the global group. The global group is used only to create the blueprint index group and the global group may be shared between multiple users; it is easier to manage Sidre as a whole if the sdc only creates groups and views under non-shared groups.

Adds `m_` prefix to sidre group variables to match other member variable's naming format

### CODE REVIEW

**Comment by rieben1** [comment]
@cyrush can you take a look at this? We have other PRs in the code which depend on this being merged.

**Comment by v-dobrev** [comment]
@tomstitt, you should be able to merge (manually) this branch into the `next` branch for testing. Also, add the `in-next` label when you do that.

**Comment by v-dobrev** [comment]
@tomstitt, when building the documentation in the `next` branch, we get the following warnings:
```
/home/dobrev1/autotest-mfem/tux375/mfem/fem/sidredatacollection.hpp:183: warning: argument 'bp_index_group' of command @param is not found in the argument list of mfem::SidreDataCollection::SidreDataCollection(const std::string &collection_name, axom::sidre::Group *bp_index_grp, axom::sidre::Group *domain_grp, bool owns_mesh_data=false)
/home/dobrev1/autotest-mfem/tux375/mfem/fem/sidredatacollection.hpp:198: warning: The following parameters of mfem::SidreDataCollection::SidreDataCollection(const std::string &collection_name, axom::sidre::Group *bp_index_grp, axom::sidre::Group *domain_grp, bool owns_mesh_data=false) are not documented:
  parameter 'bp_index_grp'
```
Can you please take a look and update this PR branch to fix these warnings?

**Comment by v-dobrev** [comment]
Thanks @tomstitt. I merged the update into `next`.

**Pull request merged**
