### PR TITLE
Fix bug in DenseTensor::Swap [tensor-swap-bugfix]

### LINKED ISSUE #2157: Missing DenseMatrix::Swap
There currently isn't a `DenseMatrix::Swap()` function implemented.  This leads to an issue when e.g. `DenseTensor::Swap()` is called:
https://github.com/mfem/mfem/blob/9676e98f8977801c8475da46c46ea0b68df0a9fc/linalg/densemat.hpp#L884-L888

In `DenseTensor::Swap()`, `tdata` and `nk` are swapped, but `Mk` (a `DenseMatrix`) is not.  Subsequently, when e.g. `DenseTensor::SizeI()` or `DenseTensor::SizeJ()` are called on the swapped `DenseTensor`s, they can return the wrong sizes (since they depend on the size of `Mk`).

Is there a reason `DenseMatrix::Swap()` isn't implemented?  If not, I'd be happy to put one together and create a pull request.

### PR DESCRIPTION
**Pull request by pazner**
Resolves #2157.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2165](https://github.com/mfem/mfem/pull/2165) | @pazner | @tzanio | @tzanio + @v-dobrev | 04/10/21 | 04/13/21 | 04/16/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
LGTM

**Review by tzanio — APPROVED** [review]

**Review by ebchin — APPROVED** [review]
Thanks @pazner!

**Review by v-dobrev — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
