### PR TITLE
Add element attribute to adios2 bp dataset

### PR DESCRIPTION
**Pull request by williamfgc**
Update dataset format version
Save element attribute as "material" local array variable
Add material as CellData in xml schema
Update FindADIOS2.cmake for adios2 v2.6.0.

Partially addresses #1616 (needs visualization support in VTK). 

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1704](https://github.com/mfem/mfem/pull/1704) | @williamfgc | @tzanio | @rcarson3 + @tzanio | 08/25/20 | 09/11/20 | 09/17/20 | |

### CODE REVIEW

**Comment by rcarson3** [comment]
@williamfgc is this ready for review? If so I can add the necessary flags to the PR to kick start that process.

**Comment by williamfgc** [comment]
@rcarson3 yes, I used example 9 parallel. You should be able to access the data in your post-processing scripts. The VTK visualization is a different effort that will be done in VTK. Let me know if you need anything from my side. Looking forward to your feedback. Thanks!

**Comment by williamfgc** [comment]
@rcarson3 thanks for the review. That's correct, I haven't implemented the cell data viewer in ParaView/VTK. My expectation is that it would be straight-forward to do in VTK but a process on its own to get a PR merged and available in the ParaView release.  The schema is just an annotation, the VTK reader is where the population happens. I'll keep you posted when that becomes available. On the MFEM, this is what is required (so far).  I'll add to the Change log. Thanks!

**Review by tzanio — APPROVED** [review]
Thanks @williamfgc !

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
