### PR TITLE
Bring us in compliance with M1 of the XSDK [xsdk-cmake-options-dev]

### PR DESCRIPTION
**Pull request by acfisher**
I believe I know just enough cmake to make me dangerous, so let me know if I've missed something here.

Slides outlining the details of M1:
https://figshare.com/articles/xSDK_Community_Installation_Policies_GNU_Autoconf_and_CMake_Options/4495133

### CODE REVIEW

**Comment by acfisher** [comment]
I'll look at #445.  I thought I saw the changes that we made in there in master, but if not I'll merge these branches.

**Comment by tzanio** [comment]
@v-dobrev -- any objections to merging this?

**Comment by v-dobrev** [comment]
I'd move the additions to the main `CMakeLists.txt` to a separate file in `config/` or `config/cmake/`, e.g. called `XSDKTPLVars.cmake`, which is included by the main `CMakeLists.txt`.

**Comment by tzanio** [comment]
@acfisher, can you consider the above changes?

**Comment by v-dobrev** [comment]
I was thinking to put these variables in a separate file because `XSDKDefaults.cmake` is an exact copy of https://github.com/xsdk-project/XSDKCMakeProj/blob/master/xsdk/XSDKDefaults.cmake but this works too - we just need to remember to move the additions if we ever need to update `XSDKDefaults.cmake`.

**Pull request merged**
