### PR TITLE
Enhance netcdf file recognition.

### LINKED ISSUE #122: Loading newer Trelis (Cubit) generated meshes doesn't work
Using a recent Trelis version 16.1 (which is basically the only Cubit version for us Europeans) doesn't work with exported Genesis/Exodus files.

The issue is present in https://github.com/mfem/mfem/blob/master/mesh/mesh.cpp#L2615 which assumes  four "magic bytes" in the first line of the file containing "CDF". This has changed in some version of netCDF (i don't know which exactly) to "HDF" plus character code 211.

```
od -N 4 -c projects/nmpc_mfem/data/cyl.e
0000000 211   H   D   F
```

Providing the new magic bytes to the mesh reading process
```
else if (mesh_type.size() > 2 &&
            (mesh_type[0] == 'C' && mesh_type[1] == 'D' && mesh_type[2] == 'F') |
	    (mesh_type[1] == 'H' && mesh_type[2] == 'D' && mesh_type[3] == 'F'))
```
solves the issue and both versions can be opened correctly.

I can setup a PR if this is desired.

Regards

### PR DESCRIPTION
**Pull request by juan42**
This enhances the file recognition of netcdf files for new magic bytes which have changed in a recent version. It also fixes #122.

### CODE REVIEW

**Comment by v-dobrev** [comment]
Merged in the `next` branch for testing.

**Comment by tzanio** [comment]
Hi Julian,

Our testing caught a small formatting issue, do you mind giving us access to your forked branch so we can make the change directly in there?

See https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Tzanio

**Comment by juan42** [comment]
I ticked the "Allow edits from maintainers" and you should now be able to edit the fork directly.

**Comment by tzanio** [comment]
Thanks!

**Pull request merged**
