### PR TITLE
extend `ConduitDataCollection` to support `adjsets` exporting

### PR DESCRIPTION
**Pull request by xjrc**
This PR extends the `mfem::ConduitDataCollection` type so that it supports exporting adjacency information to [the `adjsets` subtree](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#adjacency-sets). This data is required to properly communicate domain abutment information to Blueprint-compliant clients when running in parallel.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#2366](https://github.com/mfem/mfem/pull/2366) | @xjrc | @tzanio | @tzanio + @rw-anderson | 11/02/21 | 11/08/21 | 11/10/21 | |

### CODE REVIEW

**Comment by tzanio** [comment]
@xjrc, please mark as `ready-for-review` when this is ready

**Comment by xjrc** [comment]
@tzanio: Certainly! I have one or two more small things to add and I'll post back here when things are ready.

**Comment by tzanio** [comment]
reminder 😁

**Comment by xjrc** [comment]
Thank you @tzanio! I just got back to this this morning, but now my build is broken! I'm hoping to get that fixed and have this implementation ready in the next week or so.

**Comment by xjrc** [comment]
@tzanio: Thanks, I've changed the tag and it looks like all of the checks outside of reviews are passing!

**Comment by tzanio** [comment]
got it, thanks @xjrc !

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
@cyrush, does this look good to you?

**Comment by tzanio** [comment]
Maybe consider mentioning in `CHANGELOG`?

**Review by cyrush — APPROVED** [review]
Yes, looks good.

It would be good to add a test that calls mesh blueprint verify from a wrapped example mesh (both par and non par) -- but that could be a future addition.

**Comment by cyrush** [comment]
I created a changelog entry PR for this: https://github.com/mfem/mfem/pull/2651

however, is this 4.4, or 4.3.1 (I may need to adjust changelog?)

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
