### PR TITLE
Compare PETSc 64bit int also with HYPRE_MIXEDINT

### PR DESCRIPTION
**Pull request by lindsayad**
64 bit indices is the default for MOOSE, so I ran into this. I'm pretty sure @stefanozampini wrote these macros so tagging him

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#4510](https://github.com/mfem/mfem/pull/4510) | @lindsayad | @tzanio | @stefanozampini + @jandrej | 9/26/24 | 10/15/24 | 10/19/24 | |

<details>
<summary>PR Checklist</summary>
    
- [ ] Code builds.
- [ ] Code passes `make style`.
- [ ] Update `CHANGELOG`:
    - [ ] Is this a new feature users need to be aware of? New or updated example or miniapp?
    - [ ] Does it make sense to create a new section in the `CHANGELOG` to group with other related features?
- [ ] Update `INSTALL`:
    - [ ] Had a new optional library been added? If so, what range of versions of this library are required? (*Make sure the external library is compatible with our BSD license, e.g. it is not licensed under GPL!*)
    - [ ] Have the version ranges for any required or optional libraries changed?
    - [ ] Does `make` or `cmake` have a new target?
    - [ ] Did the requirements or the installation process change? *(rare)*
- [ ] Update continuous integration server configurations if necessary (e.g. with new version requirements for each of MFEM's dependencies)
    - [ ] `.github`
    - [ ] `.appveyor.yml`
- [ ] Update `.gitignore`:
    - [ ] Check if `make distclean; git status` shows any files that were generated from the source by the project (not an IDE) but we don't want to track in the repository.
    - [ ] Add new patterns (just for the new files above) and re-run the above test.
- [ ] New examples:
    - [ ] All sample runs at the top of the example source file work.
    - [ ] Update `examples/makefile`:
      - [ ] Add the example code to the appropriate `SEQ_EXAMPLES` and `PAR_EXAMPLES` variables.
      - [ ] Add any files generated by it to the `clean` target.
      - [ ] Add the example binary and any files generated by it to the top-level `.gitignore` file.
    - [ ] Update `examples/CMakeLists.txt`:
      - [ ] Add the example code to the `ALL_EXE_SRCS` variable.
      - [ ] Make sure `THIS_TEST_OPTIONS` is set correctly for the new example.
   - [ ] List the new example in `doc/CodeDocumentation.dox`.
   - [ ] If new examples directory (e.g.`examples/pumi`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
      - [ ] Update or add example-specific documentation, see e.g. the `src/examples.md`.
      - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
      - [ ] In `examples.md`, list the example under the appropriate categories, add new categories if necessary.
      - [ ] Add a short description of the example in the "Extensive Examples" section of `features.md`.
- [ ] New miniapps:
   - [ ] All sample runs at the top of the miniapp source file work.
   - [ ] Update top-level `makefile` and `makefile` in corresponding miniapp directory.
   - [ ] Add the miniapp binary and any files generated by it to the top-level `.gitignore` file.
   - [ ] Update CMake build system:
      - [ ] Update the `CMakeLists.txt` file in the `miniapps` directory, if the new miniapp is in a new directory.
      - [ ] Add/update the `CMakeLists.txt` file in the new miniapp directory.
      - [ ] Consider adding a new test for the new miniapp.
   - [ ] List the new miniapp in `doc/CodeDocumentation.dox`
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), add it to `MINIAPP_SUBDIRS` in the `makefile`.
   - [ ] If new miniapps directory (e.g.`miniapps/nurbs`), list it in `doc/CodeDocumentation.conf.in`
   - [ ] Companion pull request for documentation in [mfem/web](https://github.com/mfem/web) repo:
     - [ ] Update or add miniapp-specific documentation, see e.g. the `src/meshing.md` and `src/electromagnetics.md` files.
     - [ ] Add the description, labels and screenshots in `src/examples.md` and `src/img`.
     - [ ] The miniapps go at the end of the page, and are usually listed only under a specific "Application (PDE)" category.
     - [ ] Add a short description of the miniapp in the "Extensive Examples" section of `features.md`.
- [ ] New capability:
   - [ ] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
   - [ ] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
   - [ ] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
   - [ ] Consider adding new sample runs in existing examples to highlight the new capability.
   - [ ] Consider saving cool simulation pictures with the new capability in the Confluence gallery (LLNL only) or submitting them, via pull request, to the gallery section of the `mfem/web` repo.
   - [ ] If this is a major new feature, consider mentioning it in the short summary inside `README` *(rare)*.
   - [ ] List major new classes in `doc/CodeDocumentation.dox` *(rare)*.
- [ ] Update this checklist, if the new pull request affects it.
- [ ] Run `make unittest` to make sure all unit tests pass.
- [ ] Run the tests in `tests/scripts`.
- [ ] (LLNL only) After merging:
   - [ ] Update internal tests to include the new features.
</details>

### CODE REVIEW

**Comment by stefanozampini** [comment]
At the time I wrote them, MFEM did not support MIXED_INT configurations for hypre. Probably that has changed now, @tzanio ? I think I have tried at some point, but something was broken

@lindsayad Can you please try running all the PETSc tests and confirm everything works?
```
$ cd ${PETSC_DIR}/${PETSC_ARCH}/externalpackages/git.mfem/petsc-build/examples/petsc/
$ make test
```

**Comment by jandrej** [comment]
> At the time I wrote them, MFEM did not support MIXED_INT configurations for hypre

Hypre mixed integer support has been added in MFEM Version 4.3, released on July 29, 2021.

**Comment by lindsayad** [comment]
Let's see... I see a failure with ex2p which is
```
[0]PETSC ERROR: No support for this operation for this object type
[0]PETSC ERROR: Unspecified symbolic phase for product AB with A mpiaij, B mpiaijcusparse. The product is not supported
[0]PETSC ERROR: WARNING! There are unused option(s) set! Could be the program crashed before usage or a spelling mistake, etc!
[0]PETSC ERROR:   Option left: name:-ksp_converged_reason (no value) source: file
[0]PETSC ERROR:   Option left: name:-ksp_view (no value) source: file
[0]PETSC ERROR:   Option left: name:-mg_levels_esteig_ksp_max_it value: 10 source: file
[0]PETSC ERROR:   Option left: name:-mg_levels_esteig_ksp_type value: cg source: file
[0]PETSC ERROR:   Option left: name:-mg_levels_ksp_chebyshev_esteig value: 0,0.05,0,1.05 source: file
[0]PETSC ERROR:   Option left: name:-mg_levels_ksp_max_it value: 2 source: file
[0]PETSC ERROR:   Option left: name:-mg_levels_ksp_type value: chebyshev source: file
[0]PETSC ERROR:   Option left: name:-mg_levels_pc_type value: sor source: file
[0]PETSC ERROR:   Option left: name:-pc_gamg_agg_nsmooths value: 1 source: file
[0]PETSC ERROR:   Option left: name:-pc_gamg_coarse_eq_limit value: 100 source: file
[0]PETSC ERROR:   Option left: name:-pc_gamg_reuse_interpolation value: true source: file
[0]PETSC ERROR:   Option left: name:-pc_gamg_square_graph value: 1 source: file
[0]PETSC ERROR:   Option left: name:-pc_gamg_threshold value: 0.0 source: file
[0]PETSC ERROR:   Option left: name:-pc_gamg_type value: agg source: file
[0]PETSC ERROR:   Option left: name:-pc_type value: gamg source: file
[0]PETSC ERROR: See https://petsc.org/release/faq/ for trouble shooting.
[0]PETSC ERROR: Petsc Development GIT revision: v3.21.5-558-g895b37aaba3  GIT Date: 2024-09-17 14:18:01 +0000
[0]PETSC ERROR: Unknown Name with 4 MPI process(es) and PETSC_ARCH arch-moose on rod.hpc.inl.gov by lindad Tue Sep 17 16:11:48 2024
[0]PETSC ERROR: Configure options: --with-64-bit-indices --with-cxx-dialect=C++17 --with-debugging=no --with-fortran-bindings=0 --with-mpi=1 --with-openmp=1 --with-strict-petscerrorcode=1 --with-shared-libraries=1 --with-sowing=0 --download-fblaslapack=1 --download-hpddm=1 --download-hypre=1 --download-metis=1 --download-mumps=1 --download-ptscotch=1 --download-parmetis=1 --download-scalapack=1 --download-slepc=1 --download-strumpack=1 --download-superlu_dist=1 --download-hdf5=1 --with-hdf5-fortran-bindings=0 --download-hdf5-configure-arguments="--with-zlib"  --with-cuda --download-mfem --download-libceed --download-slate --with-make-np=32
[0]PETSC ERROR: #1 MatProductSymbolic() at /data/lindad/gpu-moose/petsc/src/mat/interface/matproduct.c:813
[0]PETSC ERROR: #2 MatProductSymbolic_PtAP_Unsafe() at /data/lindad/gpu-moose/petsc/src/mat/interface/matproduct.c:73
[0]PETSC ERROR: #3 MatProductSymbolic_Unsafe() at /data/lindad/gpu-moose/petsc/src/mat/interface/matproduct.c:185
[0]PETSC ERROR: #4 MatProductSymbolic() at /data/lindad/gpu-moose/petsc/src/mat/interface/matproduct.c:800
[0]PETSC ERROR: #5 MatPtAP() at /data/lindad/gpu-moose/petsc/src/mat/interface/matrix.c:10184
[0]PETSC ERROR: #6 mfem::PetscParMatrix* mfem::RAP(PetscParMatrix*, PetscParMatrix*, PetscParMatrix*)() at /data/lindad/gpu-moose/petsc/arch-moose/externalpackages/git.mfem/linalg/petsc.cpp:2188
```
This reminds me of what Junchao [was seeing in discord](https://discord.com/channels/1119324534303109172/1280678847842488434/1281289597136932905). 

Similar stack trace for failures of ex5p, ex6p. ex10p has a different failure
```
  0 SNES Function norm 1.484772858574e-01
  1 SNES Function norm 9.961870690705e-03
  2 SNES Function norm 3.636486532052e-03
  3 SNES Function norm 2.191767101921e-05
  4 SNES Function norm 4.538811657514e-08
  5 SNES Function norm 6.671643317436e-13


Verification failed: (it != maps->memories.end()) is false:
 --> host pointer is not registered: h_ptr = 0x56f4030
 ... in function: static void mfem::MemoryManager::CheckHostMemoryType_(mfem::MemoryType, void*, bool)
 ... in file: /data/lindad/gpu-moose/petsc/arch-moose/externalpackages/git.mfem/general/mem_manager.cpp:1710



Verification failed: (it != maps->memories.end()) is false:
 --> host pointer is not registered: h_ptr = 0x49be920
 ... in function: static void mfem::MemoryManager::CheckHostMemoryType_(mfem::MemoryType, void*, bool)
 ... in file: /data/lindad/gpu-moose/petsc/arch-moose/externalpackages/git.mfem/general/mem_manager.cpp:1710



Verification failed: (it != maps->memories.end()) is false:
 --> host pointer is not registered: h_ptr = 0x475f7d0
 ... in function: static void mfem::MemoryManager::CheckHostMemoryType_(mfem::MemoryType, void*, bool)
 ... in file: /data/lindad/gpu-moose/petsc/arch-moose/externalpackages/git.mfem/general/mem_manager.cpp:1710



Verification failed: (it != maps->memories.end()) is false:
 --> host pointer is not registered: h_ptr = 0x5a186d0
 ... in function: static void mfem::MemoryManager::CheckHostMemoryType_(mfem::MemoryType, void*, bool)
 ... in file: /data/lindad/gpu-moose/petsc/arch-moose/externalpackages/git.mfem/general/mem_manager.cpp:1710

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 3 in communicator MPI_COMM_WORLD
  Proc: [[33376,1],3]
  Errorcode: 1

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
prterun has exited due to process rank 1 with PID 0 on node rod calling
"abort". This may have caused other processes in the application to be
terminated by signals sent by prterun (as reported here).
--------------------------------------------------------------------------
make: *** [/data/lindad/gpu-moose/petsc/arch-moose/externalpackages/git.mfem/examples/petsc/makefile:148: ex10p-test-par] Error 1
```

**Comment by lindsayad** [comment]
This was with PETSc hash `895b37aaba3e83f8a13cbd4424acd9aec3d4f3d4` which should include your most recent MFEM-related MR @stefanozampini

**Comment by stefanozampini** [comment]
Best to include the latest mfem and to not use a cuda capable install.

**Comment by lindsayad** [comment]
I was testing with the hash in this PR which is rebased on top of the most recent mfem master. Changing to not use a cuda capable install, all tests pass
```
lindad@rod:/data/lindad/petsc/hypre-mfem-no-cuda/externalpackages/git.mfem/petsc-build/examples/petsc(hypre-mixed-int)$ make test
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex1p ... ]: OK  (1.36s 76016kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex1p ... ]: OK  (1.82s 128700kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex2p ... ]: OK  (0.42s 67132kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex2p ... ]: OK  (0.38s 69924kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex2p ... ]: OK  (0.36s 59812kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex3p ... ]: OK  (2.07s 176728kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex3p ... ]: OK  (4.89s 223832kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex4p ... ]: OK  (2.03s 175352kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex4p ... ]: OK  (1.82s 228748kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex5p ... ]: OK  (3.54s 399240kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex5p ... ]: OK  (3.55s 400008kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex5p ... ]: OK  (5.09s 364096kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex6p ... ]: OK  (13.12s 157152kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex6p ... ]: OK  (15.57s 142588kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex9p ... ]: OK  (8.98s 57848kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex9p ... ]: OK  (3.72s 57728kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex9p ... ]: OK  (1.68s 67960kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex10p ... ]: OK  (6.36s 58260kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex10p ... ]: OK  (0.99s 52064kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex10p ... ]: OK  (0.90s 55824kB)
    Parallel PETSc example [ /opt/mpich/bin/mpiexec -np 4 ex10p ... ]: OK  (0.92s 56968kB)
```

**Review by stefanozampini — APPROVED** [review]
LGTM since the tests pass. Thanks @lindsayad

**Comment by lindsayad** [comment]
I made this PR very late at night ... I feel like there was a checklist which I removed 😅 😬 Sorry about that. Please let me know what additional steps are needed to get this ready for merge

**Comment by tzanio** [comment]
No worries, thanks for the contribution @lindsayad !

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Comment by tzanio** [comment]
ping: @jandrej

**Review by jandrej — APPROVED** [review]

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by lindsayad** [comment]
thanks all!

**Pull request merged**
