### PR TITLE
[WIP] Add automatic generation of edge2knot for NURBS meshes [nurbs-knot2edge]

### PR DESCRIPTION
**Pull request by IdoAkkerman**
This PR does several things:
- It removes the need to define the edge to knot mapping in the mesh. This is automatically generated instead.
- Orientation check of patch is removed, this is not necessary (Check??!!) and to resctrictive for multi-patch meshes.
- It adds a routine to compute the location of the maxima of the shapefunctions.
- It adds the option to generate  controle points  that will generate curves that will go through the defined points. This routine uses the location of the maxima of the shapefunctions as collocation  points.
- A second type of Calc??Shape is added. This will compute the shapes and derivative wrt the knot coodinate,  at the knot coordinate. This instead of the element coordinate xi.
- PrintFunctions is changed to plot the global function instead of the local functions
- Two routines without capital letter are renamed

### CODE REVIEW

**Comment by JacobLotz** [comment]
Edit JacobLotz:
The following implementations are to ensure the "Check??!!" in @IdoAkkerman his notes above.
- The necessary orientation check of patch is replaced by a more general definition of the KnotVectors. The KnotVectors are now defined in two different ways: a set of unique (reduced) KnotVectors KnotVecRed and an extended set of KnotVectors KnotVecExt which is an array containing dim x npatch KnotVectors. In this last set the KnotVectors can be flipped if required for a specific patch orientation. This is for instance the case for a C-shaped mesh. Checks have been added to ensure consistency between the two arrays of KnotVectors.
- Tests which use meshes with two NURBSPatches have been added to show that the orientation of the NURBSPatch is not important anymore. The number of added tests is 4*4 for 2D and 3D cases separately, making a total of 32. The tests contain all the possible combinations of the rotation of the NURBSPatches. The meshes are generated using two meshers, one for 2D and one for 3D, in two tests. The solution of all the 2D cases should be the same and the solution of all the 3D cases should be the same.
- A routine for rotating a 2D NURBSPatch is added. 
- A function which prints all the KnotVectors in a NURBSPatch is added

Only one check fails: repo-check / branch-history (push)
This arises from a try to solve a conflict between branches master and nurbs-knot2edge. This is reverted and master is merged into nurbs-knot2edge. According to #2650 this can be solved using a squash-merge.
All the other checks are succesful.

**Comment by JacobLotz** [comment]
> This PR does several things:
> 
>     * It removes the need to define the edge to knot mapping in the mesh. This is automatically generated instead.
> 
>     * Orientation check of patch is removed, this is not necessary (Check??!!) and to resctrictive for multi-patch meshes.
> 
>     * It adds a routine to compute the location of the maxima of the shapefunctions.
> 
>     * It adds the option to generate  controle points  that will generate curves that will go through the defined points. This routine uses the location of the maxima of the shapefunctions as collocation  points.
> 
>     * A second type of Calc??Shape is added. This will compute the shapes and derivative wrt the knot coodinate,  at the knot coordinate. This instead of the element coordinate xi.
> 
>     * PrintFunctions is changed to plot the global function instead of the local functions
> 
>     * Two routines without capital letter are renamed

**Comment by IdoAkkerman** [comment]
I have submitted a new PR #2724  in order to fix the history issue.

**Comment by v-dobrev** [comment]
Superseded by #2724.

**Pull request closed without merging**
