### PR TITLE
[WIP] Fast nondeterministic mass kernels

### PR DESCRIPTION
**Pull request by camierjs**
Initial setup for `fast` nondeterministic kernel optimizations of the mass/diagonal kernels for `ex1` and `Laghos`.
The only speedups are brought here by avoiding the L ⇒ E `Mult` and `MultTranspose` operations.
To use the `fast` kernels, the device option must be set with `-d dev:fast`
A `version` number can be added as follow: `-d dev:fast1` or  `-d dev:fast2`

`MFEM_USE_BENCHMARKS=YES` can be when configuring `MFEM` to have access to the `tests/benchmarks` sub-directory benchmarks. A [Google-Benchmark](https://github.com/google/benchmark) installation should be available in `../google-benchmark`.

To test on `MI100`, the following command line could be used:
`make distclean && make serial -j MFEM_USE_BENCHMARK=YES CPPFLAGS=-g MFEM_USE_HIP=YES HIP_ARCH=gfx908`

In the `tests/benchmarks` sub-directory, `make bench_ceed` allow to run the command: 
`./bench_ceed --benchmark_filter=BP1 --benchmark_context=device=hip` for the 'default' `hip` implementation, and:
`./bench_ceed --benchmark_filter=BP1 --benchmark_context=device=hip:fast7` for the `fast7` one.

### Generating plots
Plots can be generated with some following commands:
`./bench_ceed --benchmark_filter=BP1 --benchmark_context=device=hip:fast7 --benchmark_out=bp1_mi100_fast7.org --benchmark_out_format=csv --benchmark_min_time=1`
`xelatex -file-line-error -shell-escape -interaction nonstopmode -halt-on-error bench_ceed.tex`

### Fast1 @ `V100`:
```
----------------------------------------------------------------
Benchmark           Time             CPU   Iterations     MDof/s
----------------------------------------------------------------
BP1/1            3.67 ms         3.67 ms          190   313.55/s
BP1/2            5.58 ms         5.58 ms          123 1.57449k/s
BP1/3            11.4 ms         11.4 ms           61 2.56597k/s
BP1/4            22.0 ms         22.0 ms           31 3.12715k/s
BP1/5            39.5 ms         39.5 ms           18  3.3839k/s
BP1/6            67.4 ms         65.6 ms           10 3.50729k/s
```

### Fast7 @ `V100`:
```
----------------------------------------------------------------
Benchmark           Time             CPU   Iterations     MDof/s
----------------------------------------------------------------
BP1/1            4.61 ms         4.61 ms          152   249.29/s
BP1/2            5.65 ms         5.65 ms          121 1.55434k/s
BP1/3            11.3 ms         11.3 ms           61 2.57661k/s
BP1/4            22.0 ms         22.0 ms           31 3.12509k/s
BP1/5            38.9 ms         38.9 ms           18 3.43151k/s
BP1/6            63.2 ms         61.2 ms           11 3.75724k/s
```

### Fast1 @ `MI100`
```
----------------------------------------------------------------
Benchmark           Time             CPU   Iterations     MDof/s
----------------------------------------------------------------
BP1/1            5.93 ms         5.93 ms          118  193.966/s
BP1/2            9.10 ms         9.09 ms           79  966.782/s
BP1/3            14.9 ms         14.9 ms           47 1.96132k/s
BP1/4            30.5 ms         30.5 ms           23 2.25583k/s
BP1/5             151 ms          151 ms            5  884.561/s
BP1/6             222 ms          222 ms            3  1038.35/s
```

### Fast7 @ `MI100`
```
----------------------------------------------------------------
Benchmark           Time             CPU   Iterations     MDof/s
----------------------------------------------------------------
BP1/1            7.62 ms         7.62 ms           92  150.899/s
BP1/2            12.1 ms         12.1 ms           59  728.766/s
BP1/3            17.5 ms         17.5 ms           40 1.66536k/s
BP1/4            27.7 ms         27.7 ms           25 2.47717k/s
BP1/5             101 ms          101 ms            7 1.31947k/s
BP1/6             197 ms          197 ms            4 1.16956k/s
```

---
### MFEM, example 1

```
make ex1 
./ex1 -pa -m ../data/inline-hex.mesh -o 4 -d hip:fast
./ex1 -pa -m ../data/inline-hex.mesh -o 4 -d cpu:fast
./ex1 -pa -m ../data/inline-hex.mesh -o 4 -d cuda:fast
./ex1 -pa -m ../data/inline-hex.mesh -o 4 -d cuda:fast1
./ex1 -pa -m ../data/inline-hex.mesh -o 4 -d cuda:fast2
./ex1 -pa -m ../data/inline-hex.mesh -o 4 -d cuda:fast7
```

---

### LAGHOS, Sedov & Triple point

```
./laghos -p 1 -pa -ms 50 -f -rs 3 -ok 4 -ot 3 -d cuda:fast
./laghos -p 1 -pa -ms 50 -f -rs 3 -ok 4 -ot 3 -d cuda:fast1
./laghos -p 1 -pa -ms 50 -f -rs 3 -ok 4 -ot 3 -d cuda:fast2
./laghos -p 3 -m data/box01_hex.mesh -rs 3 -pa -d cuda:fast -ms 10 -f -ok 4 -ot 3
```

### CODE REVIEW

**Comment by artv3** [comment]
I'm curious about this, could this improve performance for nvidia gpus as well?

**Comment by camierjs** [comment]
> I'm curious about this, could this improve performance for nvidia gpus as well?

It does, yes.

**Comment by artv3** [comment]
Why are the iteration counts different between the versions on the chart above?

**Comment by camierjs** [comment]
> Why are the iteration counts different between the versions on the chart above?

These `Iterations` are the number of times the test is run: it depends on the time of the test itself.
The benchmark will try to launch a maximum of them, with a minimum of `1`.

**Comment by camierjs** [comment]
Will be reworked in a new PR with the `fast` device option.

**Pull request closed without merging**
