### PR TITLE
Add an option for grace-exit [sshiraiwa:graceexit]

### PR DESCRIPTION
**Pull request by sshiraiwa**
Dear team,

Thank you for providing this powerful FEM library. 

Based on a conversation last week, this pull request is to add an option to 
raise a custom error class, so that we can catch it in a SWIG wrapper layer. An issue here is that when working with MFEM interactively from Python, I can blow up the whole Python interpreter by making
a small (;D) mistake.  In the example below, I tried to open a mesh file, which does
not exist. And since MFEM calls mfem_error, it killed an interpreter. 

screen shot 2018-02-16 at 12 18 07 pm

I would rather like to keep the python interpretor alive. 

This pull adds one global variable (mfem_use_throw) in the mfem namespace, which 
a user can access via set_use_throw/get_use_throw. When mfem_use_throw is True, 
mfem_error throws an error instead of calling abort.  Below, it shows how it behaves in Python 

screen shot 2018-02-16 at 12 17 53 pm

Please let me know what you think. Also, please note that only serial environment is 
considered.

### CODE REVIEW

**Comment by tzanio** [comment]
Hi Syun'ichi,

We will prefer not to build any code with exceptions by default, so I made a small change in https://github.com/mfem/mfem/pull/433/commits/0ef9ff252f0cb353f0c5753662fd2047c43d88ab.

You will need to config with `MFEM_USE_EXCEPTIONS=YES`.

If that works for you, we may also consider removing `set`/`get_use_throw`.

**Comment by sshiraiwa** [comment]
Hi Tzanio,

Okay. It should work. Actually, this was what I thought first ;D. 

--
S

**Comment by v-dobrev** [comment]
@sshiraiwa, @tzanio, I made some changes - take a look to see if you are OK with them.

**Comment by gelever** [comment]
@tzanio Somewhat related: Doesn't `fem/picojson.h` throw exceptions and is included by default?

**Comment by sshiraiwa** [comment]
HI all,  Thank you. I made a corresponding adjustment in PyMFEM (grace-exit-support branch). I only made changes in the serial version (mfem.ser modules). Once this is merged to master, I will merge the branch too in PyMFEM and apply the same adjustment in mfem.par.

**Comment by v-dobrev** [comment]
You are welcome, @sshiraiwa. Thank you for the PR.

I was wondering about the parallel case - I'm not sure how this will work in parallel in PyMFEM. For example: what will happen if only some of the ranks actually throw an exception? Probably a deadlock? Anyway, hopefully, this PR is a good start for better error handling in PyMFEM.

**Comment by sshiraiwa** [comment]
If one rank throws an exception and others started to MPI communication, it will make a deadlock. This pull is mainly motivated to improve the user interaction in a serial mode. I agree that a user still needs to be extremely careful to use it in parallel environment, and TBH, I don't know if there is general approach to such a case.

**Pull request merged**
