### PR TITLE
NCMesh memory optimizations [ncmesh-mem-opt-dev]

### PR DESCRIPTION
**Pull request by jakubcerveny**
This adds the following memory optimizations in the NCMesh class:

* Most 64-bit pointers (to child elements, nodes, etc.) were replaced by 32-bit ints.
* The ints are indices into NCMesh::elements, NCMesh::nodes and NCMesh::faces. These are instances of a new container, BlockArray<T> (or its subclass HashTable<T>).
* BlockArray<T> is a fast allocator, it allocates T in chunks. It allows the slots in the container to be freed and reused later. 
* HashTable<T> now uses BlockArray<T> for storage, and adds the usual hashing on top of it. There are some changes in the interface because of the primary use of indices to refer  to items.
* NCMesh::Vertex, NCMesh::Edge and NCMesh::RefCount are all gone. I realized they're not needed.
* NCMesh::Node and NCMesh::Face are smaller. Nodes just track the vertex and edge reference counts and their indices in the Mesh.
* NCMesh::top_vertex_pos contains the coordinates of top-level vertices and is practically the only geometry left in NCMesh now. If the Mesh is not curved, this member is used to calculate positions of all vertices (in NCMesh::GetMeshComponents, see also NCMesh::CalcVertexPos).
  
Changes in ex1 and ex9p are not to be merged. In ex1 there is some code to measure the memory use of NCMesh.

Compared to master (you can try running the modified ex1 in there), NCMesh now uses 50% less memory (in total). The average cost of an NC element (including the refinement hierarchy, but not including the temporary
face_list and edge_list) is now only about 290 bytes. Also, the total time of the testing ex1 is now 30-40% smaller.

ParNCMesh could use some optimization too, but I only had time to make it work again with the new NCMesh. Maybe some other time. 

There's quite a few changes in NCMesh and ParNCMesh. I tried to make sure all examples work, especially ex1/p, ex6/p, ex9/p and ex14/p. 

The changes in this PR need not be studied in detail, there's a lot of boring stuff. We should make sure all examples work exactly as before, though.

### CODE REVIEW

**Comment by tzanio** [comment]
@rw-anderson, @mlstowell and @v-dobrev, do you mind taking a look / approving this?

**Comment by v-dobrev** [comment]
We need to fix the travis ci file - `make check` failed but it was not reported properly because it exited with code 0.

**Comment by tzanio** [comment]
Hmm, looking at https://travis-ci.org/mfem/mfem/jobs/209589765 I would have expected a failure... there was a core dump after all.

**Comment by tzanio** [comment]
@mlstowell and @rw-anderson do you mind if we merge this PR in, or do you need more time to review it?

**Pull request merged**
