### PR TITLE
Batched LOR assembly with GPU support

### PR DESCRIPTION
**Pull request by pazner**
This PR adds functionality for "batched LOR assembly" with GPU support. This allows for the assembly of the sparse matrices representing the low-order-refined discretizations in an efficient way. Additionally, the efficient creation of LOR `HypreAMS` and `HypreADS` solvers is supported. The LOR solvers miniapp is updated for full GPU support.

The user-facing interface is basically unchanged. If it is possible to use the optimized (batched) kernels, it will happen automatically.

There are basically no diffs to the `lor_solvers` (just adding the `Device`), and the batched assembly is automatically enabled. Diffs to the parallel version `plor_solvers` are extremely minimal, and batched assembly for the matrix, AMS, and ADS is enabled automatically.

H1 diffusion + mass, ND curl-curl + mass, and RT div-div + mass are supported.

Features:

* Expensive preprocessing steps (creating the actual LOR mesh and FE space) can be skipped completely, resulting in significant speedups.
* GPU support for fully assembling the LOR matrices in `SparseMatrix` or `HypreParMatrix` format.
* GPU support for assembling the discrete gradient, discrete curl, and coordinate vectors needed by AMS and ADS solvers.
* Unit tests to make sure that the batched assembly results in the same matrices as the legacy code.

Big thanks to @camierjs for help with this PR!

Some timing results, measuring the LOR matrix assembly. The mesh is `fichera` with three refinements, order 7.

| | H1 | H(curl) | H(div) |
| - | - | - | - |
| Legacy, quartz, 1 CPU | 11.182 | 27.610 | 13.686 |
| Batched, quartz, 1 CPU | 3.964 | 16.932 | 3.993 |
| Batched, lassen, 1 GPU | 0.0812 | 0.2101 | 0.0459 |

Some throughput plots:

| Before | After |
| - | - |
| all_full_log | ker_batched_log |

| AMS Coordinates | AMS Gradient | ND Assembly |
| - | - | -  |
| ams_coordinates | ams_gradient | nd_ker_batched |

Note: for now, only constant coefficients are supported. Variable coefficients can be added easily when a feature like #2891 or #1656 is merged.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge|
 | --- | --- | --- | --- | --- | --- | --- |
| [#2966](https://github.com/mfem/mfem/pull/2966) | @pazner | @tzanio | @tzanio + @artv3 + @YohannDudouit + @camierjs | 4/14/22 | 4/26/22 | 5/9/22 | |

**PR Checklist**
    
- [x] Code builds.
- [x] Code passes `make style`.
- [x] Update `CHANGELOG`
- [x] All sample runs at the top of the miniapp source file work.
- [x] All new public, protected, and private classes, methods, data members, and functions have full Doxygen-style documentation in source comments. Documentation should include descriptions of member data, function arguments and return values, template parameters, and prerequisites for calling new functions.
- [x] Pointer arguments and return values must specify whether ownership is being transferred or lent with the call.
- [x] Any new functions should include descriptions of their intended use e.g. for internal use only, user-facing, etc., along with references to example code whenever possible/appropriate.
- [x] Consider adding new sample runs in existing examples to highlight the new capability.

### CODE REVIEW

**Comment by tzanio** [comment]
This PR is now [under review](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests) (see the table in the PR description). To help with the review process, please **do not force push** to the branch.

**Review by tzanio — APPROVED** [review]
I like the new organization, the clarity of the implementation and most importantly the impressive performance improvements... thank you @pazner and @camierjs 🚀 

Please make sure to address the PR checklist items in the description

**Review by artv3 — APPROVED** [review]
Awesome work!!

**Review by camierjs — APPROVED** [review]
Awesome contribution @pazner, with huge potential impact!
Used, sanitized check ⇒ everything looks good!

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by tzanio** [comment]
Re-merged in `next` for testing...

**Comment by v-dobrev** [comment]
One of the tests on LC Gitlab actually failed -- I'm not sure why it is shown here with a green check. Probably the sub-pipelines we use confuse it somehow.

**Comment by tzanio** [comment]
Re-merged in `next` for testing...

**Pull request merged**
