### PR TITLE
Renamed Example 22 to Example 21 [ex22-rename]

### PR DESCRIPTION
**Pull request by tzanio**
(to close the gap in numbering before the mfem-4.0 release)

### CODE REVIEW

**Comment by mlstowell** [comment]
My only concern, and it's a small one, is that related examples are easier to remember if their numbers are related.  For example, ex2, ex12, and ex22 are currently all related to elasticity.

**Comment by tzanio** [comment]
> My only concern, and it's a small one, is that related examples are easier to remember if their numbers are related. For example, ex2, ex12, and ex22 are currently all related to elasticity.

True. This is nice.

I am willing to be convinced if both you and @v-dobrev feel that maintaining the numbering is preferable to having continuous examples numbering.

**Comment by v-dobrev** [comment]
I'll be fine with either choice. Toss a coin. 😃

**Comment by tzanio** [comment]
Ok, I'll make the change now and if we want we can rename again when we add the next Example.

**Comment by tzanio** [comment]
@mlstowell or @v-dobrev do you mind approving this so we can merge it?

**Pull request merged**
