### PR TITLE
Small bug when compiling without LAPACK

### PR DESCRIPTION
**Pull request by psocratis**

### CODE REVIEW

**Review by brendankeith — APPROVED** [review]

**Comment by tzanio** [comment]
@psocratis since this is a minor change, can you please just add it in https://github.com/mfem/mfem/pull/4172?

**Comment by v-dobrev** [comment]
> @psocratis since this is a minor change, can you please just add it in #4172 and close this PR?

Another option is to add it to #4236 which already has some fixes for Example 33/33p.

**Comment by v-dobrev** [comment]
We can switch the target branch of this to #4236 and merge it there for review.

**Comment by psocratis** [comment]
> We can switch the target branch of this to #4236 and merge it there for review.

I will add the change to #4236 and close this. Thanks.

**Pull request closed without merging**
