### PR TITLE
Expose more parallelism in some kernels [feature/stitt4/more-work-units]

### PR DESCRIPTION
**Pull request by tomstitt**
Updates `PADiffusionSetup{2,3}D` and `QuadratureInterpolator::Eval{2,3}D` to expose more units of work, 1 thread/element wasn't enough.

The `PADiffusionSetup` kernels are now over `NE*NQ` instead of just `NE` and the `Eval{2,3}D` kernels are now shared-memory kernels of size `max(NQ, ND)` instead of just over `NE`.

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#1622](https://github.com/mfem/mfem/pull/1622) | @tomstitt | @tzanio | @artv3 + @camierjs | 07/15/20 | 08/13/20 | 08/19/20 | |

### CODE REVIEW

**Comment by tzanio** [comment]
@tomstitt, please mark this as `ready-for-review` when it is ready, see https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#pull-requests

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Comment by camierjs** [comment]
Thanks for pushing on the PA setup kernel, that is something that needs to be improved: great!

Could we try to use instead of the `for (int q = 0; q < NQ; ++q)` two inner for-loops?
I'd also like to turn the inner computation into a `kernels::` call of `linalg/kernels.hpp` that we can populate.

Let me know if you need any help.

**Comment by camierjs** [comment]
I've updated the mass and diffusion setup kernels @tomstitt : can you test in the code ?

**Comment by camierjs** [comment]
LGTM

**Comment by tomstitt** [comment]
> I've updated the mass and diffusion setup kernels @tomstitt : can you test in the code ?

Thanks @camierjs , I'm testing it this morning

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
