### PR TITLE
Transparently handle essential boundary conditions in PetscSolver and give the user a callback to construct preconditioners [handle-essbc-and-preconditioners]

### PR DESCRIPTION
**Pull request by stefanozampini**
Allows the user to create an helper object to handle essential boundary conditions, without the burden to zero rows and columns, change the rhs and so on. This is consistently handled by the private routines that create the Jacobian and evaluate the current residual. I have a student already using this branch. We will commit an example later in a different branch.

The helper object needs to provide the Eval method to compute the values of the boundary conditions at a given time (returned in a Vector of size tdofs); an internal caching mechanism is in place to prevent calling the method if not needed.

The user can also handle the creation of a preconditioner inside a time-dependent or nonlinear simulation.

### CODE REVIEW

**Comment by tzanio** [comment]
@stefanozampini, is this similar to how boundary conditions are handled on Operator level in https://github.com/mfem/mfem/blob/master/linalg/operator.hpp#L100?

**Comment by stefanozampini** [comment]
It's similar, but it is done at the level of the nonlinear and ODE solvers (I can add it to the linear solver class too). I have tested the implementation with a time-domain maxwell solver (with time-dependent bc), not yet with a nonlinear one.

basically, you sample jacobians and residuals strongly imposing the correct values of the boundary conditions. Below is my source of inspiration ...you may know the author...  This is a trick that I have always used, even with ODE solvers, since it is quite natural from within the PETSc framework (TS)

https://scicomp.stackexchange.com/questions/3298/appropriate-space-for-weak-solutions-to-an-elliptical-pde-with-mixed-inhomogeneo

**Comment by stefanozampini** [comment]
I decided to add this new feature of PetscPreconditionerFactory on top of the essential-bc work.
This branch will require some more days of testing from me before it could be merged.

**Comment by stefanozampini** [comment]
I merged to next. Should be ready to be merged to master

**Comment by tzanio** [comment]
@stefanozampini, the workflow is to wait for all approvals before merging into `next` :)

**Comment by stefanozampini** [comment]
@tzanio sorry for that. Won't happen again :-(

**Comment by tzanio** [comment]
no worries... our fault for not having `CONTRIBUTING.md` to clarify this

**Pull request merged**
